### ISSUE TITLE
No build/package instruction for distros other that Debian?

### ISSUE THREAD

**Issue by Yamakaky** [slgobinath/SafeEyes#1]

**Comment by slgobinath** [comment]
Hi,
I have added the manual installation instructions @ https://github.com/slgobinath/SafeEyes#other-linux.
Could you please try it and let me know whether it is working or not along with your Linux distribution name.
Thanks

**Comment by slgobinath** [comment]
Please see the updated installation methods for Arch and other Linux distributions @ https://github.com/slgobinath/SafeEyes#installation. If you can let me know your Linux distro, I will try my best to test on that distro.
Thanks.

**Comment by Yamakaky** [comment]
I don't think it's `pacman -R`. `pacman -U` maybe?

**Comment by slgobinath** [comment]
Ouch its by mistake. I've corrected it. Thanks again.

**Comment by Yamakaky** [comment]
https://aur.archlinux.org/packages/safeeyes/
Tell me if I forgot something. I put the files in `/usr/lib` instead of `/opt` because it seams more logical.

**Comment by Yamakaky** [comment]
You can remove `build/arch`, BTW.

**Comment by slgobinath** [comment]
Thank you very much @Yamakaky . I am a newbie to packaging apps and I have no experience with Arch. I really appreciate your support in packaging this app.
Thanks a lot for your suggestions and effort :-)

**Comment by Yamakaky** [comment]
Done.

**Comment by slgobinath** [comment]
Thank you @Yamakaky
