### ISSUE TITLE
Feature request: During the ten-second timer before the break starts, don't allow the user to suspend SafeEyes

### ISSUE THREAD

**Issue by JesseTG** [slgobinath/SafeEyes#100]
Otherwise it's easy to fall into the habit of just clicking "Suspend for 30 minutes"

**Comment by slgobinath** [comment]
Ha ha.. I am one of them ;-)
I will add it as part of the strict break. In other words if `Strict Break` is enabled, users can't pause during notification time.

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/faa015fe7a0e9b7d2dbf4966aab7e86a4758de37

**Comment by JesseTG** [comment]
Thanks!
