### ISSUE TITLE
Idea: Display urgent reminders at the bottom of the screen?

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#101]
Dear all, 

I would like to share an idea with you I had today. 

Safe Eyes has become a very important and dominant screen to look at. 

This makes it perfect to not only display an exercise but also some very important information, e.g. daily reminders you should not forget about, like calling Jon at 6 pm. 

How about the following:

If a file like `.SafeEyes/reminders.txt` exist, read in the information line by line and display it at the bottom of the Safe Eyes Black Screen.

What do you think? :-)

Yours,

Robert

**Comment by slgobinath** [comment]
+1 I was thinking about adding Safe Eyes extension support that can attract more developers to come up with their own plugins. For example weather plugin or reminder plugin.

However, I was in a confusion of asking users to spend some time on the screen even during the break. Even though it may be a fracture of second, I am little against to that ;-)

Let's start the discussion on this and decide based on the votes.

**Comment by orschiro** [comment]
Alright!

I assume we keep the discussion and the voting inside this thread, correct?

Looking forward to more opinions. :-)

**Comment by slgobinath** [comment]
Yep. Anyhow, I strongly agree with your suggestion and planning to add plugins for Safe Eyes, so my vote is for you :-).

**Comment by slgobinath** [comment]
Hi @orschiro,

Now you can come up with your own reminder (or else whatever you want ;-) ) with Safe Eyes. Read more about plugins and how to create your own plugin here: https://github.com/slgobinath/SafeEyes#write-safe-eyes-plugins
Eventhough the documentation is poor, I hope you can get the idea.
Note: The plugin support may be enhanced further before the release.

**Comment by orschiro** [comment]
Thank you!

I will take a look at it. :-)
