### ISSUE TITLE
Extension Support

### ISSUE THREAD

**Issue by slgobinath** [slgobinath/SafeEyes#104]
This is the feature I think as the solution for several other issues and provides more power and customizability to Safe Eyes.

Provide an interface to third-party developers to write extensions for Safe Eyes. A simple interface with the following methods will be provided to the developers:
```
preNotification(context):
    return

postNotification(context):
    return

preBreak(context):
# Limitations on text length will be applied to limit the time spent by the user.
# Because having a lengthy text which requires the user to read the screen
# even during the break collapses the purpose of Safe Eyes
     return "Text to display on the left/right panel" 

postBreak(context):
    return
```

The context will provide additional information about the break type, break text, whether the break is skipped or end automatically, is the idle break on or off, configurations related to the plugin etc.

Safe Eyes will load all the Python classes from `~/.config/safeeyes/extensions/<ext-name>/extension.py` along with extension specific configurations from `~/.config/safeeyes/extensions/<ext-name>/extension.json`

It can be used to write your own extensions like:
 - Reminder or to-do list https://github.com/slgobinath/SafeEyes/issues/101
 - Battery status indicator
 - Lock the screen https://github.com/slgobinath/SafeEyes/issues/102
 - Whatever you need

If you have anything to add, please do let me know.

**Comment by ruXlab** [comment]
Are you planning to add some kind of installer for it? To make installation process easier for end user

**Comment by slgobinath** [comment]
Until your suggestion, I had no such an idea. But +1 for your opinion and will think about it later.

**Comment by luizcarvalho** [comment]
Any example of a plugin ?

**Comment by slgobinath** [comment]
@luizcarvalho,
You can find how to create a to-do plugin at http://slgobinath.github.io/SafeEyes/.
Go to the customize section and click on Plugins

**Comment by luizcarvalho** [comment]
Nice @slgobinath . Very thanks!
