### ISSUE TITLE
Very small font on Ubuntu 17.04

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#105]
Dear all, 

Can someone reproduce the problem that the font for the break messages appears to be a lot smaller than it used to be?

I will try to catch a screenshot. 

Yours,

Robert

**Comment by orschiro** [comment]
I have a screenshot. However, it might not look smaller than it used to be...

![image](https://cloud.githubusercontent.com/assets/170947/24618406/3d9d6996-1897-11e7-9227-f191a437a8cd.png)

**Comment by slgobinath** [comment]
Hi,
 I think it is mostly related to the screen resolution. However, I have updated the font size in the last commit https://github.com/slgobinath/SafeEyes/commit/a8f2ad4a6b8cd5ee11de04f8792801eefb669d93#diff-23a0a70d55424fd7f0a8a165abc48334. Please try the updated values in `~/.config/safeyes/styles/safeeyes.css`

**Comment by orschiro** [comment]
Thank you! Let me try those and I will get back to you after some testing. :-)

**Comment by orschiro** [comment]
Font restored. 

Thank you! :-)

Should I revert this manual change once you publish the next version?

Yours,

Robert

**Comment by slgobinath** [comment]
You are welcome :-)
No need. The entire `config/safeeyes` directory will be replaced ;-)

**Comment by orschiro** [comment]
Great, thanks! :-)
