### ISSUE TITLE
not working in linux mint 17.3

### ISSUE THREAD

**Issue by muralikodali** [slgobinath/SafeEyes#11]
Indicator is showing up in bottom panel and giving notification before 10 seconds as set in the configuration.After that it is not blocking the screen or doing any thing else.

**Comment by slgobinath** [comment]
Hi,
Thanks for reporting the issue. I believe you are using the latest Safe Eyes version(1.0.8). Could you please open the Settings dialog and let me know whether you can open it or not.

**Comment by muralikodali** [comment]
Hi @slgobinath ,
After updating to latest version as suggested by you, it is working well in my linux mint.
Thanks for your response.

**Comment by slgobinath** [comment]
Duplicate of https://github.com/slgobinath/SafeEyes/issues/8
