### ISSUE TITLE
Looking for screensaver command to lock screen in your os

### ISSUE THREAD

**Issue by slgobinath** [slgobinath/SafeEyes#111]
One of the new feature added to Safe Eyes is [locking the screen after long breaks](https://github.com/slgobinath/SafeEyes/issues/102). This feature requires platform-specific external command-line tools to lock the screen.
For example, in `gnome-screensaver-command --lock` is used in Gnome.
Currently, Safe Eyes supports only Gnome, Unity and Cinnamon and I need your help to find out a reliable technique to identify your desktop environment and the screensaver command.

Please show your support by providing the output of following commands along with the operating system, desktop environment, and the **default** screensaver command (Please stick to the default screen saver). If someone already added the information about your system, just +1 the existing comment.

```
echo $DESKTOP_SESSION
echo $GNOME_DESKTOP_SESSION_ID
echo $KDE_FULL_SESSION
```

This is what I have found:

Linux Mint 18.1:
- Desktop Environment: `Cinnamon`
- Command to lock screen: `cinnamon-screensaver-command --lock`
- DESKTOP_SESSION: `cinnamon`
- GNOME_DESKTOP_SESSION_ID: `this-is-deprecated`
- KDE_FULL_SESSION: N/A

Manjaro:
- Desktop Envinroment: `KDE Plasma 5.9.2`
- Command to lock screen: `qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock`
- DESKTOP_SESSION: `/usr/share/xsessions/plasma`
- GNOME_DESKTOP_SESSION_ID: N/A
- KDE_FULL_SESSION: `true`

Xubuntu:
- Desktop Envinroment: `XFCE`
- Command to lock screen: `xflock4`
- DESKTOP_SESSION: `Xubuntu`
- GNOME_DESKTOP_SESSION_ID: N/A
- KDE_FULL_SESSION: N/A

Thanks

**Comment by Gabriel-p** [comment]
elementary OS Loki:

echo $DESKTOP_SESSION
`pantheon`
echo $GNOME_DESKTOP_SESSION_ID
`this-is-deprecated`
echo $KDE_FULL_SESSION
N/A
