### ISSUE TITLE
Starting over trainings

### ISSUE THREAD

**Issue by WhySoSeriousMORI** [slgobinath/SafeEyes#112]
If app could save last done trainings and cancel them for being popped for later use, I think this would be better.
This semi-issue specially happens when we have a lot of shut downs or restarts due to other works or system updates.
tnanks, Mori.

**Comment by slgobinath** [comment]
Added to Safe Eyes 2.0.0 with the commit https://github.com/slgobinath/SafeEyes/commit/3d86788f871f805714700b288bc7a96678820b76.
I leave this issue open until I merge the 2.0.0 branch with master.

**Comment by slgobinath** [comment]
Released in Safe Eyes 2.0.0
