### ISSUE TITLE
Breaks not triggered in XFCE4

### ISSUE THREAD

**Issue by Danesprite** [slgobinath/SafeEyes#114]
I noticed breaks weren't being shown for me and that the time shown for the next break on the panel icon wasn't changing either. The problem appears to be related to my recent switch to XFCE4; it works perfectly on Cinnamon. This was the output I got when running `safeeyes` in a terminal and waiting for a break:
```Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/safeeyes/SafeEyesCore.py", line 192, in __show_notification
    self.show_notification()
  File "./safeeyes", line 68, in show_notification
    notification.show(config['pre_break_warning_time'])
  File "/opt/safeeyes/Notification.py", line 51, in show
    self.notification.show()
Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
```
Any ideas? I've tried installing libnotify packages with no effect. Is it me not having something else installed or is this a bug?

**Comment by slgobinath** [comment]
Hi,

I haven't test Safe Eyes on XFCE yet. Based on my Google search two possible reasons are there.
1. Missing `libnotify-cil-dev`
Please try this command and check the result:
```
sudo apt-get install libnotify-cil-dev
```
2. Missing notification daemon
Try to install `xfce4-notifyd`

Please do let me know whether it fixes your problem or not. If not, let me know your operating system so that I can try my best to reproduce this issue.

**Comment by slgobinath** [comment]
I have tested Safe Eyes on Xubuntu 16.10 and couldn't reproduce this bug.

**Comment by slgobinath** [comment]
Anyhow, I have added the fix to ignore the errors related to g-dbus notification which is not related to Safe Eyes but to XFCE notification daemon. If none of the suggested solutions work for you, replace the `/opt/safeeyes/Notification.py' by [Notification.py](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/Notification.py)

**Comment by Danesprite** [comment]
Hi,
Installing `xfce4-notifyd` did the trick. I think I must've just missed that package when installing Xfce4. Thanks for the help! :+1:

**Comment by slgobinath** [comment]
You're welcome :-)
