### ISSUE TITLE
Q: Rolling eyes break

### ISSUE THREAD

**Issue by goldylucks** [slgobinath/SafeEyes#115]
Roll them once as far as possible and keep 'em there?
Or "roll and release" during the break?

**Comment by slgobinath** [comment]
Hi,
Sorry I couldn't catch the point. Is it something to improve the meaning of existing `Roll your eyes` exercise or a new exercise?

**Comment by goldylucks** [comment]
Improve the meaning for the existing exercise

**Comment by slgobinath** [comment]
Do you think changing it to `Roll your eyes left to right and vice versa` make sense? or please suggest me propper term which gives that meaning.

Thanks

**Comment by goldylucks** [comment]
depending on what you suggest we do in the break, one of the following would be more accurate IMO:
1. Roll your eyes a few times to each side
2. Roll your eyes once for each side

Thoughts?

**Comment by slgobinath** [comment]
Resolved with https://github.com/slgobinath/SafeEyes/commit/cca711a449e397add2e0241bf0137dd113293efa#diff-4eee0a9839e3364977cb81ef94d29e82R8
