### ISSUE TITLE
Not showing break screen

### ISSUE THREAD

**Issue by matrixik** [slgobinath/SafeEyes#117]
Hi, thank you for great tool.

I have some problems with Safe Eyes.
I can see system notification but it's not showing break screen.

Version 1.2.0.a7 (it was working previously without problems but not sure if 1.2 break it)
Ubuntu 16.04 and Linux Mint 18.1

In logs:
```
Apr 18 10:33:32 zybortd-dev gnome-session[2595]: Traceback (most recent call last):
Apr 18 10:33:32 zybortd-dev gnome-session[2595]:   File "/opt/safeeyes/BreakScreen.py", line 90, in <lambda>
Apr 18 10:33:32 zybortd-dev gnome-session[2595]:   File "/opt/safeeyes/BreakScreen.py", line 122, in __show_break_screen
Apr 18 10:33:32 zybortd-dev gnome-session[2595]: GLib.Error: g-file-error-quark: Failed to open file '/opt/safeeyes/glade/break_screen.glade': No such file or directory (4)
```

When trying to open about dialog:
```
Apr 18 10:37:04 zybortd-dev gnome-session[2595]:   File "/opt/safeeyes/TrayIcon.py", line 167, in show_about
Apr 18 10:37:04 zybortd-dev gnome-session[2595]:   File "/opt/safeeyes/safeeyes", line 61, in show_about
Apr 18 10:37:04 zybortd-dev gnome-session[2595]:   File "/opt/safeeyes/AboutDialog.py", line 35, in __init__ 
Apr 18 10:37:04 zybortd-dev gnome-session[2595]: GLib.Error: g-file-error-quark: Failed to open file '/opt/safeeyes/glade/about_dialog.glade': No such file or directory (4)
```

Looks like `/opt/safeeyes` does not exist at all.

But it's working when I kill Safe Eyes and start it again from command line or menu.
It's possible that problem is with autostarting with system.

**Comment by slgobinath** [comment]
Hi,
According to the error log, safeeyes is trying to open the GUI files from `/opt/safeeyes` but the location is moved to Python standard packages directory from 1.2.

Could you please provide more information to track this issue?

1. How did you upgrade the Safe Eyes?
2. Do you still have `/opt/safeeyes` directory?

Anyhow you can fix this by following these steps:
1. Delete the safeeyes folder in config
```
rm -r ~/.config/safeeyes
```

2. Remove the startup file
```
rm ~/.config/autostart/safeeyes.desktop
```

3. Restart Safe Eyes either from menu or command line

**Comment by matrixik** [comment]
OK, looks like I too rarely restart my computer.
I updated it from ppa, when updated in system without restarting it started to show this error, probably because `/opt/safeeyes` was removed by package and still old version of Safe Eyes was running.
Working now.

I spotted problem with 1.2 when break screen is showing only on one monitor (I have two) or on both if I have my mouse pointer on the second monitor but that probably separate issue.

Thank you for help and sorry for bothering.

**Comment by slgobinath** [comment]
Thanks and no worries.
I will test the new issue with multi monitors.

**Comment by slgobinath** [comment]
Multi-monitor issue is fixed with https://github.com/slgobinath/SafeEyes/commit/919dbb234fcb49d3d414ea3962ddb6bbe44936a0

**Comment by matrixik** [comment]
I can confirm that multi-monitor setup is working now with update to 1.2.0a9.
Thank you.
