### ISSUE TITLE
[1.2.0a8] Crash "KeyError: 'plugins'" when upgrading from 1.1.x

### ISSUE THREAD

**Issue by hartwork** [slgobinath/SafeEyes#120]
I ran into this crash with 1.2.0a8:
```
# safeeyes 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/safeeyes", line 11, in <module>
    load_entry_point('safeeyes==1.2.0a8', 'console_scripts', 'safeeyes')()
  File "/usr/lib64/python3.4/site-packages/safeeyes/__main__.py", line 318, in main
    plugins = Plugins(config)
  File "/usr/lib64/python3.4/site-packages/safeeyes/Plugins.py", line 40, in __init__
    for plugin in config['plugins']:
KeyError: 'plugins'
```
Is that something only I am going to run into? I used `mv ~/.config/safeeyes/safeeyes.json{,_OLD}` to workaround the issue for myself.

Best, Sebastian

**Comment by slgobinath** [comment]
Hi @hartwork,
The old config file must be replaced by the new version by comparing the `config_version`.
Could you please let me know the `config_version` in the old `safeeyes.json`.
```
"meta": {
        "config_version": 4
}
```
For Safe Eyes 1.1.8, it should be 3.

**Comment by ruXlab** [comment]
@slgobinath is it better to have default values instead if key wasn't found? What do you think?

**Comment by slgobinath** [comment]
@ruXlab you are right.
I am thinking of providing a better solution to merge the config file. Will add soon.

**Comment by ruXlab** [comment]
Let me know if I can help you :)

**Comment by hartwork** [comment]
Looks like I had version 4 in, already:
```
# fgrep config_version ~/.config/safeeyes/safeeyes.json_OLD 
        "config_version": 4
```

**Comment by slgobinath** [comment]
That's the issue. I guess for some testing purposes you already executed Safe Eyes version somewhat between 1.8 and 1.2 ;-)
