### ISSUE TITLE
Multiscreen bug in 1.2.0a7

### ISSUE THREAD

**Issue by ruXlab** [slgobinath/SafeEyes#121]
Ubuntu 17.04, installation from ppa

Not sure was it because of 17.04 or internal changes but now only one screen is grayed, second screen remains active(unblocked)

**Comment by slgobinath** [comment]
Hi,
This bug is already fixed in https://github.com/slgobinath/SafeEyes/commit/919dbb234fcb49d3d414ea3962ddb6bbe44936a0
