### ISSUE TITLE
Break overlay buttons

### ISSUE THREAD

**Issue by Joe5** [slgobinath/SafeEyes#124]
The buttons should be much less noticeable. They should not call your attention to click them. Giving them 0.1 or less opacity should be enough. They can have full opacity on hover / focus.

**Comment by slgobinath** [comment]
Hi,
You can achieve this by customizing the CSS style of the break screen. Follow these steps:

1. Open the `safeeyes_style.css` file
```
gedit ~/.config/safeeyes/style/safeeyes_style.css
```
2. Add the opactity values to `btn_skip`, `.btn_skip:hover`, `.btn_postpone` and `.btn_postpone:hover`
```
...
.btn_skip {
    ...
    opacity: 0.1;
}

.btn_skip:hover {
   ...
    opacity: 0.9;
}

.btn_postpone{
    ...
    opacity: 0.1;
}

.btn_postpone:hover {
   ...
    opacity: 0.9;
}
...
```
If you don't need the skip/postpone buttons at all, enable the strict break mode in Settings.

**Comment by Joe5** [comment]
Thanks for the explanation, I know some CSS so I already did that for my local installation. Just wanted to share my idea. I don't want to disable them all together because sometimes I just might be forced to skip/interrupt the break depending on my work situation.
