### ISSUE TITLE
Custom config

### ISSUE THREAD

**Issue by Joe5** [slgobinath/SafeEyes#125]
After upgrading my local application I lost my config (it got overwritten). Would it be possible to have core config inside application installation and than user config to overwrite some of this settings?

**Comment by slgobinath** [comment]
I have already considered this problem. Will fix it in next version. (Not in 1.2.0 as there are already more changes to include)

**Comment by slgobinath** [comment]
Fixed in https://github.com/slgobinath/SafeEyes/commit/252d5fa9e8d033629d372f7d05a9177d41bc2aaf. So you can see this in 1.2.0
