### ISSUE TITLE
Not showing blank screen on both windows

### ISSUE THREAD

**Issue by imaravin** [slgobinath/SafeEyes#129]
When I connected my laptop to monitor 
Safe Eyes shows blank screen on single window, not both

**Comment by slgobinath** [comment]
Hi,
Could you please share your Safe Eyes version? This problem was identified in Safe Eyes 1.2.0a7 and fixed in the latest release.

**Comment by imaravin** [comment]
I'm using Safe Eyes 1.2.0a7

**Comment by slgobinath** [comment]
Please upgrade to the latest version 1.2.0a10 (Released yesterday)
