### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by adamos42** [slgobinath/SafeEyes#13]
I would like to add multiple languages to this program, but far as I can see only way to do it to change the json file in config. Please make support for the languages :+1:

**Comment by slgobinath** [comment]
I also planned to add support for multiple languages. I will add this feature soon.

**Comment by slgobinath** [comment]
Included in release [v1.1.0](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.0). See [how to translate](https://github.com/slgobinath/SafeEyes#translating-safe-eyes).

**Comment by wilfried18** [comment]
I translated the file en.json into fr.json but then how to make the software in French because in the "safeeyes.json" there is nothing concerning the language
thank you
code
`{
    "break_interval": 15, 
    "long_break_duration": 60, 
    "long_break_messages": [
        "Walk for a while", 
        "Lean back at your seat and relax"
    ], 
    "no_of_short_breaks_per_long_break": 5, 
    "pre_break_warning_time": 10, 
    "short_break_duration": 15, 
    "short_break_messages": [
        "Tightly close your eyes", 
        "Roll your eyes", 
        "Rotate your eyes", 
        "Blink your eyes", 
        "Have some water"
    ], 
    "skip_button_text": "Skip", 
    "strict_break": false
}`

**Comment by slgobinath** [comment]
Hi,
If there is no option, please update your Safe Eyes to the latest version. You can define the language at [safeeyes.json_language](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/safeeyes/config/safeeyes.json#L11)

**Comment by wilfried18** [comment]
I use the version available on AUR. ....

**Comment by slgobinath** [comment]
The AUR version is 1.0.9 but the translation was introduced in 1.1.0. I do not have access to AUR so could you please install using the updated version in [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=safeeyes#n3).
