### ISSUE TITLE
make sound (portaudio) optional

### ISSUE THREAD

**Issue by blshkv** [slgobinath/SafeEyes#135]
could you make pyaudio optional or add alsa support?

I dont' have portaudio in my system (alsa only) and it would be good to have it optional

**Comment by orschiro** [comment]
Do you actually mean Pulseaudio?

**Comment by blshkv** [comment]
hm.. I confused it with pulseaudio, but it is portaudio in reality. See PyAudio-0.2.8/setup.py:
```
external_libraries = ['portaudio']
```
http://www.portaudio.com/

**Comment by blshkv** [comment]
portaudio is really small and works with alsa. Feel free to close this issue if making it optional is too troublesome

**Comment by orschiro** [comment]
Why can't you install the pulseaudio package?

I mean you don't have to use it, right?

But then you would fulfil the dependency requirement of Safe Eyes.

**Comment by blshkv** [comment]
I was just hoping to able to choose a backend audio engine or disable it completely if I'm  not going to use it. The sound setting is even disabled by default in safe eyes so it would make sense to have an option not to install it.

**Comment by orschiro** [comment]
How do you install Safe Eyes?

**Comment by blshkv** [comment]
I use Gentoo and its packet manager with its own python installer, here is the standard ebuild:
https://packages.gentoo.org/packages/x11-misc/safeeyes
This ebuild pulls
https://packages.gentoo.org/packages/dev-python/pyaudio
which pulls portaudio

What is the reason of your question?

**Comment by blshkv** [comment]
Ok, there is the official way
https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

**Comment by orschiro** [comment]
Just wondering because I am on Ubuntu

and never thought of these dependencies. 

Thanks for explaining!

**Comment by blshkv** [comment]
ah, ok. Ubuntu comes with precompiled packages and you have to go with whatever provided.
Gentoo gives you more options and you can disable/enable certain functions (such as available via ./configure --with-XXX). So portaudio, for example, supports ```alsa```, ```jack``` and ```oss``` flags.

Similarly, you could make pyaudio package optional via ```audio``` (as an example) flag:
```
    extras_require={
        'audio':  ["pyaudio"],
    }
```
Obviously, you will also need to modify Utility.py and catch an exception if pyaudio is not available during import. It would be also good to have a friendly message in GUI if user tries to enable sound notifications without the required library.

**Comment by orschiro** [comment]
> It would be also good to have a friendly message in GUI if user tries to enable sound notifications without the required library.

Aren't people who compile from source

generally aware of these potential problems?

**Comment by blshkv** [comment]
They might compiled it years ago. Just set a flag during the load in case of unable to find pyaudio and notify a user if he decided to activate sound

**Comment by blshkv** [comment]
Btw, they don't really compile. They run a Gentoo package manager and it does all job. So they don't even need to know how to compile

**Comment by slgobinath** [comment]
Hi,
I will make it optional. Similar issue I faced with `xprintidle` in Fedora 25 and made `xprintidle` optional (Not in Ubuntu deb but Safe Eyes can run without xprintidle).

**Comment by slgobinath** [comment]
`pyaudio` is made optional with https://github.com/slgobinath/SafeEyes/commit/08932e5fff0c867a5b9d034781c38666648cbd22. From next version onwards, `sudo pip3 install safeeyes` will not check `pyaudio` as a dependency.
To install `pyaudio` as a dependency, use the following command:
```
sudo pip3 install safeeyes[audible_alert]
```

**Comment by blshkv** [comment]
Perfect! Thank you!

**Comment by radek-sprta** [comment]
When pyaudio is not installed, the audible alerts setting is just unclickable, without giving the user any hint of what they should do. How about showing an informative popup telling them to install pyaudio instead?
See #165

**Comment by slgobinath** [comment]
Thank you @radek-sprta.
I planned to add this feature to the new Settings dialog which is under development. Now I can reuse your code ^_^

Thanks again.

**Comment by radek-sprta** [comment]
Sorry about the bugs in the commit!
I sent a pull request for the wrong branch, since my development environment was super messy, with a lot of branches etc. I've cleaned it up now, so it shouldn't happen again!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by slgobinath** [comment]
@radek-sprta no worries. I can manage those minor issues.
Thanks for your support :)
