### ISSUE TITLE
Install SafeEyes manually (no package repository)

### ISSUE THREAD

**Issue by eldariont** [slgobinath/SafeEyes#137]
Hi,

how can I install SafeEyes on a Linux that doesn't come with a package repository? Which dependencies do I need to install and how?

Cheers
David

**Comment by slgobinath** [comment]
Hi,

May I know your operating system? Installing the following dependencies must work:

Install if available:
 - `gir1.2-appindicator3-0.1` (Mostly in Debian based it should be available)
 -  `gir1.2-notify-0.7` (Mostly in Debian based it should be available)
 - `libappindicator-gtk3`

Must to have dependencies:
 - `python3-pyaudio`
 - `python3-psutil`

Optional dependency:
 - `xprintidle`

Install Safe Eyes from PyPI:
```
sudo pip3 install safeyes
```

Update the icon cache/restart the operating system

Start Safe Eyes from the menu/launcher

**Comment by eldariont** [comment]
Thanks for the super quick reply!

I'm on a custom-made Linux distribution (no Debian, Fedora, ..) that uses the Xfce desktop environment. So I guess that it's hard or impossible to get Safe Eyes running..

**Comment by slgobinath** [comment]
Ohh. If python3 is available, I hope you can install the Python modules. Other than that you need to have GTk 3 support and App indicator support for tray icon and notifications.

**Comment by orschiro** [comment]
@slgobinath referencing https://github.com/slgobinath/SafeEyes/pull/138. 

What do you think?

**Comment by slgobinath** [comment]
@orschiro thanks for the PR. I have merged it.
I am closing this issue because the operating system is not a standard one and it is hard to find out the exact dependencies for the specific OS.
