### ISSUE TITLE
Add user's arbitrary exercises 

### ISSUE THREAD

**Issue by Akronix** [slgobinath/SafeEyes#142]
I'd be nice to have an user-friendly easy way to add personal exercises.
I imagine just a pop-up dialog asking for title, description and an optional picture.

**Comment by slgobinath** [comment]
Hi @Akronix,
+1 for your suggestion. The settings dialog becomes messier and I am planning to redesign it with tabs or similar UI component. I will include it when I change the settings dialog.

**Comment by slgobinath** [comment]
Implemented in Safe Eyes 2.0.0
