### ISSUE TITLE
Make short breaks optional

### ISSUE THREAD

**Issue by dbogdanov** [slgobinath/SafeEyes#154]
This is a feature request to make short breaks optional. Also, it will be beneficial to have breaks longer than 120 seconds (e.g., 5 minutes).

**Comment by slgobinath** [comment]
Hi @dbogdanov,
I agree with increasing break time longer than 120 seconds and include it in the next release. But making short breaks optional require some design level changes and I wonder whether it is worth to do that.

What do you think if users can increase the short break time equal to long break time and the time between 2 breaks to 45 minutes (or more)? Then technically there will not be any differences between short & long breaks. Also, you can change the exercise name using the configuration.

**Comment by dbogdanov** [comment]
Yes, this will work fine as a workaround. Also, may be allowing 0 seconds time for short breaks will work?

**Comment by slgobinath** [comment]
Implemented in Safe Eyes 2.0.0 with https://github.com/slgobinath/SafeEyes/commit/e4bae4807dcdf5ea67a2c41bc6c1404ffabddb85 and https://github.com/slgobinath/SafeEyes/commit/5d5daa1be6f1dc3faee62ae180691d842d181d52.

In Safe Eyes 2.0.0, you can delete all the short breaks or all the long breaks.

I leave this issue open until I release Safe Eyes 2.0.0

**Comment by slgobinath** [comment]
Released in Safe Eyes 2.0.0
