### ISSUE TITLE
Real-life consequences

### ISSUE THREAD

**Issue by grandchild** [slgobinath/SafeEyes#156]
I have been running SafeEyes on my work computer for a few weeks. It's a great little utility. But time is scarce, and optimizing as we all are, I eventually tried to do as many exercises at once as I could.

So now, after watching me walking on the spot in front of the window staring at a distant chimney, eyes blinking and rolling fast from side to side while frantically trying to gulp down as much water as possible from my bottle within 15 seconds, my colleagues finally decided I have gone stark raving mad. They outright rejected my prompt and feverish explanations that this was for "health reasons" and have now institutionalized me.

I am writing this from the the only computer here, which runs windows and has a terribly flickering CRT, and I fear for my eyes. I am clearly NOT insane!

Any ideas for a fix?

**Comment by orschiro** [comment]
> and have now institutionalized me.

What do you mean by that?

**Comment by slgobinath** [comment]
Sometimes I also face this. But what kind of solutions do you expect? We can't modify this tool (or develop a new software) to change the human attitude right ;-)

**Comment by slgobinath** [comment]
Closing this issue as no possible technical solutions.
