### ISSUE TITLE
Show time until next break

### ISSUE THREAD

**Issue by Gabriel-p** [slgobinath/SafeEyes#16]
Nice app, I just started using it in elementary OS Freya (64 bit).

It would be nice to see how long it takes until the next break, and a description of what break it will be (short, long, exercise, etc)

It could be located below `Quit` in the icon's pop-up perhaps?

**Comment by Gabriel-p** [comment]
Some questions about the app:

1. What does `Interval between two breaks` mean? Is this the time interval between two *long* breaks?
2. How does `Number of short breaks between two long breaks` work precisely? If I set the above to 15 min, and this one to 4 min, what will happen? Will I get two short breaks, one 4 min after the first long break and the next after 8 min? And then I'll get a long break at the 15 min mark?
3. Is there a log file anywhere?

**Comment by slgobinath** [comment]
I will include your suggestion in later versions.

1. Interval between two breaks is the time between any two breaks (They can be either short/long).

2. Long breaks are not determined by time instead they are determined by number of short breaks taken. For example if you need a short break every 15 minutes and a long break every hour, set `Interval between two breaks' to 15 and `Number of short breaks between two long breaks` to 3.
If you start at 10.00, you will get 3 short breaks at 10.15, 10.30 & 10.45 respectively and a long break at 11.00.

3. Sorry there is no log right now.

**Comment by Gabriel-p** [comment]
Thank you for clarifying that. Perhaps some details in a `Help` menu or somewhere would be nice.

**Comment by slgobinath** [comment]
Added info to the menu about next break time with https://github.com/slgobinath/SafeEyes/commit/223d4b029c2b4f8464ec06337a9f97fb50a2216c. The exercise name and break type are purposely not included in the info to maintain the minimum menu width.
This feature will be included in the next release after further developer testing.

**Comment by slgobinath** [comment]
Included in release [v1.1.0](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.0)
