### ISSUE TITLE
Safeeyes.desktop Slovenský and Magyar translation required

### ISSUE THREAD

**Issue by slgobinath** [slgobinath/SafeEyes#161]
Need to translate the following two lines in `safeeyes.desktop`.
 - [Comment[hu]=Protect your eyes from eye strain](https://github.com/slgobinath/SafeEyes/blob/master/share/applications/safeeyes.desktop#L12)
 - [Comment[sk]=Protect your eyes from eye strain](https://github.com/slgobinath/SafeEyes/blob/master/share/applications/safeeyes.desktop#L18)

@radek-sprta I guess you can help on this :-)

**Comment by radek-sprta** [comment]
Done! #162

**Comment by slgobinath** [comment]
@radek-sprta thank you very much :-).

Now Hungarian translation is pending.
```
Comment[hu]=Protect your eyes from eye strain
```
