### ISSUE TITLE
Locale not supported by C libraby;Using the fallback 'C' locale

### ISSUE THREAD

**Issue by mrhieu059** [slgobinath/SafeEyes#164]
(safeeyes:26742): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 11, in <module>
    load_entry_point('safeeyes==1.2.1', 'console_scripts', 'safeeyes')()
  File "/usr/lib/python3.6/site-packages/safeeyes/__main__.py", line 249, in main
    language = Utility.load_language(config['language'])
  File "/usr/lib/python3.6/site-packages/safeeyes/Utility.py", line 224, in load_language
    lang_code = parse_language_code(lang_code)
  File "/usr/lib/python3.6/site-packages/safeeyes/Utility.py", line 206, in parse_language_code
    system_locale = __system_locale()
  File "/usr/lib/python3.6/site-packages/safeeyes/Utility.py", line 166, in __system_locale
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

How to fix it?

**Comment by slgobinath** [comment]
Hi @mrhieu059,
Please execute the following command in your terminal and share the output.
```
locale
```
Also, follow these steps and let me know the result.
1. Export `LC_ALL`
```
export LC_ALL=C
```

2. Start Safe Eyes from the same terminal
```
safeeyes
```

**Comment by gihaires24** [comment]
Bonsoir la famille. après avoir éssayer plusieurs  méthode trouver sa et là sur le web, une idée simple m'est venu en exprit... C'est celle de devoir, choisir un autre pays occidentale qui s'exprime avec la mèmè langue . je l'ai fait en modifiant les la region dans :" configuration system->paramettres regionaux->regions. pour m'a part j'ai prie "france"

pour info, je travail sur Debian8

**Comment by slgobinath** [comment]
Since there is no more update and this issue was reported for an older version, I close this issue. If you still have the issue with Safe Eyes 2.0.0, please reopen it.

Thanks
