### ISSUE TITLE
missing `~/.config/safeyes`

### ISSUE THREAD

**Issue by goldylucks** [slgobinath/SafeEyes#166]
I don't have it on my machine, running
```bash
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

I want to [customize the exercises](http://slgobinath.github.io/SafeEyes/#custom-exercise)

**Comment by slgobinath** [comment]
Hi,
It's a strange issue! Does safeeyes work in your system as expected?
Could you please follow these steps and let me know the results.
1. Create a folder safeeyes in .config
```
mkdir -p ~.config/safeeyes/style
```

2. Ensure that the user has write permission to those directories

3. Start the safeeyes and check the directories for config, log and css style files.

**Comment by goldylucks** [comment]
1. Except the missing folder, so far it has worked flawlessly
2. After following the 3 steps u mentioned, [the 3 files were indeed created](https://gist.github.com/goldylucks/43856e9d5e2380c912e2da1b1cd17fbc).
3. not it gets even stranger ... if i make a change in `safeeyes.json` and then change something through safeeyes gui, it wipes my changes! The file is back to how it was, like I posted in the [gist](https://gist.github.com/goldylucks/43856e9d5e2380c912e2da1b1cd17fbc).

**Comment by slgobinath** [comment]
The changes done through GUI are intended to replace only the options available in GUI. Does it replace even the changes you have done through GUI after every restart?

**Comment by goldylucks** [comment]
if I do a change in the GUI, the json file is "re-started."

now I've changed the json to what u c below and the app doesn't not load. resetting to default json makes it work.

```json
{
    "active_window_class": {
        "skip_break": [],
        "take_break": []
    },
    "audible_alert": true,
    "break_interval": 1,
    "disable_options": [
        {
            "label": "for_x_minutes",
            "time": 30,
            "unit": "minute"
        },
        {
            "label": "for_x_hour",
            "time": 1,
            "unit": "hour"
        },
        {
            "label": "for_x_hours",
            "time": 2,
            "unit": "hour"
        },
        {
            "label": "for_x_hours",
            "time": 3,
            "unit": "hour"
        }
    ],
    "idle_time": 2,
    "language": "en",
    "long_break_duration": 60,
    "long_breaks": [
        {
            "name": "long_break_walk"
        },
        {
            "name": "long_break_lean_back"
        }
    ],
    "meta": {
        "config_version": 3
    },
    "no_of_short_breaks_per_long_break": 5,
    "pre_break_warning_time": 10,
    "short_break_duration": 15,
    "short_breaks": [
        {
            "name": "conscious_breath"
        },
        {
            "name": "pushups"
        }

    ],
    "custom_exercises": {
        "conscious_breath": "Take a conscious breath",
        "pushups": "Do ten push-ups"
    },
    "strict_break": false
}

```

**Comment by slgobinath** [comment]
Hi,
I think the problem is with the version of the config file. (You are using an older version) see `config_version`. I hope you are using the latest Safe Eyes (v1.2.1). Apart from the version of Safe Eyes, the config file has its own version which is increased whenever a new property is introduced to the configuration. So please try the following configuration:

```
{
    "meta": {
            "config_version": "5.0.1"
    },
    "allow_postpone": false,
    "break_interval": 15,
    "enable_screen_lock": false,
    "long_break_duration": 60,
    "no_of_short_breaks_per_long_break": 5,
    "pre_break_warning_time": 10,
    "short_break_duration": 15,
    "idle_time": 5,
    "postpone_duration": 5,
    "show_time_in_tray": false,
    "strict_break": false,
    "audible_alert": false,
    "language": "system",
    "time_to_screen_lock": 5,
    "lock_screen_command": [],
    "active_window_class": {
        "skip_break": [],
        "take_break": []
    },
    "disable_options": [
        {
            "label": "for_x_minutes",
            "time": 30,
            "unit": "minute"
        },
        {
            "label": "for_x_hour",
            "time": 1,
            "unit": "hour"
        },
        {
            "label": "for_x_hours",
            "time": 2,
            "unit": "hour"
        },
        {
            "label": "for_x_hours",
            "time": 3,
            "unit": "hour"
        }
    ],
    "short_breaks": [
        {
            "name": "conscious_breath"
        },
        {
            "name": "pushups"
        }
    ],
    "long_breaks": [
        {
            "name": "long_break_walk"
        },
        {
            "name": "long_break_lean_back"
        }
    ],
    "custom_exercises": {
    	"conscious_breath": "Take a conscious breath",
        "pushups": "Do ten push-ups"
    },
    "plugins": []
}
```

**Comment by goldylucks** [comment]
Awesome!
Thanks for the help my friend. U rock! :)

Now where's your BTC donation Address ;)

**Comment by slgobinath** [comment]
It's my pleasure to help you.
I develop and maintain this project as one of my hobby projects. If you really like to donate, please donate to any other open source projects those are in need :-)

Have a nice day :-)
