### ISSUE TITLE
Miscalculation of break times

### ISSUE THREAD

**Issue by nomadwannabe** [slgobinath/SafeEyes#170]
I'm using ubuntu 14.04 and SafeEyes 1.2.1. I made some minor changes in durations and now SafeEyes doesn't act as it should. Sometimes it wouldn't give any break at all. For example now it's 09:42 and it says "next break 09:01". That is a bug, but my coder instincts say that it may require a change of algorithm altogether for calculating the breaks.

**Comment by slgobinath** [comment]
Thanks for reporting the bug. Could you please share the log file so that I can find out the exact reason for such behavior.
The log file is available at `~/.config/safeeyes/safeeyes.log`

**Comment by svepe** [comment]
I observed the behaviour when no new break time is estimated. When this bug ocurrs the last line in the log file is "Playing audible alert". The only way I figured out how to recalculate a new break (without restarting the app) is by idling. Here is the relevant log file section (note the logging times):

```
2017-09-13 14:12:12,373 [INFO]:[Thread-4] Playing audible alert                
2017-09-13 14:25:08,895 [INFO]:[Thread-2] Pause Safe Eyes due to system idle   
2017-09-13 14:26:23,565 [INFO]:[Thread-2] Resume Safe Eyes due to user activity
2017-09-13 14:26:23,566 [INFO]:[Thread-6] Update next break information        
2017-09-13 14:26:23,567 [INFO]:[Thread-6] Pre-break waiting for 15 minutes     
```

I think this might be an issue with pyaudio and may be related to #187.

**Comment by slgobinath** [comment]
Closing this issue with an assumption this won't happen in Safe Eyes 2.0.0 because we have moved to `aplay`.
If it happens again, please reopen this issue.

Thanks
