### ISSUE TITLE
reset break counter after suspend

### ISSUE THREAD

**Issue by klayman** [slgobinath/SafeEyes#174]
Currently safeeyes doesn't reset the short break counter after system suspend. I think, a short break should always come first after resuming (if system was suspended longer than the break interval).

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/8b2af970e09ebd96578ef95736a5287b68b570d6.

**Comment by klayman** [comment]
Thank you!
