### ISSUE TITLE
background non-transparent in Ubuntu MATE 16.04

### ISSUE THREAD

**Issue by ZekeSinner** [slgobinath/SafeEyes#18]
With last update (1.09 i think) safeeyes black background is not transparent at all (100% black). there is nothing in terminal, and i also havnt change any settings in files.

Its not any major issue, but i assume its not WAI.

**Comment by slgobinath** [comment]
Thank you for reporting this issue. It affects not only Ubuntu MATE but other distributions as well. The fix will be released in next release.

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/e3341e26c1a27a03800e55b759b6e2116e115319. The fix will be included in the next release.

**Comment by slgobinath** [comment]
Included in release [v1.1.0](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.0)
