### ISSUE TITLE
Doesn't work on Manjaro 

### ISSUE THREAD

**Issue by Warmuser** [slgobinath/SafeEyes#180]
After the installation with Pamac, I tried to open SafeEyes but it didn't start. I also tried to refresh the shell, but nothing..

My specs:
Manjaro 17.0.2
GNOME 3.24.2
kernel 4.9.40.1

**Comment by Warmuser** [comment]
Damn, it's worked unexpectedly.. xD I

**Comment by slgobinath** [comment]
No worries :-D
