### ISSUE TITLE
official debian package?

### ISSUE THREAD

**Issue by anarcat** [slgobinath/SafeEyes#183]
anyone working on uploading this into debian? would make a nice (modern) replacement for the (unmaintained?) workrave package.

as a debian developer, i'd be happy to accompany whoever wants to in the process here.

**Comment by slgobinath** [comment]
Hi,
So far I didn't consider Debian. I would appreciate it, if you could help us on this.

Thanks

**Comment by anarcat** [comment]
hi - i have opened [#876383](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876383) to followup on this on Debian's side.

**Comment by slgobinath** [comment]
Thank you very much.
Hope to see Safe Eyes on Debian repo.

**Comment by slgobinath** [comment]
Great to hear that :-)
Is it available now for Debian users?

**Comment by anarcat** [comment]
On 2017-10-02 12:31:03, Gobinath wrote:
> Great to hear that :-)
> Is it available now for Debian users?

no. NEW is the process by which new packages get accepted in debian. the
package needs to be reviewed by FTP-masters to see if it's suitable in
the archive. the process can take from days to months, depending on how
busy those people are and how complicated the package is.

**Comment by slgobinath** [comment]
Okay. Thanks for updating me :-)

**Comment by FedericoCeratto** [comment]
I'm happy to announce that SafeEyes is in Debian Unstable: https://packages.debian.org/sid/safeeyes

**Comment by anarcat** [comment]
well, looks like our work is done here, congrats everyone. :)

**Comment by slgobinath** [comment]
My sincere thanks to @anarcat and @FedericoCeratto.
Could you please let me know the detailed instructions to install Safe Eyes on Debian?

FYI: I have modified the official web page and have to update the Debian commands.

**Comment by FedericoCeratto** [comment]
For people running Unstable or Testing:
```
$ sudo apt-get install safeeyes
```

**Comment by slgobinath** [comment]
Thank you very much.
I have updated the README for the moment. Will update the website soon.
