### ISSUE TITLE
count keystrokes/mouse movement?

### ISSUE THREAD

**Issue by anarcat** [slgobinath/SafeEyes#184]
This is pretty cool software. I like the minimalist/configuration approach (and the fact that it is written in python!).

As a workrave user, one thing I am wondering is whether it will keep track of mouse movement and keystrokes counts the way workrave does. You can see the analysis I get out of this:

https://anarc.at/blog/2016-06-01-work-volume/

... which I find personally fascinating.

**Comment by anarcat** [comment]
some possible solutions:

* [this thread](https://unix.stackexchange.com/a/56224/30227) mentions tracking the Xinput extension and the input-events (needs root)
* [kbdcounter](https://github.com/forsberg/kbdcounter) counts keystrokes (in python)
* [pynput](https://pypi.python.org/pypi/pynput) is a clean Python interface for Xinput

**Comment by slgobinath** [comment]
Hi,
Now I am developing Safe Eyes 2.0.0 with complete plugin support. According to the new design, everything except the core features will be implemented as plugins. I guess we can include this feature as a plugin in future.

**Comment by slgobinath** [comment]
Hi @anarcat,
I saw your French translations in Weblate but I reset them by mistake when I pulled the new changes from GitHub. Could you please make those changes again.

Sorry for the inconvenience.

**Comment by anarcat** [comment]
@slgobinath i'm not sure i can do that. i don't exactly remember which changes I did and, for a reason i cannot explain, the changes do not show up in the weblate git repository either. sorry.

**Comment by slgobinath** [comment]
In case if it is useful, these are the changes you made:
```
Afficher la prochaine heure de pause dans la zone de notification
Langue du système
Afficher la prochaine pause dans la zone de notification
```

Sorry again for my mistake and I don't want to loose your contribution.
![screenshot from 2017-08-28 21-06-52](https://user-images.githubusercontent.com/4003168/29799921-16dfbc66-8c35-11e7-9c25-d52a86ef33a6.png)

**Comment by anarcat** [comment]
okay, done..

**Comment by anarcat** [comment]
i think we can consider this out of scope, now that I found [selfspy](https://github.com/gurgeh/selfspy/) through #144. :) thanks!
