### ISSUE TITLE
clarify preferences panel with columns and long-break specific timer

### ISSUE THREAD

**Issue by anarcat** [slgobinath/SafeEyes#190]
the safeeyes preferences are somewhat lacking compared to workrave. example:

![Workrave vs safeeyes](https://user-images.githubusercontent.com/796623/31093106-a216548e-a77e-11e7-9df5-06ca5b57e4cf.png)

Above, you can see the Workrave preferences window and below, safeeyes. The use of tabs is commendable, but the first tab is really hard to read. I'm not sure what's going on there, but it does seem like a reaaally long list that could be broken into columns or *something* to improve readability. Having hour/minute/seconds breakdowns would also improve the usability significantly.

But there's also a rather difficult configuration aspect in safeeyes: the correlation between short and long breaks. In workrave, both are configured independently. But to figure out how to configure the interval i want between *long* breaks in safeeyes, i need to multiple the number of short breaks period... It's really hard to figure that out. It would be much easier to just say "N minutes between long breaks" instead of "X short breaks between long breaks"...

so i think this could be a huge improvement to the usability of safe eyes, at the cost of a little work in glade. ;)

**Comment by slgobinath** [comment]
Hi @anarcat,
Your suggestions make sense and I will improve the GUI before releasing 2.0.0.

May I know how workrave handles clashing short and long breaks?
Suppose I set short breaks every 15 minutes and long breaks every 1 hour, what will I get after an hour? The fourth short break or the first long break?

I hope it should be long break.

Further, if I set short breaks every 14 minutes and long breaks every 57 minutes, will I get a long break(at 57th minute) after a 1-minute delay from fourth short break (at 56th minute)?

**Comment by anarcat** [comment]
i don't exactly know what it does: i would assume the long break as well.

i wouldn't worry about weird setups like 56ths vs 57th minute either: if the user configures something weird like that, they deserve what they're getting. :p

**Comment by slgobinath** [comment]
:-D
Those were the concerns I had when I developed Safe Eyes. Further I didn't wont to have two timers running in background. Anyhow I will change the way we handle long breaks now.

**Comment by anarcat** [comment]
On 2017-10-02 19:32:21, Gobinath wrote:
> :-D
> Those were the concerns I had when I developed Safe Eyes. Further I didn't wont to have two timers running in background. Anyhow I will change the way we handle long breaks now.

This is a case of implementation details leaking into the UI, in my
opinion. It should matter to the user if there are one timers or two:
they should be able to specify those delays in a way that doesn't
require them to make modulo-60 calculations. ;)

In other words: you do not need to add a new timer. You just need to set
the long break internal setting to "floor(long_break_timer_from_user /
short_break_time)" :)

**Comment by slgobinath** [comment]
:-) Makes sense.
I will fix it soon.

**Comment by slgobinath** [comment]
Hi,
I have changed the settings dialog as shown below. The `long break interval` can be defined only in multiples of `short break interval`. This way we can let users define the long break interval in time without further confusion.

I avoided splitting time units into `HH:MM:SS` format because:
1. It makes hard to define UI level constraints
2. UI becomes more complex
3. Some controls do not need all three. For example, time to prepare for a break do not need `Hour` and a break interval do not need `Second`. Having `HH:MM` in one place and `MM:SS` in another place will make the UI inconsistent.
Therefore I -1 that implementation.
WDYT?
![screenshot from 2017-10-04 12-26-56](https://user-images.githubusercontent.com/4003168/31187784-e7450982-a900-11e7-81a0-a3fb14b0ad0c.png)

**Comment by anarcat** [comment]
>I have changed the settings dialog as shown below. The long break interval can be defined only in multiples of short break interval. This way we can let users define the long break interval in time without further confusion.

Okay, that's fine, even if this may lead to more questions. A tooltip or some way to discover that logic may be useful...

> I avoided splitting time units into HH:MM:SS format because:
>
> 1. It makes hard to define UI level constraints
> 2. UI becomes more complex
> 3. Some controls do not need all three. For example, time to prepare for a break do not need Hour and a break interval do not need Second. Having HH:MM in one place and MM:SS in another place will make the UI inconsistent.
> Therefore I -1 that implementation.

Okay, makes sense. :)

> WDYT?

One more comment, if I may...

The "postpone duration (in minutes)" field could be grouped, or at least *after* the "allow postponing breaks" toggle. That way it would be clear they are related.

Thanks for doing this!

**Comment by slgobinath** [comment]
With the commit https://github.com/slgobinath/SafeEyes/commit/e04f463adf018506f3d9c9e6b02912a730bc0a7f, an info message will be shown when a user updates either the short break interval or the long break interval for the first time. If the user closes it, it will not appear again in that settings session.
![screenshot from 2017-10-04 19-31-31](https://user-images.githubusercontent.com/4003168/31204973-774ab71c-a93c-11e7-96c1-a750fc9f2235.png)

**Comment by anarcat** [comment]
excellent. i like the new ordering as well - thanks!
