### ISSUE TITLE
walking away from a break

### ISSUE THREAD

**Issue by anarcat** [slgobinath/SafeEyes#191]
i know that safeeyes can start the screensaver after a break is completed, and that's great. unfortunately, what actually happens here is that i walk away from the computer at the *beginning* of the break, which makes my workstation vulnerable to an attacker: they can just walk up to the keyboard and skip the break.

i would need a "lock" button which allows me to fire up the screen locking mechanism immediately when i start the break, would that make sense?

**Comment by slgobinath** [comment]
Hi,
This can be achieved by setting the `Maximum time to skip, bypassing the lock screen (in seconds)` to `0`.
This setting can be found under the properties of `Screensaver` plugin in Safe Eyes 2.0.0.

**Comment by anarcat** [comment]
that was definitely not obvious to me, but thanks for the pointer. :)

**Comment by Bolo92** [comment]
@slgobinath This solution has a disadvantage. When long break popup and you are in midlle of something you press the skip button and screen is locked.
Would be nice if:
a) will be exeception on the shorcut when safeeye display the break screen. Probably the most popular is [windows key](https://en.wikipedia.org/wiki/Windows_key) + L
b) additional button "screensaver" on the break screen.

The perfect solution is both, but this is your private time so you will choose ;)
