### ISSUE TITLE
setup.py clean compiles .po files

### ISSUE THREAD

**Issue by FedericoCeratto** [slgobinath/SafeEyes#196]
Running `python3.5 setup.py clean` unexpectedly generates 23 .po files by calling __compile_po_files().
(The `clean` command should only delete build artifacts.)

**Comment by slgobinath** [comment]
Hi,
I have fixed it with https://github.com/slgobinath/SafeEyes/commit/443804c3d18fd2212cdff1b00cc5ec5dc1424d1e. If there are any other issues, please do let me know.
