### ISSUE TITLE
Hardcoded directories

### ISSUE THREAD

**Issue by FedericoCeratto** [slgobinath/SafeEyes#198]
Utility.py handcodes a number of directories. Ideally a desktop application should use XDG env vars if present, e.g. XDG_CONFIG_HOME XDG_DATA_DIRS XDG_CONFIG_DIRS

See https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/4d646d4abb62e2d894569e13f4901aa68319d24b
