### ISSUE TITLE
Minor issues on the tar.gz release

### ISSUE THREAD

**Issue by Yamakaky** [slgobinath/SafeEyes#2]
- `.desktop` file is in opt and usr/share/applications
- `.desktop` file is executable

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/dd3f7978f06155fa21c64863e108bf0d1fbc90ef

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/dd3f7978f06155fa21c64863e108bf0d1fbc90ef
