### ISSUE TITLE
Save log / statistics (configurable)

### ISSUE THREAD

**Issue by CreamyCookie** [slgobinath/SafeEyes#20]
That means saving enabled / disabled times, skips and pauses. Of course it should be possible to disable these logs.

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/95b4a53e8730a8751dcfc8dc1a5d4d7cafb4ee94 and included in [v1.1.0](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.0)
