### ISSUE TITLE
Spanish localization issue

### ISSUE THREAD

**Issue by elurofilico** [slgobinath/SafeEyes#201]
Spanish (es) LC_MESSAGES not working
Others may not work either.
Tested on ubuntu 16.04 and linuxmint 18.2.

**Comment by slgobinath** [comment]
At the time of releasing Safe Eyes 2.0.0, the Spanish translation was not added. See https://github.com/slgobinath/SafeEyes/blob/v2.0.0/safeeyes/config/locale/es/LC_MESSAGES/safeeyes.po.
Will be included in the next release.

I found an issue with Spanish translation done via Weblate. Some texts were deleted by Weblate commit but I don't know why that happened. Could you please translate the rest?

Thanks
