### ISSUE TITLE
Localization doesn't fall back to English, puts out raw i18n message IDs on the screen

### ISSUE THREAD

**Issue by asoltesz** [slgobinath/SafeEyes#202]
Version 2.0 seems to have removed Hungarian localization, which - in itself - wouldn't be a big problem.

However, it doesn't fall back to English but puts out the message ID on the screen (like "short_break_roll_eyes").

This looks very bad.

Kde Neon x64 here.

I have tried "completely remove" and reinstalling with Synaptic - in hopes of only being a misconfiguration issue due to the upgrade to 2.0 - but the problem persists so it may be a bug.

**Comment by slgobinath** [comment]
Hi,
This is a known problem and the fix is provided in https://github.com/slgobinath/SafeEyes/issues/203

**Comment by slgobinath** [comment]
most of the localizations were not migrated to Safe Eyes 2.0.0 but will be included in the next release.
