### ISSUE TITLE
Safe Eyes 2.0.0: Break names are like short_break_roll_eyes

### ISSUE THREAD

**Issue by slgobinath** [slgobinath/SafeEyes#203]
This is a known bug in Safe Eyes 2.0.0. This problem can be fixed by either manually changing the break names or by following the given steps:

1. Quit currently running safe eyes
2. Remove the config directory
```
rm -r ~/.config/safeeyes
```
3. Start Safe Eyes again

**Comment by asoltesz** [comment]
It has worked. Great, many thanks.

**Comment by roopesh90** [comment]
brilliant!  :+1:

**Comment by luizcarvalho** [comment]
Thanks! same Issue. Great fix.

**Comment by slgobinath** [comment]
Fixed in 2.0.2
