### ISSUE TITLE
Xlib error

### ISSUE THREAD

**Issue by Gagazet** [slgobinath/SafeEyes#205]
Hello! Wanted to use this great program, but have problem:
<class 'Xlib.protocol.request.QueryExtension'>
Tried to update Xlib, but using last version of it. Any ideas how i can fix it?

**Comment by slgobinath** [comment]
Hi,
Could you please let me know your OS and how you have installed Safe Eyes?

Thanks

**Comment by Gagazet** [comment]
I am sorry for delay~
Its Ubuntu 14.04 LTS, i tried both way's of it, clone from git and manual one, with apt

**Comment by slgobinath** [comment]
Thanks for the update.
I will try Safe Eyes on my Ubuntu 14.04 VM and let you know the fix.

Thanks

**Comment by Gagazet** [comment]
Thank you very much, i appreciate it. Will wait for any news~

**Comment by slgobinath** [comment]
Hi,
I do get the `<class 'Xlib.protocol.request.QueryExtension'>` message on my terminal but Safe Eyes runs without any problems.

May I know when Safe Eyes terminates? Also if you could share the terminal output before termination/unexpected behavior, I can investigate it further.
Please run Safe Eyes using the following command to get the logs in terminal:
```
safeeyes --debug
```

**Comment by Gagazet** [comment]
Thank you for help! I reinstalled all, include python3 and libraries, now works well! 
Safeeyes got a great support, thank you!
