### ISSUE TITLE
Crash on Ubuntu 17.10 Gnome Wayland session: Xlib.error.XauthError in init():~/.Xauthority

### ISSUE THREAD

**Issue by peter-jerry-ye** [slgobinath/SafeEyes#206]
safeeyes crashed with Xlib.error.XauthError in __init__():~/.Xauthority: [Error 2] No such file or directory: '/home/zihang/.Xauthority'
ApportVersion: 2.20.7-0ubuntu3

By the way, is there any native solution since gnome has removed the legacy tray? When I mean native, it means without using TopIcons-plus etc.

**Comment by slgobinath** [comment]
Hi,
I also faced this problem and the solution is creating an empty `~/.Xauthority` file. Please use the following command to fix this issue:
```
touch ~/.Xauthority
```

Even though it is not an issue related to Safe Eyes, leave this issue open so that others can find the solution easily.

> By the way, is there any native solution since gnome has removed the legacy tray? When I mean native, it means without using TopIcons-plus etc.

I designed Safe Eyes 2.0.0 with keeping Gnome's guidelines in mind. According to Gnome's suggestion, the alternative to tray icon is developing our own extension. However, I am not going to write an extension in near future (but RPC api is implemented for that purpose. so developers are welcome to write an extension ;-) ). As Gnome suggests, tray icon is optional. You can disable it in the plugins section.

At the moment command line is the only way to interact with Safe Eyes without using tray icon. Starting Safe Eyes while another instance is already running, will open the settings dialog. Check `safeeyes --help` for more details.

**Comment by kandaur** [comment]
Creation of `~/.Xauthority` file helped to start safeeyes on Ubuntu 17.10
At the same time only short breaks start periodically and long breaks skip.
Also command line interact with Safe Eyes looks like strange. When software is started its status displayed as "Disabled until restart":
```
$ safeeyes --debug
2018-03-02 13:41:34,525 [INFO]:[MainThread] Safe Eyes is already running
$ safeeyes --status
Disabled until restart
$ safeeyes -d
$ safeeyes -e
$ safeeyes --status
Disabled until restart
```

**Comment by slgobinath** [comment]
Hi,
The long break issue has been resolved in a recent commit which will be included in the next release. The command line output is strange.
Could you please try this solution and let me know.
1. Quit running Safe Eyes (using Tray icon or kill using system monitor)
2. Delete the config directory
```
rm -rf ~/.config/safeeyes
```
3. Start Safe Eyes again
4. Check the status
```
safeeyes --status
```

If it does not help, please check which process is listening on port 7200 by running the following command.
```
 lsof -i :7200
```
Please execute the above command when Safe Eyes is running and not running and share the output.

**Comment by kandaur** [comment]
```
$ ps -aux | grep safee
okondaur 23076  1.2  0.8 893396 65540 tty2     Sl+  19:34   0:01 /usr/bin/python3 /usr/bin/safeeyes
root     23450  0.0  0.0  15860  1172 pts/2    S+   19:37   0:00 grep --color=auto safee
$ kill -9 23076
$ ps -aux | grep safee
root     23475  0.0  0.0  15860  1172 pts/2    S+   19:37   0:00 grep --color=auto safee
$ safeeyes --status
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
Safe Eyes is not running
```
Starting via CLI...
```
$ safeeyes -e
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
Xlib.xauth: warning, no xauthority details available
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 9, in <module>
    load_entry_point('safeeyes==2.0.4', 'console_scripts', 'safeeyes')()
  File "/usr/lib/python3/dist-packages/safeeyes/__main__.py", line 141, in main
    safeeyes = SafeEyes(system_locale, config)
  File "/usr/lib/python3/dist-packages/safeeyes/SafeEyes.py", line 77, in __init__
    self.break_screen = BreakScreen(self.context, self.on_skipped, self.on_postponed, Utility.STYLE_SHEET_PATH)
  File "/usr/lib/python3/dist-packages/safeeyes/BreakScreen.py", line 47, in __init__
    self.display = Display()
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 80, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3/dist-packages/Xlib/display.py", line 62, in __init__
    display.Display.__init__(*(self, ) + args, **keys)
  File "/usr/lib/python3/dist-packages/Xlib/protocol/display.py", line 129, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'
$ lsof -i :7200
$ 
```
Starting via GUI...
```
$ safeeyes -e
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
$ lsof -i :7200
COMMAND    PID     USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
safeeyes 24054 okondaur   11u  IPv4 1060147      0t0  TCP localhost:7200 (LISTEN)

```

**Comment by slgobinath** [comment]
Hi,
Could you uninstall `python3-xlib` and install it again?
To start Safe Eyes from command line, just call `safeeyes` or `safeeyes --debug`

**Comment by slgobinath** [comment]
Closing this because Ubuntu 17.10 is no longer supported
