### ISSUE TITLE
Add (optional) postpone button

### ISSUE THREAD

**Issue by CreamyCookie** [slgobinath/SafeEyes#21]
Preferably one could switch it off and choose for how long to postpone

A default could look like this:

- Postpone for .. <kbd>5 minutes</kbd>, <kbd>15 minutes</kbd>, <kbd>30 minutes</kbd>

**Comment by slgobinath** [comment]
+1 Good idea. I will add it soon

**Comment by CreamyCookie** [comment]
Cool. Thank you!

**Comment by slgobinath** [comment]
The issue #51 'Disable for x hours' also requires similar functionality. I am implementing the feature as suggested in issue 51. Therefore I am closing this issue and you can continue the discussion under the issue 51.
Based on what I am implementing, users get an option to disable Safe Eyes for 30 minutes, 1 hour, 2 hours, 3 hours or until restarting the system. After the specified time, Safe Eyes will resume automatically.

**Comment by Akronix** [comment]
Hi.
I think this should be re-open.
It isn't the same disable SafeEyes for x time than to postpone an specific break for just some small amount of time (2 min, 5 min?). This means you don't want to skip the break nor disable SafeEyes, but to finish your unstoppable think you're doing right now.

**Comment by slgobinath** [comment]
@Akronix valid point +1

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/SafeEyes/commit/a8f2ad4a6b8cd5ee11de04f8792801eefb669d93
