### ISSUE TITLE
Building for Windows

### ISSUE THREAD

**Issue by omar391** [slgobinath/SafeEyes#215]
I am using both win and Linux env. SafeEyes works best in Linux but windows I failed to find any equivalent tools.

Is there a way to build it for windows environment?

**Comment by slgobinath** [comment]
Actually, I developed Safe Eyes as an alternative to [Eyeleo](http://eyeleo.com/) a Windows-only tool. Since Safe Eyes uses X window manager and other Unix specific APIs, it may not work in Windows.

I hope you may find [Eyeleo](http://eyeleo.com/) useful in Windows.

**Comment by omar391** [comment]
I actually do use "Eyeleo" but it doesn't satisfy me as SafeEye does.

**Comment by slgobinath** [comment]
> I actually do use "Eyeleo" but it doesn't satisfy me as SafeEye does.

That's something unexpected and awesome to hear as the developer of Safe Eyes ^_^. Anyhow, I am sorry; I don't have any alternatives.

**Comment by decatetsu** [comment]
For next generations, there is a good alternative for windows - https://hovancik.net/stretchly/

**Comment by archisman-panigrahi** [comment]
Alternatively try WSL with some X11 environment.
