### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by FedericoCeratto** [slgobinath/SafeEyes#217]
The log in ~/.config/safeeyes/safeeyes.log grows indefinitely. Perhaps it should be rotated.

Source: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=881174

**Comment by slgobinath** [comment]
Hi,
I have a max file size limit of `5 MB` (See https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/Utility.py#L356) but I do agree that the log file location has to be changed.
Could you please suggest a better location to store the log file and the max file size to limit?

Thanks

**Comment by slgobinath** [comment]
Hi,
I have fixed it with the commit https://github.com/slgobinath/SafeEyes/commit/4227bc6613e6fdb6b1b422225774746ac914f197.
Now log file is saved to `~/.safeeyes.log` only if debug mode is enabled using the following command:
```
safeeyes --debug
```
