### ISSUE TITLE
Allow do only long breaks (or one type of breaks without long or short).

### ISSUE THREAD

**Issue by id777** [slgobinath/SafeEyes#218]

**Comment by id777** [comment]
Hi! Thanks for app! Looks really good and working fast.
But I don't like the idea with long and short breaks. Usually I using simple schedule: 35 min working, 5 min pause. I don't need long breaks. When I feel tired, I just know it and take rest.

I was thinking what I can setup same duration for both short and long breaks but no. In my simple case I can't use this app, because for the short break max allowed break time is 60 sec. I need 5 min. 

So is this possible to add simple mode with only 1 type of breaks?

**Comment by slgobinath** [comment]
Hi,
You can remove all the short breaks and use the long breaks only.
