### ISSUE TITLE
Notification about break - always 10s

### ISSUE THREAD

**Issue by Bolo92** [slgobinath/SafeEyes#219]
Hello,

I noticed that when notification is popup it always shows the same text.
I changed standard 10s before break so notification shows up earlier but display the same text.
Probably here is wrong variable ;)

https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/plugins/notification/plugin.py#L57

in this line should be value from config variable.

https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/safeeyes.json#L9

I'm not sure how to grab this variable from main config (I'm not programmer) so i didn't create the patch for this issue on my own.

**Comment by slgobinath** [comment]
Thanks for reporting this bug.
I use the hardcoded value by mistake there (https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/plugins/notification/plugin.py#L55).

I will fix it soon.

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/57418866befa1aff64d91c4de365b8aad009e18c
