### ISSUE TITLE
One monitor stays black after overlay is skipped

### ISSUE THREAD

**Issue by pakro** [slgobinath/SafeEyes#22]
Hi there, don't know if this was already reported.
On my system (3 monitors where 2 are external 1 is internal) I always experience the problem that after I skip the overlay one of the monitors stays black. It is never the monitor where the skip button is displayed.

**Comment by slgobinath** [comment]
@pakro Thanks for reporting this issue. If possible, could you please test the following fix and let me know the result after the patch.
1. Open `'BreakScreen.py`: `sudo gedit /opt/safeeyes/BreakScreen.py`
2. Goto the last line: [line](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/safeeyes/BreakScreen.py#L182)
3. Modify the line as shown below
<code>self.secondary_windows = []</code>
4. Close the gedit and run Safe Eyes again.

**Comment by pakro** [comment]
Thanks for your answer!

I've replaced the line
`del self.secondary_windows[:]`

with the line you suggested in 3.

It still does not close the overlay properly. One monitor stays black.

**Comment by slgobinath** [comment]
Thanks for your feedback. I will test it further and release the fix soon.

**Comment by slgobinath** [comment]
Hi @pakro, please test the new version 1.1.0 and let me know the result. I hope it should fix your issue.

**Comment by pakro** [comment]
Hi @slgobinath ! Instantly installed it and tried it out. First overlay was successfully removed on all displays after I skipped it. Will try and repot back if I find something, but it looks that this issue is gone. Thank you so much for fixing this issue!

**Comment by slgobinath** [comment]
You are welcome @pakro. I am closing this issue. In case you found any problems regarding the same issue, please reopen it. :-)
