### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by BlackGrizzly** [slgobinath/SafeEyes#221]
How to change language to Russian? System language is Russian, but program in English

Ubuntu 16.04, SafeEyes 2.0.0

**Comment by slgobinath** [comment]
Hi,
When I released 2.0.0, Russian translation was not complete (See https://github.com/slgobinath/SafeEyes/blob/v2.0.0/safeeyes/config/locale/ru/LC_MESSAGES/safeeyes.po). I will include it in the next release.

**Comment by BlackGrizzly** [comment]
Ok. But on break i see text like this: "short_break_close_eyes". Is this should be?

**Comment by slgobinath** [comment]
Please see https://github.com/slgobinath/SafeEyes/issues/203
