### ISSUE TITLE
How can I specify window in settings

### ISSUE THREAD

**Issue by aostruszka** [slgobinath/SafeEyes#222]
First of all thank you for this nice application.
I used to use Workrave but now prefer SafeEyes.

I've got couple of questions though:
1. I often work with QtCreator and new versions (the one taken from qt.io at least) always work in full screen mode.  How can I specify its window in settings so that SafeEyes work normally?  The preferred setting would be to skip breaks for all windows in full screen mode with the exception of A,B,C (e.g. QtCreator, Krita, ...).  The other option would be to have breaks for all full screen windows with the exception of D, E, F but in both options I don't know how to specify window.  Could you give some hint how to do that?
1. If I skip long break shouldn't screen saver not be triggered?  Right now (2.0.0) it is always triggered even if I skip the break.

Best regards
Andrzej

**Comment by slgobinath** [comment]
Hi,
1. Execute `xprop WM_CLASS` in a Terminal and click on the QtCreator app once the mouse cursor has changed to cross pointer. It will print the window class of QTCreator. Use that value in `Do not disturb` plugin's settings.
Example Window class output of SMPlayer:
```
$ xprop WM_CLASS
WM_CLASS(STRING) = "smplayer", "Smplayer"
```
i.e Window class is: `smplayer`
(I had this instruction on the previous website but not now. I will update the README file.)

2. What is the value of `Minimum seconds to skip without screensaver` in the Screensaver settings? (See the attached screenshot) I think in your case it is `0`. If so, change it to `5` seconds then you can skip the break within 5 seconds without locking the screen.
![screenshot from 2017-12-19 10-29-33](https://user-images.githubusercontent.com/4003168/34164469-9fff324a-e4a7-11e7-85c1-d4f0de3a19af.png)

**Comment by aostruszka** [comment]
Thank you for your reply.  I've started to look at 'donotdisturb' and when I saw what you are using I did nearly what you have suggested above.  Unfortunately I have not read the code below and used "QtCreator" which did not work due to lowercasing.  Sorry about that - I should have read the code below :).

As for the second question I have value '3' - so I guess I should be more vigorous when skipping break.
I think though, that no matter the screen saving settings when someone cancels the break manually screen saver should not be started, that is if I take a break and leave the desk, then when the break finishes screen should be locked but when I have a need to quickly return to desk and check something and skip the break it should not be locking the screen.  But this is really minor thing.

Thank you for your reply.

**Comment by slgobinath** [comment]
> I think though, that no matter the screen saving settings when someone cancels the break manually screen saver should not be started

There can be another scenario, as soon as you leave the desk, someone comes and skip the break (manual skip) so they will get access. That's why I implemented this way ;-)
If you want to allow skipping at any time, simply increase the time to 60 seconds or more.
