### ISSUE TITLE
[2.0.1] Language mis-detected and option to change language disappeared?

### ISSUE THREAD

**Issue by hartwork** [slgobinath/SafeEyes#225]
Hi!

I have seen #63, #221 and 0df462bb242d3930ab28c2a1d22f930d153dcd48 but none seem to help, so this ticket:

Recently Safe Eyes started talking German to me. My locale is a mix of English an German because I want 24 hour format times displayed while the system talking in English to me, otherwise. To be precise:

```
# locale | fgrep de_
LC_TIME=de_DE.UTF-8
LC_COLLATE=de_DE.UTF-8

# locale | fgrep en_
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
```

To my understanding, `LC_COLLATE` is only for comparing strings (think umlauts in German) and `LC_MESSAGES` should probably take precedence when picking a language talking to the user. What do you think? Can it be changed?

Also, I don't see a way to change language in the settings dialog anymore. I remember there was such a thing. I quickly tried add things like `"language": "en_US",` to `safeeyes.json` but I haven't gotten it to work, yet. Is there a workaround to enforce English message?

Thanks and best

Sebastian

**Comment by slgobinath** [comment]
Hi,
I removed the option to select language since I used the built-in libraries to detect the system language.
I will have a look at this issue.

**Comment by leedoyle** [comment]
@slgobinath I'm also having this issue. My system's locale is en_US, but for some reason the interface is in Russian, and I can't change it.

**Comment by aostruszka** [comment]
Sorry I've just logged an issue from the code preview since I got the same problem but I have not browsed existing issues.  Please treat #230 as an entry in this issue.

@hartwork @leedoyle Could you guys test the patch I've added to #230 to see if it is working for you?

**Comment by slgobinath** [comment]
Even though this issue is reported before #230, I am closing this because #230 has more details on how to fix.
