### ISSUE TITLE
Why this program use RPC?

### ISSUE THREAD

**Issue by bhctsntrk** [slgobinath/SafeEyes#226]
I couldn't figure out why this program open my 7200 port. How can I use this program without open any ports in my Linux.

**Comment by slgobinath** [comment]
The RPC is used to control the running Safe Eyes instance from command line. Tray icon became an optional feature from Safe Eyes 2.0.0 (Gnome's decision to removing tray icon is one reason) so there is a requirement for an alternative way to control Safe Eyes.

Though you cannot disable RPC, you can change the port by editing [rpc_port](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/safeeyes.json#L13) in `~/.config/safeeyes.json`.

**Comment by bhctsntrk** [comment]
I understand thanks.
