### ISSUE TITLE
Add 'status' command line argument

### ISSUE THREAD

**Issue by petermehle** [slgobinath/SafeEyes#227]
I use xMonad without any tray icons and there is no way to see if safeeyes is enabled or disabled. I sometimes disable it when I am watching something and then I always forget to enable it again. Please add 'status' (or similar, name is not important) command that will show the current status.

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/SafeEyes/commit/866bea6b309fdfce9b963002acc0b0605554ff04
