### ISSUE TITLE
does not start with Ubuntu 16.04.1 

### ISSUE THREAD

**Issue by Wilmup** [slgobinath/SafeEyes#236]
After numerous problems with my computer, today I've re installed Safe Eyes 

`$ sudo add-apt-repository ppa:slgobinath/safeeyes`
`$ sudo apt update`
`$ sudo apt install safeeyes`

but it refuses to start:

`$ safeeyes`

```
(safeeyes:6381): Gtk-WARNING **: Theme parsing error: sidebar.css:71:12: 'text-align' is not a valid property name
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 11, in <module>
    load_entry_point('safeeyes==2.0.2.1', 'console_scripts', 'safeeyes')()
  File "/usr/lib/python3/dist-packages/safeeyes/__main__.py", line 134, in main
    safeeyes = SafeEyes(system_locale, config)
  File "/usr/lib/python3/dist-packages/safeeyes/SafeEyes.py", line 87, in __init__
    self.plugins_manager.init(self.context, self.config)
  File "/usr/lib/python3/dist-packages/safeeyes/PluginManager.py", line 92, in init
    plugin['module'].init(context, config, plugin['config'])
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 369, in init
    tray_icon = TrayIcon(context, plugin_config)
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 138, in __init__
    self.set_labels()
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 169, in set_labels
    entry[0].set_label(self.context['locale'].ngettext(entry[1][0], entry[1][1], entry[2]) % entry[2])
TypeError: not all arguments converted during string formatting
```

What went wrong?
Regards

**Comment by slgobinath** [comment]
Hi,
Could you please share the output of `locale` command in terminal?

**Comment by Wilmup** [comment]
Hi, 
sorry but I did not understand what type of command I have to put in terminal. Could you be more precise?

**Comment by slgobinath** [comment]
Hi,
Open your terminal, type `locale` and hit enter. You should get an output similar to this:
```
$ locale
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=
```
Copy and paste that output here.

**Comment by Wilmup** [comment]
```
$ locale
LANG=it_IT.UTF-8
LANGUAGE=it_IT
LC_CTYPE="it_IT.UTF-8"
LC_NUMERIC="it_IT.UTF-8"
LC_TIME="it_IT.UTF-8"
LC_COLLATE="it_IT.UTF-8"
LC_MONETARY="it_IT.UTF-8"
LC_MESSAGES="it_IT.UTF-8"
LC_PAPER="it_IT.UTF-8"
LC_NAME="it_IT.UTF-8"
LC_ADDRESS="it_IT.UTF-8"
LC_TELEPHONE="it_IT.UTF-8"
LC_MEASUREMENT="it_IT.UTF-8"
LC_IDENTIFICATION="it_IT.UTF-8"
LC_ALL=
```

**Comment by slgobinath** [comment]
Hi,
This is because of a bug in Italian translation.
See:
- https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/locale/it/LC_MESSAGES/safeeyes.po#L373
- https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/locale/it/LC_MESSAGES/safeeyes.po#L379
- https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/locale/it/LC_MESSAGES/safeeyes.po#L385

In all these lines, `un` is used instead of `%d`. Could you please replaced them by `%d` using Weblate because Python requires `%d` at the runtime.

**Comment by Wilmup** [comment]
Ok. I'm working on it.

**Comment by Wilmup** [comment]
Done. I apologize for the error.

**Comment by slgobinath** [comment]
Thanks. No problem.
I will close this issue once your changes are pushed to the master branch.

**Comment by slgobinath** [comment]
Fixed in https://github.com/slgobinath/SafeEyes/commit/6d53909eb72a7d4409a3ddfa36bbe86b067963f2
