### ISSUE TITLE
Add 'About' menu

### ISSUE THREAD

**Issue by Gabriel-p** [slgobinath/SafeEyes#24]
The installed version of the app, and some other important info (like the app's Github site to report issues), are nowhere to be found.

Perhaps they could be added in an 'About' menu in the pop-up.

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/SafeEyes/commit/177605d9bff6ba1bcc5d58538cbab48feca0d434 and included in [v1.1.1](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.1)
