### ISSUE TITLE
Show Next long break too in indicator menu [Feature Request]

### ISSUE THREAD

**Issue by Conceptron** [slgobinath/SafeEyes#241]
Currently, the next short break time is being shown. Could you also show the next long break time as sometimes I feel the long break feature isn't working. Thanks

**Comment by slgobinath** [comment]
Hi,
This issue has been reported and fixed in https://github.com/slgobinath/SafeEyes/issues/240.
However, please leave this issue open until I release the next version with the fix.

Thanks

**Comment by slgobinath** [comment]
Please check Safe Eyes 2.0.5
