### ISSUE TITLE
Install instructions for Fedora

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#242]
Hey @slgobinath,

Just a quick note. 

I think it's better to mention pip3 to install with `--user` flag. 

What do you think?

Attaching the screenshots for reference.

Thanks!

![screenshot from 2018-02-27 10-19-00](https://user-images.githubusercontent.com/170947/36725158-b03872bc-1bb5-11e8-8ffc-4fd9f52b0a51.png)
![screenshot from 2018-02-27 10-18-53](https://user-images.githubusercontent.com/170947/36725161-b0670474-1bb5-11e8-8083-d2c76feea494.png)

**Comment by slgobinath** [comment]
Hi,
Safe Eyes requires sudo privileges to install files. So we cannot ignore `sudo`.

**Comment by orschiro** [comment]
I see. So we can safely ignore the warning from pip?

**Comment by slgobinath** [comment]
Yeah.
For example, it installs icon images in `/usr/share/icons/hicolor...` which cannot be done without sudo.

**Comment by orschiro** [comment]
Got you. Thanks!
