### ISSUE TITLE
Add Lithuanian language to Weblate

### ISSUE THREAD

**Issue by welaq** [slgobinath/SafeEyes#245]
Please add Lithuanian language to Weblate, I have sent request there and would like to translate to make it until new release.

**Comment by slgobinath** [comment]
Hi,

Added with https://github.com/slgobinath/SafeEyes/commit/b28b4a96cc3c88c576d2643b9e35980482a4a9af.
Please visit https://hosted.weblate.org/projects/safe-eyes/translations/lt/

Thank you for your interest :-)
