### ISSUE TITLE
Postpone long break after long inactivity periods and sleep

### ISSUE THREAD

**Issue by Vavooon** [slgobinath/SafeEyes#249]
As far as I see the application uses simple logic: it just starts a long break after some count of short ones. However it may be an issue when a user works on PC until few short breaks are started, then he leaves PC for sleep or other activity and then when he returns a long break is still in queue.
I believe the app shouldn't act in such way because there is no reason to make another long break after user was away from PC.
P.S. If you want I can give you a link to my own app sources where I've implemented such logic.

**Comment by Vavooon** [comment]
I see, that's the bug created by me :)
I used next logic to deal with the issue:
There were two independent countdowns: one for short breaks and one for long ones.
They were decreased each second during user activity. Then, if system idle time became more than 30 seconds (for example) the countdowns stopped and if inactivity time because higher than a minute countdowns started increasing. 

Let me write some pseudo code to describe the idea:
```
int timeToShortBreakSetting = 60; // Short break interval value
int timeToLongBreakSetting = 600; // Long break interval value

int timeToShortBreak = timeToShortBreakSetting; // Init coundowns with default values
int timeToLongBreak = timeToLongBreakSetting;

int timerStopThreshold = 30; // Inactivity time after which timers stop decreasing
int timerRollbackThreshold = 60; // Inactivity time after which timers start increasing


// Run this code on timer tick

int idleTime = getSystemIdleTime(); //function should return how much seconds passed from latest user input

if (idleTime < timerStopThreshold) {
  timeToShortBreak--;
  timeToLongBreak--;
}
else if (idleTime >= timerStopThreshold && idleTime < timerRollbackThreshold) {
  // Do nothing during this period
}
else if (idleTime >= timerRollbackThreshold) {
  timeToShortBreak++;
  timeToLongBreak++;
  if (timeToShortBreak > timeToShortBreakSetting) {
    timeToShortBreak = timeToShortBreakSetting;
  }
  if (timeToLongBreak > timeToLongBreakSetting) {
    timeToLongBreak = timeToLongBreakSetting;
  }
}

if (timeToLongBreak <= 0) {
  startLongBreak();
}
else if (timeToShortBreak <= 0) {
  startShortBreak();
}
```

I wanted to write it in your app but unfortunately I'm not so good with Python :(

**Comment by slgobinath** [comment]
> I see, that's the bug created by me :)

Ohh yeah!!! I didn't notice that :D

**Comment by Vavooon** [comment]
1. Maybe it would be possible to create `getSystemIdleTime` stub which will always return 0 and redefine it in the plugin.
2. I'm not sure about Python but in C++ running a timer each second isn't very CPU consuming operation at all(I believe OS has hundreds of such timers running in background). It can be running more rarely, for example each 5 seconds. In this case only one thing to change would be 
```
timeToShortBreak =- 5;
timeToLongBreak =- 5;
```
but I'd make it even more flexible by calculating seconds passed from last timer tick, e.g.
```
int secondsFromLastTick = getCurrentTimestamp() - lastTickTimestamp;
// Process our coundowns
timeToShortBreak =- secondsFromLastTick;
timeToLongBreak =- secondsFromLastTick;
// Store current timestamp
lastTickTimestamp = getCurrentTimestamp();
```

Your idea also looks good. Maybe one advantage of using two separate timers is that it is more easy to debug breaks when you see how much time is left.
NP, I'm not hurrying you :)

**Comment by slgobinath** [comment]
Fixed in https://github.com/slgobinath/SafeEyes/commit/3a7ebc4047fbe9b5029d28819c2d5b51ed147ecd.

For the moment I am using single timer due to the simplicity. I will consider using two separate tickers if it is required in future.

Thank you very much for your idea. I would be grateful if you can test this feature before the release.

**Comment by Vavooon** [comment]
Thank you so much. I've pulled latest sources and already running them. 
BTW how can I install the app from its sources?

**Comment by slgobinath** [comment]
`sudo python3 setup.py install` from SafeEyes folder should work.

I am going to release the new version (hopefully within 2 days) after testing on Fedora and Manjaro.
