### ISSUE TITLE
Unstable on Ubuntu 18.04

### ISSUE THREAD

**Issue by peter-jerry-ye** [slgobinath/SafeEyes#251]
Hi,
I recently updated my OS from Ubuntu 17.10 to 18.04. But I found that the safeeyes isn't stable.
Sometimes it keeps getting to the status of "Disabled until restart", and then it will restart itself. It is repeating this procedure while I'm typing here. Apparently this hasn't affected it's function, but watching it switching on and off is quite annoying.

Is there any information I should provide you?

And I've got another question. Is it possible to remove the tray icon since it's unnecessary? 'Cause with the plugin of Ubuntu on, it will be displayed even if it's necessary. Is it possible to make it a choice like the Variety by Peter Levi has done?
Thanks.

**Comment by slgobinath** [comment]
Hi,
> safeeyes isn't stable

Could you please try disabling `Smart Pause` plugin and see what happens. If it is stable, please execute `xprintidle` in terminal few times check whether it prints the correct idle time. If executed manually, it should be less than `10`.

>  Is it possible to remove the tray icon since it's unnecessary?

Of course, you can. Just disable the `Tray Icon` plugin and restart Safe Eyes. You may find the command line parameters useful. Try `safeeyes --help` from the terminal to check the available options.

**Comment by peter-jerry-ye** [comment]
Well in fact, the safeeyes works without any problem. I do get my breaks. However, it was the icon on the tray that keeps indicating that the safeeyes is shut down and restarted. With that said, the every time it changed status, the time expected for the break hasn't changed.
And I tried the ```` xprintidle ```` again, and it worked as it should when I move my mouse around.

**Comment by peter-jerry-ye** [comment]
Yes.
Well, in fact, since I've closed the tray icon, which stopped it annoying me, and the safeeyes works well, perhaps we can close this issue. Apparently no one else has been affected.

**Comment by slgobinath** [comment]
The time not updated problem has been already reported here at #211 so I close this issue.

**Comment by TheCrowned** [comment]
Reopen just to say that I have similar issues. I ran `safeeyes --debug` and this is my output:

> stefano@Lemur:~$ safeeyes --debug
2018-05-24 08:28:21,285 [INFO]:[MainThread] Starting Safe Eyes
2018-05-24 08:28:21,336 [INFO]:[MainThread] Initialize the break screen
2018-05-24 08:28:21,336 [INFO]:[MainThread] Load all the plugins
2018-05-24 08:28:21,336 [INFO]:[MainThread] Initialize the core
2018-05-24 08:28:21,338 [INFO]:[MainThread] Successfully loaded <module 'trayicon.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py'>
2018-05-24 08:28:21,340 [INFO]:[MainThread] Successfully loaded <module 'notification.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/notification/plugin.py'>
2018-05-24 08:28:21,341 [INFO]:[MainThread] Successfully loaded <module 'healthstats.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/healthstats/plugin.py'>
2018-05-24 08:28:21,342 [INFO]:[MainThread] Successfully loaded <module 'audiblealert.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/audiblealert/plugin.py'>
2018-05-24 08:28:21,343 [INFO]:[MainThread] Successfully loaded <module 'screensaver.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/screensaver/plugin.py'>
2018-05-24 08:28:21,345 [INFO]:[MainThread] Successfully loaded <module 'donotdisturb.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/donotdisturb/plugin.py'>
2018-05-24 08:28:21,345 [DEBUG]:[MainThread] Initialize Tray Icon plugin
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 11, in <module>
    load_entry_point('safeeyes==2.0.0', 'console_scripts', 'safeeyes')()
  File "/usr/lib/python3/dist-packages/safeeyes/__main__.py", line 132, in main
    safeeyes = SafeEyes(system_locale, config)
  File "/usr/lib/python3/dist-packages/safeeyes/SafeEyes.py", line 87, in __init__
    self.plugins_manager.init(self.context, self.config)
  File "/usr/lib/python3/dist-packages/safeeyes/PluginManager.py", line 92, in init
    plugin['module'].init(context, config, plugin['config'])
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 369, in init
    tray_icon = TrayIcon(context, plugin_config)
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 138, in __init__
    self.set_labels()
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 169, in set_labels
    entry[0].set_label(self.context['locale'].ngettext(entry[1][0], entry[1][1], entry[2]) % entry[2])
TypeError: not all arguments converted during string formatting

**Comment by slgobinath** [comment]
Hi,
May I know your locale (Execute `locale` in terminal)?

**Comment by TheCrowned** [comment]
Here you are :)

```
LANG=it_IT.UTF-8
LANGUAGE=
LC_CTYPE="it_IT.UTF-8"
LC_NUMERIC="it_IT.UTF-8"
LC_TIME="it_IT.UTF-8"
LC_COLLATE="it_IT.UTF-8"
LC_MONETARY="it_IT.UTF-8"
LC_MESSAGES="it_IT.UTF-8"
LC_PAPER="it_IT.UTF-8"
LC_NAME="it_IT.UTF-8"
LC_ADDRESS="it_IT.UTF-8"
LC_TELEPHONE="it_IT.UTF-8"
LC_MEASUREMENT="it_IT.UTF-8"
LC_IDENTIFICATION="it_IT.UTF-8"
LC_ALL=

```

**Comment by TheCrowned** [comment]
Any news on this? This makes Safe Eyes not working at all for me :(

**Comment by slgobinath** [comment]
Hi,
Sorry, I forgot to reply you. There is nothing wrong with locale files.  May I know your Python version (`python3 -V`) and the content of `~/.config/safeeyes/safeeyes.json`.

**Comment by TheCrowned** [comment]
Sure! Thanks for taking care of this!

Python 3.6.5

safeyes.json
`{
    "allow_postpone": false,
    "break_interval": 20,
    "long_break_duration": 60,
    "long_breaks": [
        {
            "name": "long_break_walk"
        },
        {
            "name": "long_break_lean_back"
        }
    ],
    "meta": {
        "config_version": "6.0.0"
    },
    "no_of_short_breaks_per_long_break": 5,
    "persist_state": false,
    "plugins": [
        {
            "enabled": true,
            "id": "trayicon",
            "settings": {
                "disable_options": [
                    {
                        "time": 30,
                        "unit": "minute"
                    },
                    {
                        "time": 1,
                        "unit": "hour"
                    },
                    {
                        "time": 2,
                        "unit": "hour"
                    },
                    {
                        "time": 3,
                        "unit": "hour"
                    }
                ],
                "show_time_in_tray": false
            },
            "version": "0.0.1"
        },
        {
            "enabled": true,
            "id": "notification",
            "version": "0.0.1"
        },
        {
            "enabled": false,
            "id": "healthstats",
            "version": "0.0.1"
        },
        {
            "enabled": false,
            "id": "smartpause",
            "settings": {
                "idle_time": 3
            },
            "version": "0.0.1"
        },
        {
            "enabled": false,
            "id": "audiblealert",
            "version": "0.0.1"
        },
        {
            "enabled": false,
            "id": "screensaver",
            "settings": {
                "command": "",
                "min_seconds": 3
            },
            "version": "0.0.1"
        },
        {
            "enabled": true,
            "id": "donotdisturb",
            "settings": {
                "skip_break_windows": "",
                "take_break_windows": "",
                "unfullscreen": true
            },
            "version": "0.0.1"
        }
    ],
    "postpone_duration": 5,
    "pre_break_warning_time": 10,
    "rpc_port": 7200,
    "short_break_duration": 30,
    "short_breaks": [
        {
            "name": "short_break_close_eyes"
        },
        {
            "name": "short_break_roll_eyes"
        },
        {
            "name": "short_break_rotate_clockwise"
        },
        {
            "name": "short_break_rotate_counter_clockwise"
        },
        {
            "name": "short_break_blink"
        },
        {
            "name": "short_break_focus_far_distance"
        },
        {
            "name": "short_break_drink_water"
        }
    ],
    "shortcut_disable_time": 2,
    "shortcut_postpone": 65,
    "shortcut_skip": 9,
    "strict_break": true
}`

**Comment by slgobinath** [comment]
I think I found the issue.
This bug was in Safe Eyes 2.0.0 and fixed in later versions. I recommend to use the latest version but before that uninstall Safe Eyes 2.0.0.

Please try this solution and let me know.
1. Uninstall Safe Eyes
2. Remove config/safeeyes directory: `rm -rf ~/.config/safeeyes`
3. Remove safeeyes from bin if exissts: `rm -f /usr/bin/safeeyes`
4. Remove any temporary files left in Python directory: `rm -rf /usr/lib/python3/dist-packages/safeeyes`
5. Install Safe Eyes 2.0.5

**Comment by TheCrowned** [comment]
Cool, this solved the issue for me, thanks a lot man! Really appreciate your help! I'm back to not having wrists/arms aching at the of the day :)

**Comment by slgobinath** [comment]
It's my pleasure.
Have a great day :-)
