### ISSUE TITLE
Blinking tray icon shortly before next break?

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#253]
Hey all, 

Please tell me if I am alone here with this problem! :-P

So, I already set SafeEyes to show the next break time next to the tray icon. 

But still! I keep forgetting about the next break and find those pop-up notifications too obtrusive. 

Hence my idea: a blinking tray icon. That would easily catch my eye and inform me about the next break time. 

Your thoughts? Useful or just stupid? :-)

Thanks!

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/SafeEyes/commit/35cfa50c95caa0fa20859bea545657949f7197bd

**Comment by slgobinath** [comment]
I'm gonna call the next release by your name because all the features were requested by you :smile:

**Comment by orschiro** [comment]
@slgobinath I am glad for your openness to my ideas. 🤗😋

**Comment by slgobinath** [comment]
Released in 2.0.9

**Comment by orschiro** [comment]
@slgobinath what a great release! :clinking_glasses:
