### ISSUE TITLE
Fix missing dep SafeEyes Debian installation instructions

### ISSUE THREAD

**Issue by larkvirtual** [slgobinath/SafeEyes#256]
-sudo apt-get install gir1.2-appindicator3-0.1 gir1.2-notify-0.7 python3-psutil python3-xlib xprintidle
+sudo apt-get install gir1.2-appindicator3-0.1 gir1.2-notify-0.7 python3-psutil python3-xlib xprintidle python3-pip

**Comment by slgobinath** [comment]
Fixed
