### ISSUE TITLE
SafeEyes Don't launch on Manjaro

### ISSUE THREAD

**Issue by RiajulKashem** [slgobinath/SafeEyes#262]
I have installed SafeEyes. When I Type on a terminal safeeyes just nothing happens. I tried several commands like

> safeeyes -e
> safeeyes -d
> safeeyes -a
> safeeyes -s

**Comment by slgobinath** [comment]
Hi,
Just call `safeeyes` from terminal.

May I know how you have installed it on Manjaro?

**Comment by RiajulKashem** [comment]
I installed  Manjaro by downloading iso file. BTW I have again tested safeeys from the terminal and got this output :(

> safeeyes -e

> ERROR:root:Error in loading the plugin: trayicon

**Comment by RiajulKashem** [comment]
No Installed via pip sudo python  -m pip install safeeyes but during the installation i got an error something like

> tensorboard 1.8.0 has requirement html5lib==0.9999999, but you'll have html5lib 1.0.1 which is incompatible.
> bleach 1.5.0 has requirement html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999, but you'll have html5lib 1.0.1 which is incompatible.

**Comment by slgobinath** [comment]
`pip` does not install some required libraries.

1. Please remove Safe Eyes using `sudo pip uninstall safeeyes`
2. Enable AUR in Manjaro `Add/Remove Software` (Check this blog for gif explanation: https://manjaro-tutorial.blogspot.com/2016/09/how-to-enable-aur-repository-on-manjaro.html)
3. Search for `safeeyes` in `Add/Remove Software` and install it

**Comment by RiajulKashem** [comment]
I searched for safeeyes but no package found :(
then i tried for **yaourt -S safeeyes** and i got this error

`
[riajulk@riajul-pc ~]$  yaourt -S safeeyes

==> Downloading safeeyes PKGBUILD from AUR...
x .SRCINFO
x .gitignore
x PKGBUILD
knight_corvi commented on 2016-10-25 17:20			 
Are you using GNOME+Wayland by any chance?
The application doesn't seem to be working for me. The process is there, but there is no tray icon I can click on the legacy tray bar. I will look further into the issue at any rate.

third_man commented on 2016-10-26 05:06			 
Please add python2-gobject as dependency. It provides necessary gi module.

imdn commented on 2017-10-05 21:36			 
Like @third_man commented python-gobject is a necessary dependency. Without it you will encounter the following error:

AttributeError: module 'gi' has no attribute 'require_version'

addictgamer commented on 2018-01-05 04:31			 

FredBezies commented on 2018-01-17 12:34			 

safeeyes 2.0.6-1  (2018-06-26 18:35)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> n

==> safeeyes dependencies:
 - alsa-utils (already installed)
 - hicolor-icon-theme (already installed)
 - python (already installed)
 - python-babel (already installed)
 - python-dbus (already installed)
 - python-gobject (already installed)
 - python-psutil (already installed)
 - xorg-xprop (already installed)
 - python-setuptools (already installed) [makedepend]
 - libappindicator-gtk3 (package found)
 - python-xlib (package found)


==> Continue building safeeyes ? [Y/n]
==> ----------------------------------
==> y

==> Building and installing package
==> Install or build missing dependencies for safeeyes:
resolving dependencies...
looking for conflicting packages...

Packages (5) libdbusmenu-glib-16.04.0-2  libdbusmenu-gtk3-16.04.0-2
             libindicator-gtk3-12.10.1-7  libappindicator-gtk3-12.10.0-12
             python-xlib-0.23-1

Total Installed Size:  1.94 MiB

:: Proceed with installation? [Y/n] y
(5/5) checking keys in keyring                      [##########################] 100%
(5/5) checking package integrity                    [##########################] 100%
(5/5) loading package files                         [##########################] 100%
(5/5) checking for file conflicts                   [##########################] 100%
error: failed to commit transaction (conflicting files)
python-xlib: /usr/lib/python3.6/site-packages/Xlib/X.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/XK.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/Xatom.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/Xcursorfont.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/Xutil.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__init__.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__pycache__/X.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__pycache__/XK.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__pycache__/Xatom.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__pycache__/Xcursorfont.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__pycache__/Xutil.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__pycache__/__init__.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__pycache__/display.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__pycache__/error.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__pycache__/rdb.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__pycache__/threaded.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/__pycache__/xauth.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/display.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/error.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__init__.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__pycache__/__init__.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__pycache__/composite.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__pycache__/ge.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__pycache__/randr.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__pycache__/record.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__pycache__/security.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__pycache__/shape.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__pycache__/xfixes.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__pycache__/xinerama.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__pycache__/xinput.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/__pycache__/xtest.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/composite.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/ge.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/randr.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/record.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/security.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/shape.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/xfixes.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/xinerama.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/xinput.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/ext/xtest.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__init__.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/__init__.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/apl.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/arabic.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/cyrillic.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/greek.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/hebrew.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/katakana.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/korean.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/latin1.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/latin2.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/latin3.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/latin4.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/miscellany.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/publishing.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/special.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/technical.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/thai.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/xf86.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/xk3270.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/__pycache__/xkb.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/apl.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/arabic.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/cyrillic.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/greek.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/hebrew.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/katakana.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/korean.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/latin1.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/latin2.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/latin3.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/latin4.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/miscellany.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/publishing.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/special.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/technical.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/thai.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/xf86.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/xk3270.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/keysymdef/xkb.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/__init__.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/__pycache__/__init__.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/__pycache__/display.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/__pycache__/event.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/__pycache__/request.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/__pycache__/rq.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/__pycache__/structs.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/display.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/event.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/request.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/rq.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/protocol/structs.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/rdb.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/support/__init__.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/support/__pycache__/__init__.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/support/__pycache__/connect.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/support/__pycache__/lock.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/support/__pycache__/unix_connect.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/support/__pycache__/vms_connect.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/support/connect.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/support/lock.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/support/unix_connect.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/support/vms_connect.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/threaded.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xauth.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/__init__.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/__pycache__/__init__.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/__pycache__/colormap.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/__pycache__/cursor.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/__pycache__/drawable.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/__pycache__/fontable.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/__pycache__/icccm.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/__pycache__/resource.cpython-36.pyc exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/colormap.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/cursor.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/drawable.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/fontable.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/icccm.py exists in filesystem
python-xlib: /usr/lib/python3.6/site-packages/Xlib/xobject/resource.py exists in filesystem
Errors occurred, no packages were upgraded.`

**Comment by slgobinath** [comment]
Hi,
It happens due to conflicting files in Xlib. This is a common problem in Manjaro. Please search on Google on how to fix this.
