### ISSUE TITLE
Disable the ability to disable Safe Eyes

### ISSUE THREAD

**Issue by seekM** [slgobinath/SafeEyes#264]
Safe Eyes offers the ability to disable Safe Eyes for a specific time (Right click -> "Disable Safe Eyes" -> "For 30 Minutes" / ...). Is it possible to disable this feature?

**Comment by slgobinath** [comment]
Hi,
Do you want to disable only `Disable for x` and leave the `Disable until restart` or disable the ability to disable Safe Eyes at all?

**Comment by seekM** [comment]
Sorry for not being precise. Both options would appeal to me: On the one hand, I tend to shift breaks (which I actually don't want to shift) by using `Disable for x`. I haven't used `Disable until restart` yet, so regarding this, disabling `Disable for x` would suffice. On the other hand, a bigger hurdle to prevent shifting breaks would be to disable both `Disable until restart` and `Quit`. If I had the choice, I would go for the second option because I fear that I could use `Disable until restart` and `Quit` to shift breaks as well. One could still kill the process via the terminal if one needs. Though this could be used to prevent breaks as well, I think that would be an even bigger hurdle and more uncomfortable than just clicking `Quit`.

**Comment by slgobinath** [comment]
Sure. It makes sense.
Though we don't have this feature at the moment, it is worth to implement. I will implement this feature once I get some time.

**Comment by smith558** [comment]
@slgobinath seems like this may be closed as the feature has been implemented

**Comment by archisman-panigrahi** [comment]
Uncheck plugin -> tray icon (settings) -> Allow disabling safe eyes
