### ISSUE TITLE
Missing dependency dbus in setup.py

### ISSUE THREAD

**Issue by yurivict** [slgobinath/SafeEyes#265]
You import it here https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/rpc.py#L25 but don't mention it in ```setup.py```.

**Comment by yurivict** [comment]
Same with ```dbus``` import.

**Comment by slgobinath** [comment]
Hi,
`xmlrpc` is available in Python 3 standard library. Please check https://docs.python.org/3/library/xmlrpc.html

Though I am not sure, I think `dbus` dependency is available in Linux distributions.

**Comment by yurivict** [comment]
What do you mean "already available"? It is available, but not installed. So if you install SafeEyes it will end up broken because py-dbus isn't installed, just like with any other dependency.

**Comment by slgobinath** [comment]
Ohh I see.
I meant it is already installed.
May I know the distribution on which you have the problem installing Safe Eyes?

**Comment by yurivict** [comment]
> May I know the distribution on which you have the problem installing Safe Eyes?

FreeBSD. You can't rely on the fact that some other package happens to install your dependency. What if they only install openeyes and a bare-minimum window manager? Then openeyes will break.
