### ISSUE TITLE
ERROR:root:Error in loading the plugin: trayicon

### ISSUE THREAD

**Issue by yurivict** [slgobinath/SafeEyes#268]
This is printed every time during start.

**Comment by MihaiAnei** [comment]
You might need some deps from here: https://github.com/slgobinath/SafeEyes#other-linux--run-from-source

Especially libappindicator-gtk3

**Comment by cs96and** [comment]
This is the [same issue](https://github.com/slgobinath/SafeEyes/issues/428) I am having on Debain 11 (bullseye) .

libappindicator-gtk3 no longer exists.  It has been replaced with  libayatana-appindicator3-1.  I tried installing gir1.2-ayatanaappindicator3-0.1 and libayatana-appindicator3-1 instead, but I still get the same error.

**Comment by archisman-panigrahi** [comment]
Is this issue still present?

**Comment by archisman-panigrahi** [comment]
Cannot reproduce in Linux Mint 22.
