### ISSUE TITLE
Show next time next to icon when using TopIcons (Plus) GNOME extension

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#270]
Dear @slgobinath,

Can you help me get the next time to display next to the icon when using the [TopIcons](https://extensions.gnome.org/extension/495/topicons/) or [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/) extension for GNOME?

Thank you for any help you can provide.

![image](https://user-images.githubusercontent.com/170947/43710258-6d565ab2-996f-11e8-9afa-492c02bf5427.png)

**Comment by slgobinath** [comment]
Hi,
You need to enable `Show next break time in tray icon` option as shown below.
![enable time](https://user-images.githubusercontent.com/4003168/43718171-d4664f72-9957-11e8-8dcd-e29d4a7768bc.png)


This feature does not work in some desktop environments (Eg: Cinnamon). I tested this some time ago on Fedora with Gnome and Ubuntu with Gnome and it was working as expected.
Please give it a try and let me know.

**Comment by orschiro** [comment]
I appreciate your reply!

The setting is turned on. The problem arises from default GNOME not supporting tray icons. 

Hence you need to rely on an extension. 

What is unclear to me, why the time is properly shown next to the icon when using [(K)StatusNotifierItem/AppIndicator Support](https://extensions.gnome.org/extension/615/appindicator-support/) whereas it doesn't work with the aforementioned TopIcon extensions. 

Do you know why that is?

Thanks.

**Comment by slgobinath** [comment]
Sorry that I don't know.

I tested this with [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/) but I don't know their current status.

Let's see if anyone knows the reason.

**Comment by orschiro** [comment]
Meanwhile, I have switched back from TopIcons Plus to (K)StatusNotifierItem/AppIndicator Support which is displaying the time next to the icon just fine. 

Thanks for your help!

**Comment by orschiro** [comment]
Dear @slgobinath,

Could you please do me a favour and once again test it with [TopIcons Plus](https://extensions.gnome.org/extension/1031/topicons/)?

I tried it just now and for me it does not show next to the icon despite having set the setting.

Thank you!

**Comment by slgobinath** [comment]
It works!
I installed Ubuntu 18.04 on Virtual Box (fresh minimal installation) and installed the TopIcons Plus extension. Then I installed Safe Eyes using PPA and enabled to show time in the tray icon.
Here is the screenshot:
![ubuntu 18 04 top icons plus](https://user-images.githubusercontent.com/4003168/43900602-63c36080-9bb3-11e8-83be-dcdee97e0acd.png)

**Comment by orschiro** [comment]
Thank you so much!

It would be helpful if someone else with Fedora could test it as well. 

Looking at your screenshot, I can see that your theming of this context menu is different than mine. 

Maybe that's the problem?

![image](https://user-images.githubusercontent.com/170947/43901140-fe35d098-9be6-11e8-8e5f-525cb2fbbd5e.png)

**Comment by slgobinath** [comment]
Problem confirmed on Fedora 28.

> Looking at your screenshot, I can see that your theming of this context menu is different than mine.

I think you refer to the gap between the first two items. It is a separator. Some themes do not show a separator. Instead, they add a huge gap. Therefore, it is a problem with the Ubuntu theme.

In Fedora with TopIcons Plus, I couldn't get time in the tray icon. In addition, if I change that setting once, tray icon becomes unresponsive. At the moment, I don't know the reason behind this issue. I will try my best to figure it out.

**Comment by orschiro** [comment]
Thanks for your efforts! 

In fact, I think I know why it works on Ubuntu. The K Status notifier extension is installed by default on Ubuntu and may hence overwrite TopIcons Plus, even if installed manually by the user. 

The K Status notifier extension is not installed by default on Fedora, however. Plus, it is buggy. Thus, it would be great if we can show the time with TopIcons plus to have a stable alternative!

**Comment by slgobinath** [comment]
Hi @orschiro,
Today I tested the current Safe Eyes on Fedora 29. I found TopIcons Plus has one more more issue. In my test, after disabling Safe Eyes using the tray icon, the icon becomes inactive forever. I couldn't get the tray menu by clicking on the icon thereafter.

According to the OmgUbuntu article: [Bad News for Users of TopIcons Plus…](https://www.omgubuntu.co.uk/2017/09/top-icons-plus-development-paused), TopIcons Plus is not longer _actively_ maintained and kStatusNotifier looks like the viable alternative.

**Comment by orschiro** [comment]
Thanks for testing @slgobinath! I guess we can close this one then. 

Appreciate it.

**Comment by vortexnix** [comment]
I know this issue is closed. But looks like KStatusNotifier extension cannot be installed on Ubuntu Gnome 16.04, so the timer cannot be displayed alongside try icon (by using Topicons Plus). Hope this helps someone who is still on Ubuntu 16.04 for whatever reason. Thanks.
