### ISSUE TITLE
Ubuntu 18.04: White bar on the right during break

### ISSUE THREAD

**Issue by seekM** [slgobinath/SafeEyes#271]
Using Ubuntu 18.04, a white vertical bar appears on the right side of the break screen:

![screenshot from 2018-08-15 18-29-29](https://user-images.githubusercontent.com/13386344/44160151-c76cf280-a0b9-11e8-9d82-4e195fc5ba01.png)

**Comment by archisman-panigrahi** [comment]
Ubuntu 18.04 has reached end of support. Cannot reproduce this on Linux Mint 22 and Kubuntu 24.04
