### ISSUE TITLE
Postponing breaks until next inactivity period

### ISSUE THREAD

**Issue by unode** [slgobinath/SafeEyes#274]
When using SafeEyes I'm often interrupted while typing or actively using the mouse.
While breaks are desirable (or else I wouldn't be using SafeEyes :grinning:) it would be useful if the break would wait for a short inactivity period to be triggered.
 
There's the `Do Not Disturb` option but this is a all-or-nothing usecase.

What I'm after is an option that monitors keyboard/mouse activity and delays the break until a short (configurable) period of inactivity happens.
For instance with a `2` second setting the following would happen:

```
00:00 - Short break is due for 15 seconds from now
00:05 - Notification is shown: `Short break will happen in 10 seconds or the nearest inactivity period`
00:14 - Keyboard activity detected delaying break 2 seconds
00:15 - Keyboard activity detected delaying break 2 seconds
00:16 - Keyboard activity detected delaying break 2 seconds
00:17 - Keyboard activity detected delaying break 2 seconds
(keyboard activity stops)
00:19 - Triggering break
```

**Comment by unhammer** [comment]
That'd be great! I'm also annoyed when it happens right as I'm typing. There's `sudo apt install xprintidle` which will show idle-time (both mouse and keyboard), so the info's available. https://stackoverflow.com/questions/217157/how-can-i-determine-the-display-idle-time-from-python-in-windows-linux-and-mac?noredirect=1&lq=1 might also be relevant?

**Comment by unhammer** [comment]
Is this a duplicate of https://github.com/slgobinath/SafeEyes/issues/261 ?

**Comment by unode** [comment]
Seems like it, closing as duplicate of #261
