### ISSUE TITLE
Lock/screensaver button

### ISSUE THREAD

**Issue by unhammer** [slgobinath/SafeEyes#277]
I sometimes want to lock on short breaks too, or start a lock immediately in the long break (before the minimum N seconds have passed). Since super-L doesn't have an effect when SafeEyes is showing, it'd be nice if there were a button to Lock instead of Skip.

**Comment by slgobinath** [comment]
Added in https://github.com/slgobinath/SafeEyes/commit/5c54f501f64039bc6f1806258de607aeff185496

**Comment by slgobinath** [comment]
Included in 2.0.8
