### ISSUE TITLE
Feature Request: Interval between shortbreaks

### ISSUE THREAD

**Issue by anishmittal2020** [slgobinath/SafeEyes#279]
It might be more useful, if we could do `Every 15 minutes do a task from a specified set of tasks (like rolling eyes clockwise)` instead of `Interval between shortbreaks`. 

In this, I could add `Every 15 minutes 10 seconds do another task from another specified set of tasks (like rolling eyes anti-clockwise)`.  

For example:

| Relative Time | Task                           | Repeats after (minutes) |
| ------------- | ------------------------------ | ----------------------- |
| 0 min 0 s     | Software start                 | -                       |
| 15 min 0 s    | Roll eyes clockwise            | 60                      |
| 15 min 10 s   | Roll eyes counter clockwise    | 60                      |
| 15 min 20 s   | Blink eyes                     | 15                      |
| 30 min 0 s    | Stand up and stretch your back | 300                     |
| 30 min 10 s   | Do 5 squats                    | 450                     |
| 30 min 20 s   | Blink Eyes                     | 15                      |
| 45 min 0 s    | Stretch your shoulder blades   | 300                     |

**Comment by slgobinath** [comment]
Since adding custom time for each break replicates [Cron scheduler](https://en.wikipedia.org/wiki/Cron) and increases the complexity, a similar alternative is implemented. Now you can override the interval (time to break) of individual breaks.
