### ISSUE TITLE
Issues with next break time next to icon on KDE Plasma and Xfce

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#280]
Dear all, 

Can someone please quickly test with the next break time shows up next to the icon on KDE Plasma?

For me it does not using Plasma 5.13.4 on Fedora 28. 

Thank you!

![image](https://user-images.githubusercontent.com/170947/45851167-d4f84680-bd0f-11e8-8061-b07b61f7b902.png)

**Comment by orschiro** [comment]
Dear all, 

In fact, not only KDE Plasma is affected. I found the same for Xfce. 

Could someone please test this, too? 

I am wondering if this next break time only works on GNOME for now.

Yours

![image](https://user-images.githubusercontent.com/170947/45887583-72945a00-bd92-11e8-9953-d96009bd96df.png)

**Comment by slgobinath** [comment]
Hi,
Sorry for my late response. The API I am using to display the time in tray icon seems to work with only Gnome and Unity. I am using Cinnamon in which also I couldn't get this work.

Maybe we have to find an alternative.

**Comment by slgobinath** [comment]
Thanks, Happy New Year to you too!

**Comment by orschiro** [comment]
Thank you!!

**Comment by archisman-panigrahi** [comment]
Is this bug still relevant?

**Comment by orschiro** [comment]
No longer relevant. :)
