### ISSUE TITLE
Incorrect strings in textual descriptions for breaks

### ISSUE THREAD

**Issue by dbogdanov** [slgobinath/SafeEyes#282]
The messages that pop up during breaks do not contain readable strings. See an example in this screenshot.

![breaks](https://user-images.githubusercontent.com/409668/46352606-84abad80-c65a-11e8-8130-3cfb1657024d.png)

**Comment by slgobinath** [comment]
Hi,
Could you please manually reset the settings by following these steps and see the results?
1. Quit Safe Eyes
2. Remove the `~/.config/safeeyes` directory
3. Start Safe Eyes again.

**Comment by dbogdanov** [comment]
That solves the issue, thanks!
