### ISSUE TITLE
Feature request: 12-hour time support

### ISSUE THREAD

**Issue by anowlcalledjosh** [slgobinath/SafeEyes#284]
With the "show next break time in tray icon" feature enabled, or in the tray icon's menu, the time is shown with a 24-hour clock, but my system uses a 12-hour clock. Is it possible to make SafeEyes also display the time in 12-hour format?

**Comment by slgobinath** [comment]
Hi,
The Time format is taken from your locale settings. Could you please share the output of `locale` command in your terminal.

**Comment by anowlcalledjosh** [comment]
```console
$ locale
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Comment by slgobinath** [comment]
Hi,
Sorry for my late response. I have tested this issue just now on Ubuntu 18.04 and found that the UK Time format (`LC_TIME="en_GB.UTF-8"`) is 24 hours. Your calendar may have an option to show the time in AM/PM even though your locale format is different. If you want the time in AM/PM format, I recommend you to change the format to US.
![locale](https://user-images.githubusercontent.com/4003168/50569285-a850c380-0d2f-11e9-9c32-7d0649a62a93.png)
