### ISSUE TITLE
Add "Save" button to dialogs

### ISSUE THREAD

**Issue by dwilches** [slgobinath/SafeEyes#285]
I found this dialog non-intuitive:

![image](https://user-images.githubusercontent.com/3975401/46920914-c406c200-cfa9-11e8-8bbd-a79d747aba29.png)

Once I make my change the only option is to "Remove" the notification, not to save it. Later I found that closing the Window with the X button is what triggers the Save action.

Wouldn't it be good to have a Save button at the bottom instead? And to have the X button (and ESC keys) to exit without saving?

**Comment by slgobinath** [comment]
Hi,
I agree that having a Remove button in the place of Save button is confusing. I followed the Gnome guidelines in designing the Settings dialog. According to that, Save buttons are not preferred and the input fields should reflect the current status all the time (even a temporary value is not desired). All other dialogs in the Safe Eyes settings window follow the same guideline. Therefore, I have moved the remove button to the parent Settings window and left this dialog with no buttons.
![safe eyes remove break](https://user-images.githubusercontent.com/4003168/50569019-640ef480-0d2a-11e9-950f-9fcaaaa89485.png)
Above metioned changes are included in the commit: https://github.com/slgobinath/SafeEyes/commit/f1196bb1ea630a3c08512dd3ccb647694e5fe15d
