### ISSUE TITLE
xprintidle is not reliable on Wayland distributions

### ISSUE THREAD

**Issue by TPXP** [slgobinath/SafeEyes#286]
Hello !

I'm a happy SafeEyes user and I'm using it on my computer that uses wayland as a window manager. The app works great thanks to Xwayland, except `xprintidle`, which is used to determine system idle time, will only reset when interacting with a window running in Xwayland. It would be more reliable to use a wayland command to get the "real" system idle time.

Here is how to reproduce :
1. Run a Wayland desktop environment
2. Install `xprintidle`
3. Start the terminal
4. Type `watch xprintidle`. Move your mouse over the terminal (or over the desktop). If you're using a wayland terminal (like GNOME Terminal), the counter still increases. As you move over an X11 windows (Firefox for example - you can use [xeyes](https://medium.com/@bugaevc/how-to-easily-determine-if-an-app-runs-on-xwayland-or-on-wayland-natively-8191b506ab9a) to determine which apps run with Xwayland), the counter resets.

I think we'll need to adapt the "smart break" plugin to detect which display is in use (which is actually not that hard with the `DISPLAY` env variable) and call the appropriate CLI tool. This also needs some research to find out if there's an equivalent to `xprintidle` on Wayland. It looks like [solutions exist](https://dev.gajim.org/gajim/gajim/merge_requests/240?commit_id=2e5d966f1d715f20f112dd9370f6ccd13fcaeca9).

**Comment by filipkilibarda** [comment]
Currently experiencing this issue. Any progress here? Could look into it.

**Comment by slgobinath** [comment]
Thanks @filipkilibarda for the feature.
Currently without installing `xprintidle`, Smart Pause plugin cannot be used. With the PR sent by @filipkilibarda, `xprintidle` is not required with Wayland. I leave this issue open until I make it optional in Wayland.

**Comment by slgobinath** [comment]
@filipkilibarda I've made some changes in the master branch related to this feature. I would appreciate it if you can test it in your system.
The changes I made are:
1. Check if the system is using wayland at the beginning to avoid calling it every time
2. Fixed is_wayland function to work with non numeric session ids like `c1`, and `c2`

**Comment by filipkilibarda** [comment]
Appears to be working fine on my machine. Thanks :)

**Comment by TPXP** [comment]
Tried the latest git revision with those changes, it seems to work. Great job! :clap: 

I guess this issue can be closed :smiley:
