### ISSUE TITLE
feature request - Pomodoro Mode

### ISSUE THREAD

**Issue by leedoyle** [slgobinath/SafeEyes#292]
**Somewhat** related to https://github.com/slgobinath/SafeEyes/issues/279 
Pomodoro is a productivity technique for nearing deadlines, where you have 5 minutes breaks each 25 minutes, and after four short breaks you have a larger pause (15-30 minutes). 
Right now it's impossible as short breaks in SafeEyes cannot be set to longer than 1 minute. 

It would be nice to have such a mode one could only enable when needed, otherwise using the regular safeeyes configuration, or, alternatively, to be able to permanently specify longer short breaks.

**Comment by slgobinath** [comment]
Please note that with the recent PR, you can create short breaks with a maximum duration of 30 minutes and long breaks with a maximum duration of 60 minutes
