### ISSUE TITLE
manually forcing preemptive breaks

### ISSUE THREAD

**Issue by leedoyle** [slgobinath/SafeEyes#293]
Would be nice to have the possiblity of speeding up an incoming break when you must have one (or when you feel like it).

**Comment by slgobinath** [comment]
Hi,
Are looking for the `Take a break now` option in the tray icon (which is already there)?

**Comment by leedoyle** [comment]
Yes, thank you! How stupid of me :)

It would be cool to be able to force a **long** break, but that would complicate the UX.

**Comment by slgobinath** [comment]
> It would be cool to be able to force a long break, but that would complicate the UX.

You are right. Though we can have a submenu, I prefer to keep the design as simple as possible. Introducing a submenu will also require users to click twice in some systems like Elementary OS.
