### ISSUE TITLE
Media Plugin: Button images have disappeared

### ISSUE THREAD

**Issue by stdedos** [slgobinath/SafeEyes#296]
![screenshot 2019-01-22 10 30 24](https://user-images.githubusercontent.com/133706/51522048-fa699e00-1e30-11e9-9bca-3a64525b4d6d.png)

For Ubuntu 16.04.5, buttons are not "enough visible". Tooltips come, but no images. I just updated through `apt-get` (2.0.8)

_Originally posted by @stdedos in https://github.com/slgobinath/SafeEyes/pull/295#issuecomment-456313148_

**Comment by slgobinath** [comment]
Hi,
May I know the theme you are using?

**Comment by slgobinath** [comment]
I meant the GUI customization.

> I don't believe I have done anything "special" GUI-related

Then it is the default theme. As I mentioned earlier, I installed Ubuntu 16.04.5 (fresh installation) in VM and tried Safe Eyes 2.0.8 but it works as expected. I will try my best to figure it out.

**Comment by stdedos** [comment]
Any debug stuff are welcome.

Or how I can check what "theme" I have - I have no notion of the idea in any context related to Ubuntu/Unity/SafeEyes

**Comment by slgobinath** [comment]
You mean the action buttons displayed only on one screen?

**Comment by stdedos** [comment]
Yes

**Comment by slgobinath** [comment]
I am clueless and unable to simulate your environment (3 screens) with two monitors. Anyway, I will try my best to figure it out.

**Comment by slgobinath** [comment]
Hi,
Could you please test the fix committed to the https://github.com/slgobinath/SafeEyes/tree/fix-break-screen branch.
To test the code, please pull this branch and run from source code.

**Comment by slgobinath** [comment]
Also let me know if all your screens are blocked.

**Comment by stdedos** [comment]
Well, it works. Sort-of :stuck_out_tongue_closed_eyes: 
![screenshot 2019-02-04 14 36 59](https://user-images.githubusercontent.com/133706/52208795-81376580-288a-11e9-94a8-87451cddd878.png)

I guess it's apparent I have four (4) break windows (not 3), and the "background" of the buttons is changed.

```bash:~/.installs/SafeEyes$ (fix-break-screen u=) xrandr
Screen 0: minimum 8 x 8, current 5520 x 1080, maximum 16384 x 16384
DVI-I-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 connected primary 1680x1050+0+30 (normal left inverted right x axis y axis) 474mm x 296mm
   1680x1050     59.88*+  59.95  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
DP-0 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected 1920x1080+3600+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  59.94    50.00    60.05    60.00    50.04  
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1280x720      60.00    59.94    50.00  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       75.00    59.94    59.93  
DP-1 connected 1920x1080+1680+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+
   1600x900      60.00  
   1280x1024     75.02    60.02  
   1152x864      75.00  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  

```

Can you make the buttons a bit bigger? They are a bit cumbersome to "target" them in Full HD.

**Comment by slgobinath** [comment]
It's never going to end :(

> Can you make the buttons a bit bigger? They are a bit cumbersome to "target" them in Full HD.

Sure

Thank you for taking your time to test the code. I highly appreciate it.

**Comment by slgobinath** [comment]
Hi,
Could you please pull the last commit and check the icon size?

Thanks

**Comment by stdedos** [comment]
All seem good.

There was the issue in the first break that the left-most screen only didn't have a background, but, I couldn't replicate it regardless of trying many times.

It did appear that all my screens were blocked normally too.
We can merge if your tests are okay.

**Comment by stdedos** [comment]
> It's never going to end :(

You could add whatever log-file diagnostics, and I will post them back. If that would help :confused:
