### ISSUE TITLE
SafeEyes website fails with NoScript

### ISSUE THREAD

**Issue by wolftune** [slgobinath/SafeEyes#297]
http://slgobinath.github.io/SafeEyes/ is effectively a static site with text and images. It shouldn't require JavaScript in order to render any content.

**Comment by wolftune** [comment]
I don't know how the underlying technology works, but if you merely generate the static content on the server, it can be served as plain without requiring the browser to run client-side JS. I don't know why anyone uses a JavaScript framework to make static sites anyway, but it's obviously common enough now (I suppose just because people have a way of working).

Surely Angular has some function for fallback… upon quick searching, I'm not finding anything good. Leads me to have reduced respect for Angular.

Clearly the rendered HTML could just be put directly in an html file or something. This is obviously bigger than your little site. Anyway, I look forward to trying your software anyway, thanks for producing free/libre/open software.

**Comment by slgobinath** [comment]
Hi,

I agree that using Angular is not necessary for such a simple and static page but I close this issue as won't fix. I would appreciate it if anyone contributes the website but I focus more on the application than the website.
