### ISSUE TITLE
Settings button reset default settings

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#298]
@slgobinath how about a button in the settings menu to reset to default settings?

Potentially useful for people who have played around with the settings, messed them up and now want to revert to sane defaults. :-)

Cheers!

**Comment by orschiro** [comment]
Good one.

And for the future? Do you think it's a good idea? :)

orschiro@gmail.com

**Comment by slgobinath** [comment]
Of course, it is. I am just wondering where to put that button. As you may have noticed I stick with Gnome guidelines (though I am not a Gnome fan) and haven't provided a save or cancel button. Therefore, adding a reset button at the end will confuse the users and also breaks the aesthetic look.

Thanks

I think a Reset button or menu in the CSD title bar is an option (but it may/may not work in Ubuntu 14.04). Do you have any suggestion?

**Comment by slgobinath** [comment]
> Who is still using 14.04 anyway?

If we release a version without supporting Ubuntu 14.04, we'll know :-D

April 2019 is the end of date of Ubuntu 14.04. So you're right we don't need to care for Ubuntu 14.04. I will go with CSD title bar.

**Comment by orschiro** [comment]
>  I will go with CSD title bar.

Awesome! :-D

Cheers!

orschiro@gmail.com

**Comment by slgobinath** [comment]
This feature is introduced in a new branch: https://github.com/slgobinath/SafeEyes/tree/feature-new-settings-dialog. In addition, I also replaced tabs with Gtk Stack container.

with this feature, we are moving to Gtk 3.12 from 3.10

![screenshot from 2019-02-09 12-38-53](https://user-images.githubusercontent.com/4003168/52524309-9e44ad80-2c69-11e9-8052-4c10bbb134fe.png)

**Comment by slgobinath** [comment]
After testing this feature in other DEs, I will merge this feature into the master branch

**Comment by orschiro** [comment]
@slgobinath this is looking brilliant! Deserves quite some attention. Will ask the guys from OMG Ubuntu to feature it. 👍🙃

**Comment by slgobinath** [comment]
Released in 2.0.9
