### ISSUE TITLE
More standard python packaging

### ISSUE THREAD

**Issue by Yamakaky** [slgobinath/SafeEyes#3]
Example: https://github.com/jbernard/dotfiles

**Comment by slgobinath** [comment]
Thank you @Yamakaky for sharing this with me. I will update the packaging soon :-)

**Comment by radek-sprta** [comment]
Any word on the progress?

I was checking the requirements for Python packages in Debian the other day. One of them was that they have to use standard Python packaging and be installable as such. Thus, in its current shape, SafeEyes cannot be packaged for Debian and its derivatives, which is a shame I think.

I was recently packaging my own app for PyPI and Snap, so if you are too busy with other stuff, I could take a crack at it, while the memory is still fresh.

**Comment by slgobinath** [comment]
Hi @radek-sprta,
I would really appreciate if you can do that.

Thanks

**Comment by slgobinath** [comment]
Hi @radek-sprta,

Thanks for your PR. Are there any other changes to be done? If not, I will start working on the next release.

Regards,
Gobinath
