### ISSUE TITLE
2.0.8 without icon

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#300]
@slgobinath thanks for the 2.0.8 release! ❤

Maybe it's just me but with this version, the icon is no longer showing on the Xfce desktop.

![image](https://user-images.githubusercontent.com/170947/52461268-981dd680-2b6e-11e9-868f-3e9e99b265d5.png)

**Comment by slgobinath** [comment]
Hi,
How did you install it?

Please try the following command and restart Safe Eyes
```
sudo gtk-update-icon-cache /usr/share/icons/hicolor
```

**Comment by orschiro** [comment]
I followed the instructions for Fedora:

```
  sudo dnf install libappindicator-gtk3 python3-psutil
          sudo pip3 install safeeyes
          sudo gtk-update-icon-cache /usr/share/icons/hicolor
```

I ran your command again but the same issue remains.

Missing icon for the tray and also no icon in the applications menu.

Hmm...I will try to reinstall it and let you know.

-

**Comment by orschiro** [comment]
@slgobinath do you see any issues with the command-line output below?

```
  Successfully uninstalled safeeyes-2.0.8
[orschiro@x230 ~]$           sudo pip3 install safeeyes
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting safeeyes
  Using cached https://files.pythonhosted.org/packages/e4/c0/709e88d4d8850f28d4a1e5eebea8ea4054f95be842fbbe9ff8677a25fc5e/safeeyes-2.0.8-py3-none-any.whl
Requirement already satisfied: python-xlib in /usr/lib/python3.6/site-packages (from safeeyes)
Requirement already satisfied: psutil in /usr/lib64/python3.6/site-packages (from safeeyes)
Requirement already satisfied: babel in /usr/local/lib64/python3.6/site-packages (from safeeyes)
Requirement already satisfied: PyGObject in /usr/lib64/python3.6/site-packages (from safeeyes)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3.6/site-packages (from python-xlib->safeeyes)
Requirement already satisfied: pytz>=0a in /usr/lib/python3.6/site-packages (from babel->safeeyes)
Installing collected packages: safeeyes
Successfully installed safeeyes-2.0.8
```

**Comment by slgobinath** [comment]
Hi,
I tried this in my Fedora VM but couldn't reproduce this problem. It happens if the safeeys.png icon files are not installed or not detected by the system.

Please check the path `/usr/share/icons/hicolor/64x64/apps/safeeyes.png` for safeeyes.png. If it is not there, something wrong with your pip.

**Comment by orschiro** [comment]
I am glad it's not a bug but user error. I will close this and figure this out myself.

Thanks for your help thus far! ❤

**Comment by slgobinath** [comment]
Hi,

Do you have the file `/usr/share/icons/hicolor/64x64/apps/safeeyes.png`? If it is there, please try to restart your system. That may help though I am not sure.

I am afraid, did I sound rude? If so, please accept my apologies.

**Comment by orschiro** [comment]
@slgobinath no, you were not rude at all! I opened this bug report because I was concerned that others might be affected, too. Now we seem to know that it's more an issue on my side which I can live with. 

But regarding your question, no the file does not exist and restarting my machine didn't help either. 

```
[orschiro@x230 ~]$           sudo pip3 install safeeyes
[sudo] password for orschiro: 
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting safeeyes
  Using cached https://files.pythonhosted.org/packages/e4/c0/709e88d4d8850f28d4a1e5eebea8ea4054f95be842fbbe9ff8677a25fc5e/safeeyes-2.0.8-py3-none-any.whl
Requirement already satisfied: babel in /usr/local/lib64/python3.6/site-packages (from safeeyes)
Requirement already satisfied: PyGObject in /usr/lib64/python3.6/site-packages (from safeeyes)
Requirement already satisfied: python-xlib in /usr/lib/python3.6/site-packages (from safeeyes)
Requirement already satisfied: psutil in /usr/lib64/python3.6/site-packages (from safeeyes)
Requirement already satisfied: pytz>=0a in /usr/lib/python3.6/site-packages (from babel->safeeyes)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3.6/site-packages (from python-xlib->safeeyes)
Installing collected packages: safeeyes
Successfully installed safeeyes-2.0.8
[orschiro@x230 ~]$           sudo gtk-update-icon-cache /usr/share/icons/hicolor
[orschiro@x230 ~]$           sudo gtk-update-icon-cache /usr/share/icons/hicolor
[orschiro@x230 ~]$ gtk-update-icon-cache /usr/share/icons/hicolor
[orschiro@x230 ~]$ 
[orschiro@x230 ~]$ ls /usr/share/icons/hicolor/64x64/apps/safeeyes.png
ls: cannot access '/usr/share/icons/hicolor/64x64/apps/safeeyes.png': No such file or directory
[orschiro@x230 ~]$ 
```

**Comment by slgobinath** [comment]
Thanks.
Though I don't know the reason behind it, you can fix it by manually copying icons to the hicolor folder. Please execute these commands and let me know if it works:
```
# Clone the repo
git clone https://github.com/slgobinath/SafeEyes.git
# Goto the icons folder
cd SafeEyes/share/icons
# Copy all icons with their parent folder to the the hicolor folder
sudo cp -r hicolor/* /usr/share/icons/hicolor/
```

**Comment by orschiro** [comment]
@slgobinath this did fix the issue for the tray icon. Appreciated.

Interestingly, I also don't have a menu entry for Safe Eyes. Do you on your test machine?

![image](https://user-images.githubusercontent.com/170947/52531069-ec13f100-2d0f-11e9-8aab-ad673ff4b2cd.png)

**Comment by slgobinath** [comment]
Last time I tried on Fedora with Gnome and it worked. Today I've tried on Fedora 29 with XFCE and the bug affects me. Problem is pip installs other resources into the python package folder. I will fix this soon.

**Comment by orschiro** [comment]
Oh great! I should have mentioned I am on Xfce, too.

Sorry...

-

**Comment by slgobinath** [comment]
Hi,
You did mention that in the first comment but I didn't notice that. Now I have uploaded a new version 2.0.8.1. Could you please uninstall your current version and install the latest version using the following commands:

```
sudo pip3 uninstall safeeyes
sudo pip3 install -U safeeyes
```

**Comment by slgobinath** [comment]
It does affect Fedora with Gnome. I had the icons already in my Fedora with Gnome VM. That's why I wasn't affected by this issue.

The actual problem is uploading `.whl` Python package to PyPi which installs everything inside `python3.7/site-packages` directory. Now I've uploaded only the `tar.gz` package to PyPi which should fix the problem.

Please chec in your system and let me know. Thank you very much for letting me know this issue!

**Comment by orschiro** [comment]
2.0.8.1 fixed all the issues!

Thank you so much for addressing this. 👍🙃

-

**Comment by slgobinath** [comment]
Thanks for the confirmation :-)

Have a great day!

**Comment by orschiro** [comment]
> Have a great day!

And you a great week! 😋
