### ISSUE TITLE
Option to select on_pre and on_stop break sounds

### ISSUE THREAD

**Issue by kepi** [slgobinath/SafeEyes#302]
I started experimenting with SafeEyes yesterday, but I literally can't stand current *on_pre_break* sound. It may not be important issue to solve as I will get heart attack 10 seconds before next break ;)

First I tried to turn it off, but it looks like I can turn off both or none (and I still think it is great idea to have sound before). Having no sound after break may cause me to never open my tightly closed eyes again :)

It would be great to be able to select different sound from local disk (for both) as even if we found some better sound, it may not be suitable for others. To safe myself from horrrible fate I replaced wavs directly on disk for now with login/logout sound from libpurple.

Thanks for considering.

**Comment by slgobinath** [comment]
Hi @kepi,

Thank you for your suggestion. I will add another option in Audible Alert plugin to disable pre-break sound. I agree with you that the sounds are terrible especially the pre-break sound brings heart attack to me especially when the system volume is 100%.

I am looking for smooth and tiny sound clips which are free to use without any license violations.

In addition, Safe Eyes is highly configurable. You can use custom sound clips by placing a new file in the following path (You don't need to replace them in the system path):
```
~/.config/safeeyes/resource/on_pre_break.wav
~/.config/safeeyes/resource/on_stop_break.wav
```

**Comment by kepi** [comment]
> Thank you for your suggestion. I will add another option in Audible Alert plugin to disable pre-break sound. I agree with you that the sounds are terrible especially the pre-break sound brings heart attack to me especially when the system volume is 100%.

You are right with volume, maybe make volume configurable too?

> I am looking for smooth and tiny sound clips which are free to use without any license violations.

What licenses are ok? Is CC attribution ok?

> In addition, Safe Eyes is highly configurable. You can use custom sound clips by placing a new file in the following path (You don't need to replace them in the system path):
> 
> ```
> ~/.config/safeeyes/resource/on_pre_break.wav
> ~/.config/safeeyes/resource/on_stop_break.wav
> ```

Wow, thats truly amazing and completely sufficient for me. Didn't cross my mind it would be able this way. I'm not sure it GUI for this is needed, so I'm closing the issue.

Thanks!

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/SafeEyes/commit/79d96a793246f2970bd86cf082ee498b97a2faa6
