### ISSUE TITLE
Package Safe Eyes for openSUSE Tumbleweed

### ISSUE THREAD

**Issue by fleamour** [slgobinath/SafeEyes#303]
Is there any Flatpak, Snap or openSUSE specific way to install upcoming?

**Comment by slgobinath** [comment]
Hi,
So far there is no opnSUSE specific installation method. Please install using `pip`.

I would greatly appreciate it if anyone come up with a solution.

**Comment by embar-** [comment]
SafeEyes package now entered into openSUSE Factory, see https://build.opensuse.org/request/show/835684
Thus soon (maybe after few days) you will be able to install it directly from main openSUSE Tumbleweed repository.
You can close this issue as fixed.

**Comment by fleamour** [comment]
Thx.!

**Comment by embar-** [comment]
Link for download site: https://software.opensuse.org/package/safeeyes
