### ISSUE TITLE
why port TCP/7200 is opened to any foreign address?

### ISSUE THREAD

**Issue by crysman** [slgobinath/SafeEyes#304]
Hello, I've just noted this:
```
netstat --listen | grep 7200
tcp        0      0 localhost:7200          0.0.0.0:*               LISTEN
```
and
```
lsof -i :7200
COMMAND   PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
safeeyes 1167 myuser   12u  IPv4  70327      0t0  TCP localhost:7200 (LISTEN)
```

Shouldn't it be only for localhost (127.0.0.1)? I mean something like:
```
tcp        0      0 localhost:7200          127.0.0.1:*               LISTEN
```

**Comment by slgobinath** [comment]
Hi,
Safe Eyes depends on RPC protocol to send commands via command-line. The Safe Eyes RPC server is listening at port 7200. As per this Stack Exchange [answer](https://security.stackexchange.com/questions/51767/does-connection-that-use-0-0-0-0-in-foreign-address-secured) the Foreign Address `0.0.0.0:*` indicates that Safe Eyes RPC is not connected to any IPs.

Safe Eyes is running in your localhost so only the devices connected to the same network (eg: your home router) can access Safe Eyes which is very similar to other services running on your computer (for example MySQL server listen `localhost:3306`).

FYI:
You can change the port if you want by modifying the [rpc_port](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/safeeyes.json#L13) in `cat ~/.config/safeeyes/safeeyes.json`

The RPC server and client code are available at https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/rpc.py in case you want to ensure that Safe Eyes doesn't share anything with third parties.

**Comment by crysman** [comment]
Thank you for your answer.

According to this https://stackoverflow.com/a/2135631/2878211 it depends whether the used function `SimpleXMLRPCServer` does **bind** to localhost or not (??)

**Comment by slgobinath** [comment]
Hi,

It does bind to localhost. Please check this code snippet extracted from the `TCPServer` class which is extended by the `SimpleXMLRPCServer`:

```python
class TCPServer(BaseServer):
    def __init__(self, server_address, RequestHandlerClass, bind_and_activate=True):
        """Constructor.  May be extended, do not override."""
        BaseServer.__init__(self, server_address, RequestHandlerClass)
        self.socket = socket.socket(self.address_family,
                                    self.socket_type)
        if bind_and_activate:
            try:
                self.server_bind()
                self.server_activate()
            except:
                self.server_close()
                raise

    def server_bind(self):
        """Called by constructor to bind the socket.

        May be overridden.

        """
        if self.allow_reuse_address:
            self.socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self.socket.bind(self.server_address)
        self.server_address = self.socket.getsockname()
```

```python
class SimpleXMLRPCServer(socketserver.TCPServer,
                         SimpleXMLRPCDispatcher):
    allow_reuse_address = True
    _send_traceback_header = False

    def __init__(self, addr, requestHandler=SimpleXMLRPCRequestHandler,
                 logRequests=True, allow_none=False, encoding=None,
                 bind_and_activate=True, use_builtin_types=False):
        self.logRequests = logRequests

        SimpleXMLRPCDispatcher.__init__(self, allow_none, encoding, use_builtin_types)
        socketserver.TCPServer.__init__(self, addr, requestHandler, bind_and_activate)
```

**Comment by slgobinath** [comment]
Closing this issue as the problem is been already addressed in the library.

**Comment by slgobinath** [comment]
Since there are some worried about using RPC server, an option to disable RPC server is added with https://github.com/slgobinath/SafeEyes/commit/020dea888c88940d4883168e2bb0023ea50ead48
However please note that disabling RPC server may affect some command-line commands. Especially if you are using Safe Eyes without the tray icon, it is not advisable to disable the RPC server.

Suppose if you disabled RPC accidentally without tray icon, kill `safeeyes`, reset the configuration by removing the safe eyes configuration `rm -rf ~/.config/safeeyes/`, and start Safe Eyes again.

**Comment by anvilvapre** [comment]
Good that you can disable the RPC service. 

The service binds to the ip address 0.0.0.0 meaning the service will bind to the ip addreseses on all network interfaces on the host. This makes the RPC the service accessible from remote hosts. This may offer a security risk.

Why not just bind to localhost rather i.e. pass 127.0.0.1 or localhost as hostname. The documentation has an example `https://docs.python.org/3/library/xmlrpc.server.html`.
