### ISSUE TITLE
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified

### ISSUE THREAD

**Issue by abroresonaliyev** [slgobinath/SafeEyes#308]
Please help me. I can't install safeeyes in debian 9.

Requirement already satisfied: safeeyes in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: psutil in /usr/local/lib/python3.5/dist-packages (from safeeyes)
Requirement already satisfied: python-xlib in /usr/local/lib/python3.5/dist-packages (from safeeyes)
Requirement already satisfied: babel in /usr/local/lib/python3.5/dist-packages (from safeeyes)
Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (from safeeyes)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from python-xlib->safeeyes)
Requirement already satisfied: pytz>=0a in /usr/local/lib/python3.5/dist-packages (from babel->safeeyes)

**Comment by slgobinath** [comment]
Hi,

Could you please provide the entire output of `sudo pip3 install safeeyes`?

**Comment by abroresonaliyev** [comment]
![image](https://user-images.githubusercontent.com/11418702/54993163-0ca7ba00-4fe3-11e9-820c-601a0bd6472a.png)


kebrorba@kebrorba-hp:~$ sudo pip3 install safeeyes

Requirement already satisfied: safeeyes in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: python-xlib in /usr/local/lib/python3.5/dist-packages (from safeeyes)
Requirement already satisfied: babel in /usr/local/lib/python3.5/dist-packages (from safeeyes)
Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (from safeeyes)
Requirement already satisfied: psutil in /usr/local/lib/python3.5/dist-packages (from safeeyes)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from python-xlib->safeeyes)
Requirement already satisfied: pytz>=0a in /usr/local/lib/python3.5/dist-packages (from babel->safeeyes)

kebrorba@kebrorba-hp:~$

**Comment by abroresonaliyev** [comment]
> Hi,
> 
> Could you please provide the entire output of `sudo pip3 install safeeyes`?


kebrorba@kebrorba-hp:~$ sudo pip3 install safeeyes

Requirement already satisfied: safeeyes in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: python-xlib in /usr/local/lib/python3.5/dist-packages (from safeeyes)
Requirement already satisfied: babel in /usr/local/lib/python3.5/dist-packages (from safeeyes)
Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (from safeeyes)
Requirement already satisfied: psutil in /usr/local/lib/python3.5/dist-packages (from safeeyes)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from python-xlib->safeeyes)
Requirement already satisfied: pytz>=0a in /usr/local/lib/python3.5/dist-packages (from babel->safeeyes)

kebrorba@kebrorba-hp:~$

![image](https://user-images.githubusercontent.com/11418702/54993335-6314f880-4fe3-11e9-857c-1805e26b0662.png)

**Comment by slgobinath** [comment]
Hi,

After installing Safe Eyes, what happens when you run `safeeyes` from the terminal?

**Comment by abroresonaliyev** [comment]
> Hi,
> 
> After installing Safe Eyes, what happens when you run `safeeyes` from the terminal?

![image](https://user-images.githubusercontent.com/11418702/55050521-f5181200-5072-11e9-9a2d-ca9d22cd5891.png)


kebrorba@kebrorba-hp:~$ sudo safeeyes
Traceback (most recent call last):
  File "/usr/local/bin/safeeyes", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/safeeyes/__main__.py", line 141, in main
    safeeyes = SafeEyes(system_locale, config)
  File "/usr/local/lib/python3.5/dist-packages/safeeyes/SafeEyes.py", line 77, in __init__
    self.break_screen = BreakScreen(self.context, self.on_skipped, self.on_postponed, Utility.STYLE_SHEET_PATH)
  File "/usr/local/lib/python3.5/dist-packages/safeeyes/BreakScreen.py", line 47, in __init__
    self.display = Display()
  File "/usr/local/lib/python3.5/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python3.5/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python3.5/dist-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'No protocol specified\n'

**Comment by slgobinath** [comment]
Hi,

This is an issue in Xlib. Please try this in the terminal:

```
xhost +
safeeyes
```

**Comment by h5rdly** [comment]
I 'm running OpenSUSE Tumbleweed, encountered the following - 
- The tumbleweed package tries to install py38 stuff  - eg `python38-cairo`. 
- `pip install safeeyes` tries to install pycairo as well and also fails - 
   `ERROR: Could not build wheels for pycairo which use PEP 517 and cannot be installed directly`
- I found `python39-cairo` in yast which solved the issue, leading me to the error that's described here :)

I think maybe the tumbleweed package needs to be updated to install the respective python39 supporting libraries?
