### ISSUE TITLE
timer on/off

### ISSUE THREAD

**Issue by SmilePlz** [slgobinath/SafeEyes#309]
how to change the standard timer off time in 5 seconds? when I read books my timer does not work as I expect.

**Comment by slgobinath** [comment]
Hi,
You mean the idle time to pause Safe Eyes right?
Please go to settings --> Plugins and click on the settings dialog of `Smart Pause` plugin. In the appeared dialog, increase the time to 5.

**Comment by SmilePlz** [comment]
Yes thanks a lot. This is exactly what I needed.
