### ISSUE TITLE
Starts exercises from beginning after Hibernate/Sleep

### ISSUE THREAD

**Issue by arsinux** [slgobinath/SafeEyes#31]
Instead of continuing exercises from where it was left, it starts from beginning. This way it shows the first messages more than the messages at the end of the list in en.json

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/8fda2233168aa0bfa579a94973743930d3e661d7 and included in Safe Eyes v1.1.2
