### ISSUE TITLE
Scheduler works unclear

### ISSUE THREAD

**Issue by vlad-timofeev** [slgobinath/SafeEyes#314]
Discovered this awesome program a few days ago. Works great, the only thing I cannot figure out is how the short/long break scheduling works. Given this configuration:
![image](https://user-images.githubusercontent.com/11474041/56093514-e4312280-5ef3-11e9-9812-83cfb7eac384.png)
I expect it to behave like this in loop:

0. The program is launched
1. 8 minutes go without interruptions
2. 1 minute break
3. 8 minutes go without interruptions
4. 1 minute break
5. 8 minutes go without interruptions
6. 5 minutes break
7. Go to step 1

But right after step 7 the program gives 24 minutes without interruptions instead of 8.
Why does it behave this way?
Is it possible to make it work just like I expect?

**Comment by slgobinath** [comment]
Hi,
Your expectation is correct. If this is the actual behavior, it should a bug. I am testing the program now to reproduce it. Meanwhile could you please check the log by running Safe Eyes in debug mode using the following command and share the log with me:

```
safeeyes --debug
```

Thanks & Regards,
Gobinath

**Comment by vlad-timofeev** [comment]
Hi Gobinath,
Sure, I started it at 2019-04-14.20:50:56 and waited the necessary time to generate the log:
[safeeyes.log](https://github.com/slgobinath/SafeEyes/files/3077448/safeeyes.log)

**Comment by vlad-timofeev** [comment]
Works as expected after reinstalling and removing configuration directory.

**Comment by slgobinath** [comment]
Thanks for the confirmation. I was unable to reproduce this issue but I couldn't.
