### ISSUE TITLE
Allow enabling postponing while disabling skipping

### ISSUE THREAD

**Issue by 12people** [slgobinath/SafeEyes#316]
I'd really like to be able to postpone breaks when I'm in the flow, working on something, and really need a bit of time to finish, but would like to disable skipping for myself, as I often find myself habitually skipping without giving it much thought.

Would you consider allowing postponing breaks with "strict break" enabled?

**Comment by andrewjong** [comment]
I believe the relevant line of code would be [here](https://github.com/slgobinath/SafeEyes/blob/f05bb53f250acb3b4a657161f3f49fc17e82b957/safeeyes/settings.py#L109).

```self.switch_postpone.set_active(config.get('allow_postpone') and not config.get('strict_break'))```

Should be as simple as removing everything at and after the `and` statement. Just change it to this:
```self.switch_postpone.set_active(config.get('allow_postpone'))```

I don't have time yet to test this, however. Maybe someone can submit a pull request.
