### ISSUE TITLE
Make skipping harder

### ISSUE THREAD

**Issue by 12people** [slgobinath/SafeEyes#320]
In using SafeEyes for a while, I reflexively hit the "Skip" button without thinking about it. I'd really appreciate a harder way to skip a break, to allow my conscious brain to catch up to my reflexes.

I'm thinking either a) hiding the "Skip" button under a menu (so that it's two clicks), or b) forcing me to type a random word or number in order to skip a break.

**Comment by slgobinath** [comment]
Hi,
Do you want to still skip but through a complex process or do not want to skip at all? If the purpose of this feature is the second one, there is a `strict mode` option in Safe Eyes.

**Comment by 12people** [comment]
@slgobinath The former -- still skip through a more complex process.

I tried strict mode and it works well some of the time, but sometimes, I really need to e.g. finish a message or send something on time, and then it's a huge hindrance.

**Comment by slgobinath** [comment]
Thank you for the clarification. I marked this as a new feature.

**Comment by martnnw** [comment]
Maybe add an option to unlock with a password or solve a math problem

**Comment by tuhlaajapoika** [comment]
This program really helps me with my attention decifit disorder. I usually keep 'skip' and 'postpone' disabled. If I enable either of them for longer period of time, I end up postponing/skipping multiple times in a row without taking a single break.

It would be great to have a counter which limits the number of postponements until forcing me to take a break. Not sure how difficult it would be to implement.

Thank you for your work!

**Comment by StevePires** [comment]
Having the same "issue" (not the app's fault of course!).
I was thinking of something more like the button can't be clicked before a 3s (configurable?) timer, or click for 3s to actually perform the skip (feasible?), or when user points on skip button it moves somewhere else (randomly?) so you have to go there to actually click it :)

**Comment by archisman-panigrahi** [comment]
https://github.com/slgobinath/SafeEyes/pull/526 has fixed this
