### ISSUE TITLE
Allow applying the Pomodoro technique

### ISSUE THREAD

**Issue by 12people** [slgobinath/SafeEyes#321]
Although I've used SafeEyes for eye strain so far, I've been experimenting with using it to apply the Pomodoro technique recently, with 5 minute breaks every 25 minutes.

The problem is, SafeEyes only allows short breaks to last up to 1 minute and doesn't allow long breaks without short breaks in between. Currently, I'm using 1-second short breaks every 12 mins and 5-minute long breaks every 24 mins, but it's an ugly workaround.

I'd really appreciate being able to use just one type of break to be able to apply the Pomodoro technique. If short breaks went up to 5 mins and long breaks could be disabled, that would work for me.

**Comment by slgobinath** [comment]
Hi,
What about deleting all short breaks and using long breaks as shown below?
![image](https://user-images.githubusercontent.com/4003168/58553028-d1438a80-81e1-11e9-8b61-af9bad219a49.png)

**Comment by 12people** [comment]
@slgobinath How do I disable all short breaks?

**Comment by slgobinath** [comment]
Just delete all the short breaks from Breaks section
![image](https://user-images.githubusercontent.com/4003168/58553226-6181cf80-81e2-11e9-8bea-8d6b93d36b72.png)

**Comment by 12people** [comment]
@slgobinath Thanks for the tip. I thought the "Breaks" section was only about the messages shown.

**Comment by slgobinath** [comment]
You're welcome.
You can also customize individual breaks if you want. Click on the settings button next to each break and you will see some additional options to define break specific settings.

I'm closing this issue as resolved.

**Comment by slgobinath** [comment]
You can also change the break message and add new breaks  (may be useful if you are using it for Promodoro).

**Comment by 12people** [comment]
@slgobinath I've tried this solution and it doesn't work. Instead, I only get short breaks, even though all my short breaks are deleted.
