### ISSUE TITLE
Deleting short breaks to get long breaks does not work

### ISSUE THREAD

**Issue by 12people** [slgobinath/SafeEyes#323]
When I delete all of my short breaks, long breaks appear for the duration of a short break time for me.

Using v 2.0.6-1 from the ubuntu-disco repository.

**Comment by slgobinath** [comment]
Hi
Can you try the latest Safe Eyes version 2.0.9?

**Comment by 12people** [comment]
@slgobinath That would mean compiling from source, right?

Right now, I'm studying for finals, so the soonest I'll be able to devote time to that is in two or three weeks.

**Comment by slgobinath** [comment]
It should be available in the PPA.
Please try `sudo apt update` and `sudo apt install safeeyes`.

**Comment by 12people** [comment]
Great, thanks, seems to work! :)

**Comment by 12people** [comment]
(BTW, the headerbar now has the title in it and it looks altogether unseemly. Is that a bug?)

![Screenshot from 2019-05-30 17-21-24](https://user-images.githubusercontent.com/7361228/58643402-7b650480-82ff-11e9-8fd0-f8074754f2ad.png)

**Comment by slgobinath** [comment]
Hi,
Settings dialog does have the `Safe Eyes` title by desgin.
