### ISSUE TITLE
[BUG] Screen time increases even if the computer is suspended

### ISSUE THREAD

**Issue by Miguel-Dorta** [slgobinath/SafeEyes#328]
The screen time stat will increase even if your computer is suspended.

OS: Manjaro
Linux kernel: 5.1.8
Desktop environment: Budgie 10.5
CPU: Intel i7 6550U

**Comment by gitchhiker** [comment]
Same for me using SE 2.0.9 on Ubuntu 20.04:
Turning on the computer from suspend gives an instant SafeEyes alert, and a break after the 20 seconds I set.
Would also be interested in this one :slightly_smiling_face:

**Comment by AdamPS** [comment]
4 years later and I believe this has gradually been fixed. The recent fix for #551 makes further improvements.
