### ISSUE TITLE
Add an alert/sound after break

### ISSUE THREAD

**Issue by TunableRoom9** [slgobinath/SafeEyes#33]
SafeEyes works really well in my computer. However, (and this might sound stupid) when there's break that involves closing my eyes I'd like to be notified when it finishes.

**Comment by slgobinath** [comment]
I also have that idea. These days I am little busy, will add the feature as soon as possible.

**Comment by orschiro** [comment]
Thanks for considering this! 

Indeed, when you are asked to tightly close your eyes, it would be helpful to know when you can open them again. :-)

-R

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/SafeEyes/commit/d1f9042ac7b12ab27fb2940c3d829c733db5904c. Will be included in the next version.

**Comment by orschiro** [comment]
@slgobinath,

This is fantastic! Do you already know when you will release the next .deb package?

Yours,

Robert

**Comment by slgobinath** [comment]
Hi @orschiro,
I don't have a specific date. Now I am testing the issue 26. Once developer testing is completed, I will release the new deb. Since that feature includes a new thread, I need to test it thoroughly. I hope I can release it within 2-3 days.

**Comment by slgobinath** [comment]
This feature has been included in Safe Eyes [v1.1.3](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.3)

**Comment by orschiro** [comment]
Cool, thanks so much for the release! :-)

**Comment by slgobinath** [comment]
@orschiro,

Sorry I just found a minor bug. Please wait until I release the next version. I am releasing it now.

**Comment by slgobinath** [comment]
Sorry for the inconvenience. Now you can use the Safe Eyes [v1.1.4](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.4) which includes this feature.
