### ISSUE TITLE
"Disable SafeEyes" Option Doesn't Show Up

### ISSUE THREAD

**Issue by luckydays** [slgobinath/SafeEyes#330]
Hi guys.

Awesome tool. Thank you all for supporting its development!
With it, I finally started making breaks more often and the very eyes exercise already gives results.

I want to disable the app temporary while having a call, but somehow in the wingpanel this option doesn't show up, it's empty.

Please see the GIF evidence:
![SafeEyes - Disabling issue](https://user-images.githubusercontent.com/10942891/60505355-da81b480-9cc3-11e9-9b16-9db09e2a3f5e.gif)

I'm on Elementary OS 5.0 Juno

What could you advise?

**Comment by slgobinath** [comment]
@luckydays please give me some time to test it on Elementary OS.

**Comment by luckydays** [comment]
@slgobinath Sure. Thank you.

**Comment by slgobinath** [comment]
Hi,
What's your Safe Eyes version? I found Safe Eyes 2.0.0 available in the App Center but the latest version is 2.0.9 which can be installed from my PPA. Also I wonder how you enabled tray icons because I couldn't in my VM. I tried this answer https://elementaryos.stackexchange.com/a/17453 but no luck.

**Comment by luckydays** [comment]
Hi! Thanks for getting back to this.

Actually, I've deleted 2.0.0 which was installed through the App Center before and re-installed 2.0.9 from your PPA. Unfortunately, the issue is still there.

Regarding tray icons - it was quite some time ago, but I guess I used this tweak with the `indicator-application` - https://www.linuxuprising.com/2018/08/how-to-re-enable-ayatana-appindicators.html

Let me know please how it went.
@slgobinath

**Comment by luckydays** [comment]
@slgobinath Hi.

Could you tell, please - do you probably have any updates in this regards?

**Comment by slgobinath** [comment]
Hi @luckydays 
Sorry I was busy with my work and couldn't focus on this project for a long time. I am able to reproduce this bug in my VM but couldn't solve it yet. The disabled menu options are added as sub menus. Do you have any other applications with similar sub menu feature that is working properly?

**Comment by luckydays** [comment]
Hi @slgobinath 

Thank you for getting back to me regarding this. Really appreciate it!

> Do you have any other applications with similar sub menu feature that is working properly?

Some of them - yes, some - no. For instance, [Nextcloud client](https://nextcloud.com/install/) does show the sub-menu items. However, the [Upwork Desktop Tracker App](https://support.upwork.com/hc/en-us/articles/211064088-Install-the-Desktop-App) - doesn't show it.

**Comment by archisman-panigrahi** [comment]
This seems to have been fixed (version 2.2.2). If you can reproduce, please reopen the issue.
