### ISSUE TITLE
GDK fail

### ISSUE THREAD

**Issue by Berkmann18** [slgobinath/SafeEyes#331]
Whenever I try to run `safeeyes` on ArchLinux (linux 5.1.16-arch1-1-ARCH) with awesomewm.

I get this:
```shell
(safeeyes:31014): Gdk-CRITICAL **: 21:28:07.388: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

Not sure what I'm missing.

**Comment by slgobinath** [comment]
@Berkmann18 I do get it in my LM machine. I think it's mostly because of the GTK theme though I am not sure.

**Comment by Berkmann18** [comment]
@slgobinath Perhaps, what GTK theme do you have?
I have Adwaita GTK2/3 (for now).

**Comment by slgobinath** [comment]
I'm using my [custom theme](https://github.com/slgobinath/linux-mint-themes/tree/master/themes) which I forked from another theme which I don't remember. I've observed this behavior in some of my VMs too like Manjaro. However, I didn't get this warning on Fedora with Gnome (default theme) when I tested Safe Eyes yesterday.

**Comment by AndresMpa** [comment]
Hey, I have the same issue on my OS with safeeyes 2.1.3

OS: Arch Linux
WM: Qtile (0.20.0)
Kernel: 5.16.10-zen1-1-zen


I found this also: https://bugs.launchpad.net/ubuntu/+source/caffeine/+bug/1879518

**Comment by PMunch** [comment]
I'm getting the same issue, also running Arch but with i3.

**Comment by archisman-panigrahi** [comment]
> I'm getting the same issue, also running Arch but with i3.

Can you please try the latest master branch? 
```
yay -S safeeyes-git
```

**Comment by PMunch** [comment]
Just tried it, showed me an error message about missing a dependency. I installed snixembed and ran `snixembed --fork`. After restarting safeeyes the error popu is gone but I get:

```
/org/ayatana/NotificationItem/io_github_slgobinath_SafeEyes appeared
/org/ayatana/NotificationItem/io_github_slgobinath_SafeEyes is not a service name, falling back to appindicator on :1.38
:1.38 set menu: /io/github/slgobinath/SafeEyes/Menu

(snixembed:27244): Gdk-CRITICAL **: 08:25:26.161: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

Note that the whole time the application runs fine and the tray icon has always appeared.

**Comment by archisman-panigrahi** [comment]
If it runs fine after installing snixembed, all good.

Also please add your feedback in #617

**Comment by PMunch** [comment]
I think you misunderstood. It worked without the latest version of snixembed as well. In fact I've since gone back to using the latest stable version and it works wonderfully.
