### ISSUE TITLE
Settings window is not showing

### ISSUE THREAD

**Issue by bytefather** [slgobinath/SafeEyes#333]
Hi, 
Like in title, settings window is not showing at all for Safe Eyes v 2.0.9.
I'm using Linux Mint Debian edition 2 Betsy ( 3.16.0-6-amd64 #1 SMP Debian 3.16.56-1+deb8u1 (2018-05-08) x86_64 GNU/Linux) (Jessie). 
If you have question about dependencies then please ask. Most of them are updated to the newest versions.
The error:
> $ safeeyes -s
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/safeeyes/SafeEyes.py", line 123, in show_settings
> 	self.config.clone(), self.save_settings)
>   File "/usr/lib/python3/dist-packages/safeeyes/settings.py", line 56, in __init__
> 	builder = Utility.create_gtk_builder(SETTINGS_DIALOG_GLADE)
>   File "/usr/lib/python3/dist-packages/safeeyes/Utility.py", line 506, in create_gtk_builder
> 	builder.add_from_file(glade_file)
> GLib.Error: gtk-builder-error-quark: Invalid property: GtkStack.interpolate_size on line 172 (11)

PS. It would be very nice to have ability to set settings from cli and/or file.

**Comment by slgobinath** [comment]
Hi what is the GTK version in your system?

**Comment by waldekworking** [comment]
Hi Slgobinath, 
Thanks for response. 
My GTK versions:

> ||/ Name                                           Version                      Architecture                 Description
> ii  libgtk-3-0:amd64                               3.14.5+4                     amd64                        GTK+ graphical user interface library
> ii  libgtk2.0-0:amd64                              2.24.25-3+deb8u2             amd64                        GTK+ graphical user interface library
> 
And everything that is installed and associated with GTK:

> ii  gir1.2-gtk-2.0                     2.24.25-3+deb8u2  amd64        GTK+ graphical user interface library -- gir bindings
> ii  gir1.2-gtk-3.0:amd64               3.14.5+4          amd64        GTK+ graphical user interface library -- gir bindings
> ii  gir1.2-gtksource-3.0:amd64         3.14.1-1          amd64        gir files for the GTK+ syntax highlighting widget
> ii  gir1.2-javascriptcoregtk-3.0:amd64 2.4.9-1-deb8u1    amd64        JavaScript engine library from WebKitGTK+ - GObject introspection data
> ii  gtk-recordmydesktop                0.3.8-4.1         all          Graphical frontend for recordMyDesktop screencast tool
> ii  gtk2-engines:amd64                 1:2.20.2-3        amd64        theme engines for GTK+ 2.x
> ii  gtk2-engines-murrine:amd64         0.98.1.1-5        amd64        cairo-based gtk+-2.0 theme engine
> ii  gtk2-engines-pixbuf:amd64          2.24.25-3+deb8u2  amd64        pixbuf-based theme for GTK+ 2.x
> ii  libcanberra-gtk0:amd64             0.30-2.1          amd64        GTK+ helper for playing widget event sounds with libcanberra
> ii  libcanberra-gtk3-0:amd64           0.30-2.1          amd64        GTK+ 3.0 helper for playing widget event sounds with libcanberra
> ii  libcanberra-gtk3-module:amd64      0.30-2.1          amd64        translates GTK3 widgets signals to event sounds
> ii  libclutter-gtk-1.0-0:amd64         1.6.0-1           amd64        Open GL based interactive canvas library GTK+ widget
> ii  libdbusmenu-gtk3-4:amd64           12.10.2-1         amd64        library for passing menus over DBus - GTK+ version
> ii  libgtk-3-0:amd64                   3.14.5+4          amd64        GTK+ graphical user interface library
> ii  libgtk-3-bin                       3.14.5+4          amd64        programs for the GTK+ graphical user interface library
> ii  libgtk-3-common                    3.14.5+4          all          common files for the GTK+ graphical user interface library
> ii  libgtk-sharp-beans-cil             2.14.1-3          all          Supplementary CLI bindings for GTK 2.14+
> ii  libgtk2-perl                       2:1.2492-4        amd64        Perl interface to the 2.x series of the Gimp Toolkit library
> ii  libgtk2.0-0:amd64                  2.24.25-3+deb8u2  amd64        GTK+ graphical user interface library
> ii  libgtk2.0-bin                      2.24.25-3+deb8u2  amd64        programs for the GTK+ graphical user interface library
> ii  libgtk2.0-cil                      2.12.10-5.1       amd64        CLI binding for the GTK+ toolkit 2.12
> ii  libgtk2.0-common                   2.24.25-3+deb8u2  all          common files for the GTK+ graphical user interface library
> ii  libgtkglext1                       1.2.0-3.2         amd64        OpenGL Extension to GTK+ (shared libraries)
> ii  libgtkmm-2.4-1c2a:amd64            1:2.24.4-1.1      amd64        C++ wrappers for GTK+ (shared libraries)
> ii  libgtkmm-3.0-1:amd64               3.14.0-1          amd64        C++ wrappers for GTK+ (shared libraries)
> ii  libgtksourceview-3.0-1:amd64       3.14.1-1          amd64        shared libraries for the GTK+ syntax highlighting widget
> ii  libgtksourceview-3.0-common        3.14.1-1          all          common files for the GTK+ syntax highlighting widget
> ii  libgtksourceview2.0-0              2.10.5-2          amd64        shared libraries for the GTK+ syntax highlighting widget
> ii  libgtksourceview2.0-common         2.10.5-2          all          common files for the GTK+ syntax highlighting widget
> ii  libgtkspell0                       2.0.16-1.1        amd64        a spell-checking addon for GTK's TextView widget
> ii  libindicate-gtk3                   0.6.92-2+deb8u1   amd64        library for raising indicators via DBus - GTK+ bindings
> ii  libjavascriptcoregtk-1.0-0:amd64   2.4.9-1-deb8u1    amd64        JavaScript engine library from WebKitGTK+
> ii  libjavascriptcoregtk-3.0-0:amd64   2.4.9-1-deb8u1    amd64        JavaScript engine library from WebKitGTK+
> ii  libjavascriptcoregtk-4.0-18:amd64  2.6.2+dfsg1-4     amd64        JavaScript engine library from WebKitGTK+
> ii  libnm-gtk-common                   0.9.10.0-2        all          library for wireless and mobile dialogs - common files
> ii  libnm-gtk0:amd64                   0.9.10.0-2        amd64        library for wireless and mobile dialogs
> ii  libpolkit-gtk-mate-1-0:amd64       1.18.2-1+betsy    amd64        MATE authentication agent for PolicyKit-1 (library)
> ii  libreoffice-gtk                    1:4.3.3-2+deb8u11 amd64        office productivity suite -- GTK+ integration
> ii  libwebkit2gtk-3.0-25:amd64         2.4.9-1-deb8u1    amd64        WebKit2 API layer for WebKitGTK+
> ii  libwebkit2gtk-4.0-37:amd64         2.6.2+dfsg1-4     amd64        Web content engine library for GTK+
> ii  libwebkitgtk-1.0-0:amd64           2.4.9-1-deb8u1    amd64        Web content engine library for GTK+
> ii  libwebkitgtk-1.0-common            2.4.9-1-deb8u1    all          Web content engine library for GTK+ - data files
> ii  libwebkitgtk-3.0-0:amd64           2.4.9-1-deb8u1    amd64        Web content engine library for GTK+
> ii  libwebkitgtk-3.0-common            2.4.9-1-deb8u1    all          Web content engine library for GTK+ - data files
> ii  libwxgtk3.0-0:amd64                3.0.2-1+b1        amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+ runtime)
> ii  mint-themes-gtk3                   3.14+13           all          Mint themes for GTK3
> ii  pinentry-gtk2                      0.8.3-2           amd64        GTK+-2-based PIN or pass-phrase entry dialog for GnuPG
> ii  python-aptdaemon.gtk3widgets       1.1.1-4+deb8u1    all          Python 2 GTK+ 3 widgets to run an aptdaemon client
> ii  python-gtk2                        2.24.0-4          amd64        Python bindings for the GTK+ widget set
> ii  python-gtksourceview2              2.10.1-2          amd64        Python bindings for the GtkSourceView widget
> ii  python3-aptdaemon.gtk3widgets      1.1.1-4+deb8u1    all          Python 3 GTK+ 3 widgets to run an aptdaemon client
> ii  transmission-gtk                   2.84-0.2+deb8u1   amd64        lightweight BitTorrent client (GTK+ interface)
> ii  xdg-user-dirs-gtk                  0.10-1            amd64        tool to manage well known user directories (Gtk extension)
> 
PS. I must add that, for example, "about" window is opening properly.

**Comment by bytefather** [comment]
Hi Slgobinath, 
Thanks for response. 
My GTK versions:

> ||/ Name                                           Version                      Architecture                 Description
> ii  libgtk-3-0:amd64                               3.14.5+4                     amd64                        GTK+ graphical user interface library
> ii  libgtk2.0-0:amd64                              2.24.25-3+deb8u2             amd64                        GTK+ graphical user interface library
> 
And everything that is installed and associated with GTK:

> ii  gir1.2-gtk-2.0                     2.24.25-3+deb8u2  amd64        GTK+ graphical user interface library -- gir bindings
> ii  gir1.2-gtk-3.0:amd64               3.14.5+4          amd64        GTK+ graphical user interface library -- gir bindings
> ii  gir1.2-gtksource-3.0:amd64         3.14.1-1          amd64        gir files for the GTK+ syntax highlighting widget
> ii  gir1.2-javascriptcoregtk-3.0:amd64 2.4.9-1-deb8u1    amd64        JavaScript engine library from WebKitGTK+ - GObject introspection data
> ii  gtk-recordmydesktop                0.3.8-4.1         all          Graphical frontend for recordMyDesktop screencast tool
> ii  gtk2-engines:amd64                 1:2.20.2-3        amd64        theme engines for GTK+ 2.x
> ii  gtk2-engines-murrine:amd64         0.98.1.1-5        amd64        cairo-based gtk+-2.0 theme engine
> ii  gtk2-engines-pixbuf:amd64          2.24.25-3+deb8u2  amd64        pixbuf-based theme for GTK+ 2.x
> ii  libcanberra-gtk0:amd64             0.30-2.1          amd64        GTK+ helper for playing widget event sounds with libcanberra
> ii  libcanberra-gtk3-0:amd64           0.30-2.1          amd64        GTK+ 3.0 helper for playing widget event sounds with libcanberra
> ii  libcanberra-gtk3-module:amd64      0.30-2.1          amd64        translates GTK3 widgets signals to event sounds
> ii  libclutter-gtk-1.0-0:amd64         1.6.0-1           amd64        Open GL based interactive canvas library GTK+ widget
> ii  libdbusmenu-gtk3-4:amd64           12.10.2-1         amd64        library for passing menus over DBus - GTK+ version
> ii  libgtk-3-0:amd64                   3.14.5+4          amd64        GTK+ graphical user interface library
> ii  libgtk-3-bin                       3.14.5+4          amd64        programs for the GTK+ graphical user interface library
> ii  libgtk-3-common                    3.14.5+4          all          common files for the GTK+ graphical user interface library
> ii  libgtk-sharp-beans-cil             2.14.1-3          all          Supplementary CLI bindings for GTK 2.14+
> ii  libgtk2-perl                       2:1.2492-4        amd64        Perl interface to the 2.x series of the Gimp Toolkit library
> ii  libgtk2.0-0:amd64                  2.24.25-3+deb8u2  amd64        GTK+ graphical user interface library
> ii  libgtk2.0-bin                      2.24.25-3+deb8u2  amd64        programs for the GTK+ graphical user interface library
> ii  libgtk2.0-cil                      2.12.10-5.1       amd64        CLI binding for the GTK+ toolkit 2.12
> ii  libgtk2.0-common                   2.24.25-3+deb8u2  all          common files for the GTK+ graphical user interface library
> ii  libgtkglext1                       1.2.0-3.2         amd64        OpenGL Extension to GTK+ (shared libraries)
> ii  libgtkmm-2.4-1c2a:amd64            1:2.24.4-1.1      amd64        C++ wrappers for GTK+ (shared libraries)
> ii  libgtkmm-3.0-1:amd64               3.14.0-1          amd64        C++ wrappers for GTK+ (shared libraries)
> ii  libgtksourceview-3.0-1:amd64       3.14.1-1          amd64        shared libraries for the GTK+ syntax highlighting widget
> ii  libgtksourceview-3.0-common        3.14.1-1          all          common files for the GTK+ syntax highlighting widget
> ii  libgtksourceview2.0-0              2.10.5-2          amd64        shared libraries for the GTK+ syntax highlighting widget
> ii  libgtksourceview2.0-common         2.10.5-2          all          common files for the GTK+ syntax highlighting widget
> ii  libgtkspell0                       2.0.16-1.1        amd64        a spell-checking addon for GTK's TextView widget
> ii  libindicate-gtk3                   0.6.92-2+deb8u1   amd64        library for raising indicators via DBus - GTK+ bindings
> ii  libjavascriptcoregtk-1.0-0:amd64   2.4.9-1-deb8u1    amd64        JavaScript engine library from WebKitGTK+
> ii  libjavascriptcoregtk-3.0-0:amd64   2.4.9-1-deb8u1    amd64        JavaScript engine library from WebKitGTK+
> ii  libjavascriptcoregtk-4.0-18:amd64  2.6.2+dfsg1-4     amd64        JavaScript engine library from WebKitGTK+
> ii  libnm-gtk-common                   0.9.10.0-2        all          library for wireless and mobile dialogs - common files
> ii  libnm-gtk0:amd64                   0.9.10.0-2        amd64        library for wireless and mobile dialogs
> ii  libpolkit-gtk-mate-1-0:amd64       1.18.2-1+betsy    amd64        MATE authentication agent for PolicyKit-1 (library)
> ii  libreoffice-gtk                    1:4.3.3-2+deb8u11 amd64        office productivity suite -- GTK+ integration
> ii  libwebkit2gtk-3.0-25:amd64         2.4.9-1-deb8u1    amd64        WebKit2 API layer for WebKitGTK+
> ii  libwebkit2gtk-4.0-37:amd64         2.6.2+dfsg1-4     amd64        Web content engine library for GTK+
> ii  libwebkitgtk-1.0-0:amd64           2.4.9-1-deb8u1    amd64        Web content engine library for GTK+
> ii  libwebkitgtk-1.0-common            2.4.9-1-deb8u1    all          Web content engine library for GTK+ - data files
> ii  libwebkitgtk-3.0-0:amd64           2.4.9-1-deb8u1    amd64        Web content engine library for GTK+
> ii  libwebkitgtk-3.0-common            2.4.9-1-deb8u1    all          Web content engine library for GTK+ - data files
> ii  libwxgtk3.0-0:amd64                3.0.2-1+b1        amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK+ runtime)
> ii  mint-themes-gtk3                   3.14+13           all          Mint themes for GTK3
> ii  pinentry-gtk2                      0.8.3-2           amd64        GTK+-2-based PIN or pass-phrase entry dialog for GnuPG
> ii  python-aptdaemon.gtk3widgets       1.1.1-4+deb8u1    all          Python 2 GTK+ 3 widgets to run an aptdaemon client
> ii  python-gtk2                        2.24.0-4          amd64        Python bindings for the GTK+ widget set
> ii  python-gtksourceview2              2.10.1-2          amd64        Python bindings for the GtkSourceView widget
> ii  python3-aptdaemon.gtk3widgets      1.1.1-4+deb8u1    all          Python 3 GTK+ 3 widgets to run an aptdaemon client
> ii  transmission-gtk                   2.84-0.2+deb8u1   amd64        lightweight BitTorrent client (GTK+ interface)
> ii  xdg-user-dirs-gtk                  0.10-1            amd64        tool to manage well known user directories (Gtk extension)
> 
PS. I must add that, for example, "about" window is opening properly.

**Comment by slgobinath** [comment]
Hi looks like the `<property name="interpolate_size">True</property>` in https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/glade/settings_dialog.glade#L172 is not supported in your system.

Could you please follow the given steps and let me know if it works?

1. Get the safe eyes location by executing the following command (copy and paste both lines together):
```
python3 -c "import safeeyes
print(safeeyes.__file__)"
```

In my machine, the output is: `/usr/lib/python3/dist-packages/safeeyes/__init__.py`

2. Open the `settings_dialog.glade` file:

```
vi /usr/lib/python3/dist-packages/safeeyes/glade/settings_dialog.glade
```

3. Go to line 172 (`<property name="interpolate_size">True</property>`), delete the line, save the changes and restart Safe Eyes

**Comment by bytefather** [comment]
Wow it helped. 
Thanks a lot slgobinath.
PS. First command returned the same on my mashine (`/usr/lib/python3/dist-packages/safeeyes/__init__.py`).
