### ISSUE TITLE
Custom Notification Event Sounds

### ISSUE THREAD

**Issue by p1839251** [slgobinath/SafeEyes#336]
Hey,

I've just installed SafeEyes because I wasn't satisfied with some other similar applications and it looks promising. It seems to be working well with Plasma 5.
So I'd like to know if I can pick my own notification sounds.
Not that I don't like these, I'm just so used to mine that I'd like to use them if it's possible.

**Comment by slgobinath** [comment]
Thanks. Please check this answer to see how to change notification sounds (Only `wav` files are supported).

https://github.com/slgobinath/SafeEyes/issues/302#issuecomment-462062724
