### ISSUE TITLE
After break SafeEyes switches to a new workspace

### ISSUE THREAD

**Issue by luckydays** [slgobinath/SafeEyes#337]
Hi guys.

I'm on Elementary OS 5.0 Juno.
This issue was there from the very beginning I've started using SafeEyes 2.0.9, actually. But now it really became annoying and I've decided to reach you out here.

So, the thing is that after any break, when it finished - totally new empty workspace appears in front of the eyes. And in order to get back to where I left off, there's a need to switch back to my initial workspace (using WIN + <--)

Can this be fixed?

Thank you!

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/08001f9cab1b7955dbe999b599ae737afc300532
