### ISSUE TITLE
Chrome crash if safeeyes start break

### ISSUE THREAD

**Issue by fajaryanw** [slgobinath/SafeEyes#340]
### Specification :
OS: `Arch Linux x86_64` 
Kernel: `5.3.1-arch1-1-ARCH` 
DE: `GNOME 3.34.0` 
WM: `Mutter` 
Theme: `Mojave-light-solid [GTK2/3]`
Icons: `Oranchelo [GTK2/3]`
google-chrome: `77.0.3865.90`
safeeyes: `2.0.9`

### Bug :
Google Chrome crash if safeeyes start break

**Comment by Dungdae** [comment]
I run same Kernel, Arch linux, Chromium (also ver. 77.0.3865.90), and Gnome-desktop 1.3.34.0.-1

My issue is quite similar to @fajaryanw, however on my machine it seems like a new gnome session is started (every window is closed and I start with a fresh desktop).

I suspect that it has something to do with the latest gnome-desktop, as the exact same issue occurs when opening pamac-aur.

**Comment by archisman-panigrahi** [comment]
@fajaryanw @KasperThystrup Is this issue still present in v2.2.1?

**Comment by archisman-panigrahi** [comment]
Cannot reproduce with `Chromium 127.0.6533.88` and Safe Eyes 2.2.1 in Arch Linux. Please reopen if you can reproduce this.
