### ISSUE TITLE
[Archlinux] yaourt is not supported anymore

### ISSUE THREAD

**Issue by FederAndInk** [slgobinath/SafeEyes#342]
As the title said, yaourt is not supported anymore and should not be used.
Another aur helper should be used instead like yay.
I have seen it on your website and in the readme of this repo, if you want to change it.

**Comment by slgobinath** [comment]
Added to README with https://github.com/slgobinath/SafeEyes/commit/9bb074b0784897e610b515862fa4b978ae8a68b3
