### ISSUE TITLE
Reset dialog needs rephrasing

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#345]
![image](https://user-images.githubusercontent.com/170947/67102515-dbcbe400-f1c3-11e9-95f8-88ac3325b8e7.png)

I think this should say "Are you sure you want to reset SafeEyes back to default settings?"

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/ccef830267ec2456f1d5e4238776c925c119c235
