### ISSUE TITLE
Take a (Long) break now button

### ISSUE THREAD

**Issue by p1839251** [slgobinath/SafeEyes#347]
I like the idea of having a 'Take a break now' option, but I believe it should always be a long break, shouldn't it?
I don't know how long your short breaks are, but mine is just a couple of seconds and a long break would be more sensible.

**Comment by Hritik14** [comment]
You can disable all the short breaks and have only long break work. 
It's effective in techniques like pomodoro.

**Comment by p1839251** [comment]
No, this isn't what I meant.
I do use short breaks besides long breaks. I don't want to disable them.
But let's see what they are for. They are meant to be quite short, just check the default exercises.
Nobody will blink for several minutes. So it's reasonable to use a low value here. I think mine is set to 20 seconds, which makes the current 'Take a break now' useless.

**Comment by AdamPS** [comment]
Fixed by #504
