### ISSUE TITLE
[Suggestion] Please add Korean language in Weblate project.

### ISSUE THREAD

**Issue by lee-yunseok** [slgobinath/SafeEyes#357]
One of the Safe Eyes user here. I requested to add Korean language but it doesn't listed yet. I can translate to Korean if you want it.

**Comment by slgobinath** [comment]
Hi @lee-yunseok,

I received the request from Weblate but I was busy with my work. I've committed Korean locale. Sorry for the delay.
https://hosted.weblate.org/languages/ko/safe-eyes/

Thank you very much for your contribution

**Comment by lee-yunseok** [comment]
Thanks. I will work it in this week.
