### ISSUE TITLE
Picture[s] adding

### ISSUE THREAD

**Issue by simarmata535** [slgobinath/SafeEyes#36]
this app really help for sure, just one thing, right now i am trying to quit smoking, and focusing on work very much helping, the problem is everytime this app tell me to break, instinctively i will look for cigarettes, so I think, if i could see picture of "NO SMOKING!" or "QUIT SMOKING" or something like that in the screen, that will do help so much.

that's all and thanky very much :+1: keep up the great works

**Comment by slgobinath** [comment]
This is a valid requirement. After resolving the major issues, I will add this feature.

**Comment by simarmata535** [comment]
i appreciate that  and thanks very much and look forward to it :-)

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/SafeEyes/commit/af8e9d51ab8360abdf724ef6d77ea4faf523af27
