### ISSUE TITLE
The menu is locked only during the pre break

### ISSUE THREAD

**Issue by dmitrysvd** [slgobinath/SafeEyes#362]
When the strict break is enabled, the menu is locked only during the pre break, which allows the user to open the menu before the break and turn the break off after it is started.
It seems to me that locking the menu until the break stops would be better.

P.S. The comment says that the menu is activated after the break, but it seems that it is not.
```
    def unlock_menu(self):
        """
        This method is called by the core to activate the menu after the the break.
        """
        if self.active:
            self.menu.set_sensitive(True)
```

**Comment by slgobinath** [comment]
Fixed with commit 9a92edd10735155675b69e19a99f8d9bc65d8e43
