### ISSUE TITLE
SafeEyes (Now, Post-Upgrade) Flickers On Breaks

### ISSUE THREAD

**Issue by machineghost** [slgobinath/SafeEyes#369]
I used an older version of SafeEyes on Linux Mint 18 for years, and it's by far my favorite "please interrupt me regularly" timer program.  However, I recently upgraded to Linux Mint 20, and got a newer version of Safe Eyes.

Now, between the new version and newer graphics drivers, Safe Eyes (for lack of a better word) "flickers" during breaks.  The dark overlay is mostly there, but every second (half second?) it sort of repaints the overlay, leaving the brightness behind for a fraction of a second (and not even the full screen, just a part of it), causing the "flicker".  But when you're trying to rest your eyes, the flicker is *very* distracting.

I'd be happy to provide any diagnostic details, a quick video (if I even can record it), or any other info that would be helpful.  And thanks for making Safe Eyes!

P.S. The problem is intermittent, but I don't have any good details on when it does or doesn't happen (it just recently both happened, and didn't happen shortly thereafter ... and both times I just had a webpage up in Chrome in the background).

**Comment by machineghost** [comment]
Actually, this is looking more like it's some kind of driver issue (that Safe Eyes triggers under specific/unknown conditions).

Unless anyone else ever sees this flickering, I'm going to assume it's because I'm running (I guess buggy?) open source graphics drivers, and that this is my issue and not Safe Eye's.  If anyone else does see it, I'd recommend playing with your graphics drivers first ... and then if that doesn't help maybe this ticket should be re-opened.

**Comment by slgobinath** [comment]
@machineghost thanks for reporting.
You are right it looks like a Graphics issue. I am running Linux Mint 20 with Nvidia driver. Never experienced this problem. However if an older version of Safe Eyes runs fine, I need to check on Safe Eyes side too.

Are you able to downgrade Safe Eyes and see if that works?

**Comment by machineghost** [comment]
I'm not able to downgrade, but when I was on Mint 18 I had a different version of the graphics driver installed, so I really think it's just something screwy with my driver.  Thanks though (and thanks again for Safe Eyes)!
