### ISSUE TITLE
Missing GenericName= in safeeyes.desktop

### ISSUE THREAD

**Issue by embar-** [slgobinath/SafeEyes#371]
"GenericName" variable (and its translation) should be included in safeeyes.desktop file.
See https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys

**Comment by archisman-panigrahi** [comment]
@embar- What should be the generic name for safeeyes?

**Comment by embar-** [comment]
Usually the same as other programs doing the same task.

E.g. RSIBreak has:

GenericName=RSI Prevention

**Comment by archisman-panigrahi** [comment]
I can add GenericName to this file https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/platform/io.github.slgobinath.SafeEyes.desktop.

But, how will it be translated using Weblate (unless people send pull request for translations manually)?

**Comment by embar-** [comment]
2024-07-15 18:57, Archisman Panigrahi rašė:
>
> I can add GenericName to this file 
> https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/platform/io.github.slgobinath.SafeEyes.desktop.
>
Good


> But, how will it be translated using Weblate (unless people send pull 
> request for translations manually)?
>
I do not know how...

**Comment by archisman-panigrahi** [comment]
@slgobinath How to add translations to new field in desktop file using Weblate? https://github.com/slgobinath/SafeEyes/issues/371#issuecomment-2228846723

**Comment by slgobinath** [comment]
I'm not sure if weblate supports it out of the box. Currently weblate is configured to update only the PO files. One way could be we add the description to po files and update the desktop file before each release.

If weblate supports it directly we can look into it as well - leaving it to anyone more experienced with weblate.

**Comment by archisman-panigrahi** [comment]
I have two ideas.

1. We can translate it with weblate, and once the translations are available, we will copy-paste them manually to the desktop file. I guess that translations of the text in the desktop file are so infrequent that it really would not increase our work burden.

2. We just translate "RSI Prevention" using Google translate. We keep RSI as RSI, and just translate "Prevention"
