### ISSUE TITLE
Smart Pause count as long break

### ISSUE THREAD

**Issue by AdamPS** [slgobinath/SafeEyes#373]
Great program!  I use the Smart Pause plug-in and I have enabled "Interpret idle time ... as break".  It works well, but not exactly as I would like....

Imagine that my long break duration is 10 minutes each hour.  I leave my computer for lunch of 60 minutes, SafeEyes notices I'm idle and counts a break.  However it doesn't seem to count a long break.  So I might get back from lunch, and I could get a long break at my next break.

I would prefer the algorithm like this:
If idle time greater than long break then reset both long break and short break
Else if idle time greater than short break then reset short break.

I would be happy to make a donation/bounty for fixes to this and one or two other open issue.  Please send me a private message if you would like to discuss it.  Many thanks for writing it.

**Comment by slgobinath** [comment]
Hi, This makes sense. I am busy with some personal commitments so unable to put my time in my FOSS projects these days.
I will work on this issue after this month.

**Comment by slgobinath** [comment]
Hi,
I've implemented this feature in https://github.com/slgobinath/SafeEyes/tree/feature-reset-breaks, I'd appreciate it if you could test the behaviour before merging this into the master branch.

In order to test from source code, you need to quit the running Safe Eyes instance and follow these steps:

```bash
git clone https://github.com/slgobinath/SafeEyes.git
cd SafeEyes
git checkout feature-reset-breaks
python3 -m safeeyes --debug
```

**Comment by AdamPS** [comment]
Many thanks @slgobinath.

I have been testing it for a few days and I think it works.  However it's confusing because I believe there is an existing bug: #385

**Comment by slgobinath** [comment]
@AdamPS you are right. I will fix the #385 . This feature shouldn't be affected by # though except the wrong time calculation.

**Comment by AdamPS** [comment]
Great thanks.  Yes I agree.  I believe the fix is good, but I was getting very confused in my testing.  Busy for a mo, I will test again in 2-3 days.

**Comment by slgobinath** [comment]
Sure. Merged the `feature-reset-breaks` into master. I will close this issue once you've confirmed.

Thanks

**Comment by AdamPS** [comment]
Thanks.  Easiest would be if I wait until you fix #385 then I can test both without the confusion:-)  Please send me a personal message if you would accept a donation with details of your preferred method.

**Comment by slgobinath** [comment]
HI, #385 is fixed. Please let me know if it works as you expect.

I do accept donations via PayPal https://paypal.me/slgobinath

Thanks

**Comment by AdamPS** [comment]
I believe there needs to be a correction.  Please see #388.  Thanks.

**Comment by slgobinath** [comment]
Makes sense. Thanks :-)

**Comment by AdamPS** [comment]
Great many thanks.  I send a donation.  I have offered donations on two others: 374 and 384.
