### ISSUE TITLE
screen saver extension not supported

### ISSUE THREAD

**Issue by zdzc** [slgobinath/SafeEyes#375]
For every 2 second, there's a new log entry in systemd journal. The message is `screen saver extension not supported`. It still happens even if I turned off the screensaver plugin. The problem stops if I disable SafeEyes. I'm using version 2.0.9 of the app.

My system:
```
OS: Arch Linux x86_64 
Kernel: 5.8.10-zen1-1-zen 
Uptime: 10 hours, 45 mins 
Packages: 959 (pacman) 
Shell: bash 5.0.18 
Resolution: 1366x768 
WM: sway 
Theme: Breeze [GTK3] 
Icons: breeze-dark [GTK2/3] 
Terminal: kitty 
CPU: Intel i5-7400 (4) @ 3.500GHz 
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
Memory: 3254MiB / 7898MiB

**Comment by zdzc** [comment]
After some digging around, it seems that `screen saver extension not supported` is caused by a call to `xprintidle`. Uninstalling `xprintidle` fixed the problem.

**Comment by ilario** [comment]
Filed an ticket on xprintidle repository:
https://github.com/g0hl1n/xprintidle/issues/9

**Comment by ilario** [comment]
Xprintidle, as the name says, is amde for detecting the screensaver on X11 and it does not work for more modern systems with Wayland. SafeEyes should check whether X11 or Wayland is running and check the screensaver activity accordingly.

**Comment by ilario** [comment]
The xprintidle developer suggested to have a look at https://github.com/swaywm/swayidle and the discussion is going on here: #391

**Comment by dbogdanov** [comment]
I have the same issue and I cannot uninstall `xprintidle` in APT as a workaround because it will require removing the `safeeyes` package as well.

**Comment by ilario** [comment]
@dbogdanov check out the discusion on #391
The dependencies will be updated once there will be a mechanism working also on Wayland, I suppose.
