### ISSUE TITLE
Set solid black background during break

### ISSUE THREAD

**Issue by simgunz** [slgobinath/SafeEyes#379]
I have edited `~/.config/safeeyes/style/safeeyes_style.css` and set the following:

```
.window_main {
    background: black;
    opacity: 1;
    border-color: transparent;
}
```

I restarted safeeyes, but the background displayed during the break is still transparent.

How can I set it to solid black?

PS: I also tried to change that parameter in the config file under `/etc` but the result is the same

**Comment by slgobinath** [comment]
Hi,
Editing the `safeeyes_style.css` should be enough.What is the Linux distribution (and desktop environment) are you using? I tried on my Linux Mint with Cinnamon machine, it works as expected.

**Comment by simgunz** [comment]
I further tested this and I can confirm that the settings file is read correctly. Setting the opacity to `0.1` does indeed make it more transparent, and changing it from `0.9` to `1` makes it more solid but I can still see my desktop.

Maybe it is related to the compositor. If I turn off the compositor no transparency is applied, but I think this is expected.

Operating System: Manjaro Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Kernel Version: 5.4.67-1-MANJARO
OS Type: 64-bit

**Comment by slgobinath** [comment]
So it looks like the compositor feature/issue. I am closing this issue as not related to Safe Eyes.
Thanks
