### ISSUE TITLE
Wrong idle time calculation for smart pause

### ISSUE THREAD

**Issue by AdamPS** [slgobinath/SafeEyes#385]
The code below is from smartpause/plugin.py line 152, copying only the part that's relevant.

```
if system_idle_time >= idle_time
                idle_start_time = datetime.datetime.now()
elif
                idle_period = (datetime.datetime.now() - idle_start_time)
```

In my case idle_time is 4 minutes and the long break is 5 minutes.  After 4 minutes of idle, the start time is set to now.  If I press a key after 6 minutes then idle_period becomes 2 minutes.  So the correct code is more like this...

`                idle_start_time = datetime.datetime.now() - system_idle_time`

**Comment by slgobinath** [comment]
Hi, You are right that makes sense. I'll fix it.

Thanks for pointing it out:-)

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/ebe6f1aafbcc4dd27235cce5c73d4c50d986c164

**Comment by AdamPS** [comment]
Great thanks
