### ISSUE TITLE
The eye exercise feature could be modified to "closing the eyes"

### ISSUE THREAD

**Issue by nav9** [slgobinath/SafeEyes#390]
Tired ocular muscles need rest. Not exercise. Simply closing the eyes and relaxing the face and neck muscles is the right way to give eye muscles the rest it needs during work-breaks. I know this for a fact. 
I've even written to the creator of EyeLeo about this. More info: https://nav9.medium.com/the-real-cure-for-eye-strain-6483490d150f
ps: Glad to see this new application here. Hope you'd get it into the official Ubuntu repositories soon.

**Comment by slgobinath** [comment]
Hi @nav9 
Thank you for your suggestion. The exercises included in Safe Eyes are just some examples that worked for me. I understand, it is not going to work for everyone. That's why Safe Eyes allows users to edit/delete/add exercises.

Feel free to change the exercises according to your need.

**Comment by nav9** [comment]
> ...The exercises included in Safe Eyes are just some examples that worked for me...
Good to know the exercises can be added/removed. The reason I raised it as an issue, is because when the feature of "eye exercise" is present, it leads people to think that eye exercises can somehow reduce eye strain. It's like working out for few hours in the gym, and when all your leg and arm muscles are tired, somebody tells you to do more exercises to cure the tiredness. Sure, some stretching etc. might help a little, but there is nothing more effective than taking complete rest. In the case of the eyes, rest is obtained by keeping the eyes closed and relaxing the muscles. Many people do not undergo the simple strain that you experience. They push themselves so much that their strain becomes acute or chronic. At such high levels of strain, it's detrimental to do eye exercises. I have an experiment for you: For a certain number of days, ensure that your eyes get strained for a certain number of hours, and try your eye exercises. For another bunch of days, ensure your eyes get strained and close your eyes and relax the face muscles and neck muscles. In both cases, measure how quickly the strain goes away and note it down. Other factors should be constant: For example, the amount of sleep you get and the food you eat. Believing that eye exercises can cure eye strain is similar to how people decided the Earth is at the center of the universe because celestial bodies appeared to go around the Earth. Someone with a broader perspective would know that's not true. I'm offering you this broader perspective from years of my experience. Eye exercises for reducing eye strain is wrong. Since you don't know me, since you haven't performed experiments yet and since you and ophthalmologists haven't undergone the severity of what I have been through, I understand you will have no reason to believe me. I leave the decision to the other maintainers and to you.

**Comment by nav9** [comment]
Just sharing more experiences from people world-over: https://nav9.medium.com/the-real-cure-for-eye-strain-more-experiences-7f4c1c552d5a
It's just sad that people are being led to believe that eye exercises, eye drops, special spectacles and special monitors can cure their eye strain, when the commonsense solution of getting proper sleep, rest and nutrition is not given enough emphasis. If all eye rest apps could focus on the fundamentals (sleep, rest, nutrition), it'd be a boon to mankind.
