### ISSUE TITLE
strict break interuptable / flickering

### ISSUE THREAD

**Issue by notthewave** [slgobinath/SafeEyes#397]
> #### Sytem:
> - Void-Linux x86_64 glibc
> - gnome 3.38.0_2 **Wayland**
> - SafeEyes 2.0.9_3

#### Expected bevavior:
SafeEyes screen is **un**interruptible and does not accept keyboard input when in strict break mode.

#### Actual behavior:
SafeEyes screen is interruptible and accepts keyboard input when entering window overview mode in Gnome. 
Leaving Overview-mode makes SafeEyes visible again but certain GUI elements/windows "**flicker** through".
It's even possible to open Htop and kill the active SafeEyes session.

**Comment by martnnw** [comment]
I'll test if this is Wayland specific

**Comment by slgobinath** [comment]
Looks like Wayland specific. I will take a look
Thanks for reporting
