### ISSUE TITLE
Support Python 3.8 and 3.9, drop Python 3.4 and 3.5?

### ISSUE THREAD

**Issue by hartwork** [slgobinath/SafeEyes#399]
Hi!

What are your thoughts on:
- Adding official support for current Python 3.8 and 3.9 and 
- dropping fully end-of-life Python 3.4 and 3.5?

Should I make a pull request?

Best, Sebastian

**Comment by hartwork** [comment]
Any thoughts?

**Comment by slgobinath** [comment]
Hi @hartwork I am extremely sorry for the late response. Of course we need to add support to Python 3.8 and 3.9. I will make the changes within this week. I hope there won't be any breaking changes :-)

**Comment by hartwork** [comment]
Cool!

**Comment by slgobinath** [comment]
The new version with the support for 3.8 and 3.9 is released.
Merry Christmas!

**Comment by hartwork** [comment]
:pray: Thanks and :christmas_tree: Merry Christmas! :christmas_tree:
