### ISSUE TITLE
User autostart

### ISSUE THREAD

**Issue by Yamakaky** [slgobinath/SafeEyes#4]
Instead of creating `~/.config/autostart/safeeyes.desktop`, do a symlink to the system `.desktop`.

**Comment by slgobinath** [comment]
Changed according to your suggestion in https://github.com/slgobinath/SafeEyes/commit/dd3f7978f06155fa21c64863e108bf0d1fbc90ef. The release [v1.0.7](https://github.com/slgobinath/SafeEyes/releases/tag/v1.0.7) includes this change.
