### ISSUE TITLE
Next break not updating

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#40]
Dear @slgobinath,

Do you have any idea why it could not be updating?

![image](https://cloud.githubusercontent.com/assets/170947/21852489/8c4b354c-d813-11e6-9022-69ccacc37efd.png)

**Comment by slgobinath** [comment]
This bug is introduced in the new version. I will release the fix soon.

**Comment by orschiro** [comment]
This would be great, thank you so much!

Will this update then be available in the PPA as well?

-R

**Comment by slgobinath** [comment]
Yeah sure :-). Will be fixed in v1.1.2.

**Comment by slgobinath** [comment]
Hi @orschiro 
Could you please try the new version (1.1.2) and let me know.

**Comment by orschiro** [comment]
It seems to be working. 

Thank you so much! :-)

**Comment by slgobinath** [comment]
You are welcome and thank you for reporting this major bug.

**Comment by orschiro** [comment]
Dear @slgobinath,

It happened again...

![image](https://cloud.githubusercontent.com/assets/170947/22212583/89b91484-e191-11e6-918e-a7f04f2724e8.png)

**Comment by slgobinath** [comment]
Hi @orschiro,
The reason is identified and fixed in https://github.com/slgobinath/SafeEyes/commit/d99da592c7bfb5117e575536e07966dbe21e89fa

**Comment by orschiro** [comment]
@slgobinath thank you! So, it had to do with full screen applications?

**Comment by slgobinath** [comment]
Today I have noticed that in my machine and when I checked the log it stopped after skipping the break because of a full-screen app. The start method is not intended to be called internally after the recent modifications. I plan to release a new version with at least one additional feature. Once I've implemented them, I will release a new version.

**Comment by orschiro** [comment]
Perfect, thanks! Really looking forward to the new version. 

Once Safe Eyes stops working, I have a hard to reminding myself to restart it.
