### ISSUE TITLE
Safeeyes doesn't enable by default on startup

### ISSUE THREAD

**Issue by shirejoni** [slgobinath/SafeEyes#405]
hello
i have ubuntu 20.04 and i installed safeeyes
but every time i power on my laptop, i should enable Safeeyes manual
how can i enable it automatically?

**Comment by slgobinath** [comment]
Hi, It's fixed in v 2.1.1
Please upgrade Safe Eyes, open Settings, click on the Safe Eyes icon on the title bar menu and `Reset`. It will create a desktop entry for Safe Eyes in ~/.local/autostart` folder.
