### ISSUE TITLE
Cannot disable SafeEyes autostart

### ISSUE THREAD

**Issue by jloqfjgk** [slgobinath/SafeEyes#409]
I don't want SafeEyes autostart with the desktop environment (Linux), however:
* Every time I start SafeEyes, it creates a symlink in `.config/autostart`
* If I delete the symlink, it will be created again next time I start SafeEyes
* Also, since it is a symlink to `/usr/lib/python3.9/site-packages/safeeyes/platform/safeeyes.desktop`, I can't set `Hidden=true` to disable autostart

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/e90d71f9dbbdc2939f0b4423ae12e31a1bf85b86

**Comment by slgobinath** [comment]
Released the fixed version 2.1.2
