### ISSUE TITLE
Break keeps getting delayed.

### ISSUE THREAD

**Issue by UtkarshVerma** [slgobinath/SafeEyes#410]
SafeEyes fails to show any breaks because the time for the next break keeps getting extended. For example, "Next break at 10:20 AM" at 10:00 AM, and "Next break at 10:21 AM" at 10:01 AM.

I'm observing this behaviour only on the latest build v2.1.1 (v2.0.9-r2 works fine) which I installed using the official ebuild for Gentoo.

**Comment by dario2332** [comment]
I have the same issue on Ubuntu with the latest version 2.1.1. It worked fine  before.

**Comment by matt-hires** [comment]
Same here.
As a workaround I disabled the "Smart Pause" feature.

**Comment by RB-Lab** [comment]
Confirm. It gets into "Disabled until restart" mode for a few seconds after each minute. Disabling "Smart Pause" also works.

**Comment by serjflint** [comment]
Same here. Also notifications are not working anymore. After disabling the "Smart Pause" it drops straight to the blacked screen.

**Comment by slgobinath** [comment]
Thank you for reporting this bug. Fixed with https://github.com/slgobinath/SafeEyes/commit/a69debf8ff0342e5235fa2a08d20e29c366c247d

I will release the new version soon. For the moment as @matt-hires mentioned, disabling smart pause will help.

**Comment by slgobinath** [comment]
Released the fixed version 2.1.2
