### ISSUE TITLE
Increase time (seconds) in Short Break

### ISSUE THREAD

**Issue by ducph00** [slgobinath/SafeEyes#415]
I cannot increase time in settings, since it has a maximum time limit. 
What can I do to increase it to 3 minutes instead of 60 seconds.
If you can develop more options such as minutes. That is amazing

OS: Linux Mint 19.3 Cinnamon
screenshot: https://ibb.co/NjL29D1

**Comment by slgobinath** [comment]
By default short breaks have a max limit of 60 seconds but you can override them in their individual settings to a longer duration.

For example, in the screenshot below, I increased the duration of first short break to 3 mins:
![Screenshot from 2021-01-19 08-33-15](https://user-images.githubusercontent.com/4003168/105041504-12308880-5a31-11eb-93f6-75ab2a3f995e.png)

**Comment by archisman-panigrahi** [comment]
Currently (checked in v2.2.1) is possible to increase the short break's duration beyond 60 seconds.

![image](https://github.com/user-attachments/assets/d46c451b-ea19-4c02-bd0a-7e6a1d27509f)

Please reopen if there is any confusion.
