### ISSUE TITLE
Missing Icon For Version 2.1.1

### ISSUE THREAD

**Issue by ghost** [slgobinath/SafeEyes#420]
I want to report that the same issue mentioned [here](https://github.com/slgobinath/SafeEyes/issues/300) exists in SafeEyes 2.1.1. I installed it through the PPA on Linux Mint 19.3 and the icon does not show up in the Applications Menu but the system tray icon is there. This file also does not exist: `/usr/share/icons/hicolor/64x64/apps/safeeyes.png`.

**Comment by slgobinath** [comment]
This is a known issue with the 2.1.1 version as Python packaging behaves differently now. I've already fixed the issue but not released a new version with the fix.
I will release the fix soon.

**Comment by slgobinath** [comment]
Released the fixed version 2.1.2
