### ISSUE TITLE
safeeyes not working in ubuntu 20.20

### ISSUE THREAD

**Issue by armjer** [slgobinath/SafeEyes#421]
safeeyes not working in ubuntu 20.20. The messages not apperars, but the program runs

**Comment by slgobinath** [comment]
Possible duplicate of https://github.com/slgobinath/SafeEyes/issues/410

Disabling Smart Pause plugin should solve the issue for the moment. I will release the fixed version asap (I have a busy time these days. It may take some time to release the next version)
