### ISSUE TITLE
No icon in Debian 11 bullseye

### ISSUE THREAD

**Issue by cs96and** [slgobinath/SafeEyes#428]
I recently upgraded to Debian 11 (bullseye).  I installed safeeyes through apt (v2.0.6), but there is no system tray icon appearing in KDE plasma.

Safeeyes does work though and correctly pops up a reminder about an upcoming break, and the break screen itself.

**Comment by azzamsa** [comment]
I think someone had submitted [a fix](https://github.com/slgobinath/SafeEyes/commit/c784000e694f9fa508a2535f5d23d04456b4ff86). However, having `gir1.2-ayatanaappindicator3-0.1` in my end, doesn't solve the problem.

``` fish
❯ which safeeyes  # installed using pip3 to get the latest version
/home/user/.local/bin/safeeyes

~
❯ safeeyes --version

(safeeyes:305878): dbind-WARNING **: 14:50:23.424: AT-SPI: Error retrieving accessibility bus address:org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
safeeyes 2.1.3

~
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

❯ sudo apt install gir1.2-ayatanaappindicator3-0.1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gir1.2-ayatanaappindicator3-0.1 is already the newest version (0.5.5-2).
0 upgraded, 0 newly installed, 0 to remove and 71 not upgraded.
```

**Comment by soredake** [comment]
No icon on fedora kde 36 also.

**Comment by soredake** [comment]
Problem solved, safeeyes from third-party repo was missing `libappindicator-gtk3` dep.

**Comment by soredake** [comment]
https://github.com/rpmsphere/noarch/issues/2

**Comment by hiqua** [comment]
@slgobinath could you release a new version including the fix of this bug (basically the current HEAD)? Right now Debian would have to either cherry-pick the commit / have their own special version, which is unfortunate given that the fix is already there.

The Debian testing is also freezing its packages soon (early next year I think) so it'd be awesome if this fix could be shipped before that.

See [the corresponding bug on Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1006942).

**Comment by slgobinath** [comment]
Hi @hiqua ,
Thanks for reminding me on this. I've released a new version https://github.com/slgobinath/SafeEyes/releases/tag/v2.1.4 from the current master branch.

My apologies to the community for not being active as I used to be due to several other commitments.

**Comment by hiqua** [comment]
Awesome, thanks a lot!
