### ISSUE TITLE
IMPORTANT: Black screen persists and blocks access to other application after quitting safe eyes

### ISSUE THREAD

**Issue by pratik-choudhari** [slgobinath/SafeEyes#429]
Hi, 
I am running ubuntu 18 and Safe eyes-v2.0.0-2. Today I terminated safe eyes application using the quit button and immediately after doing so a break screen opened because of its break schedule. The issue here is, now that safe eyes has been terminated the black screen opened can not be removed. I could not use any other application and when I tried to open terminal with Ctrl-Alt-T it open behind the black screen. Only solution was to restart the PC. This situation was frustrating as I was in a meeting.

**Comment by slgobinath** [comment]
Hi, I am sorry for what happened. It can happen since the break screen is running in a separate thread. I will fix it at my earliest.

I can feel how frustrating it is. Sorry for ruining your meeting. 🙁

**Comment by pratik-choudhari** [comment]
@slgobinath No, please don't be😅

**Comment by archisman-panigrahi** [comment]
I can reproduce this.

To reproduce: Click on the tray icon -> Take a Break Now -> Short Break -> **Immediately** click on the tray icon -> Quit.
Result: The break screen appears, and is stuck indefinitely. 

Workaround: Open a terminal behind the break screen (`ctrl + alt + T`), and run the command `pkill safeeyes`.

How about running the command `pkill safeeyes` when the quit button is pressed? (@deltragon)

**Comment by archisman-panigrahi** [comment]
@pratik-choudhari Thank you for reporting this. I just fixed it. The fix will be included in the next version. But in the meanwhile, you can try it using the safeeyes daily PPA https://launchpad.net/~safeeyes-team/+archive/ubuntu/safeeyes-daily
