### ISSUE TITLE
Default short break - Tightly close your eyes

### ISSUE THREAD

**Issue by AbstractGeek** [slgobinath/SafeEyes#436]
I recently checked with my ophthalmologist about eye exercises to minimize strain. He recommended most of the defaults in safe eye, except one. He did not recommend the default short break "Tightly close your eyes" as it tends to strain the eye muscles and is actually not good for the eye. Most people (including me for a while) use the default short breaks, so it might not be a good idea to have an exercise that potentially strains the eye. I recommend checking once with a ophthalmologist about that particular exercise before keeping it as one of the default short breaks. You might have done that, and maybe your doctor suggested it - I am not sure. But I figured I should raise the issue just in case, as defaults generally have a significant impact on its usage.

**Comment by slgobinath** [comment]
Hi, I came up with the techniques that worked for me and I totally agree that it may not be a good option and ophthalmologist may have a different opinion. I leave this issue open as a discussion to let other users to share their experience and feedback.

If most of us agree on this, we can remove this break in a future release.

**Comment by wolftune** [comment]
I would suggest updating this ticket to be something like "update the default exercises" and make a check-box for reviewing recommended best practices from health science etc. This is a topic those of us who are not programmers could certainly help with.

**Comment by nifadyev** [comment]
Hey @AdamPS , shall this issue be converted in Github Discussion?

**Comment by archisman-panigrahi** [comment]
I am in favor of removing this.

**Comment by deltragon** [comment]
I am also in favor of removing this. I would keep this issue open as an issue to better track updating the default options.
Suggestions for alternative default breaks are welcome.

**Comment by archisman-panigrahi** [comment]
How about replacing it with "Gently close your eyes"?

**Comment by archisman-panigrahi** [comment]
Turns out that on existing installations you will have to dele `.config/safeeyes` for the fix to work. It will work in new installations.
