### ISSUE TITLE
"Look at a point in the far distance" exercise?

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#44]
Hello all, 

What do you think of such an exercise? :-)

-R

**Comment by slgobinath** [comment]
Your PR is merged :-)
This issue is left open until getting translations.

**Comment by orschiro** [comment]
Cool! :-)

What translation do you need?

**Comment by slgobinath** [comment]
This exercise must be added to the following languages:
* Čeština
* Español
* Français
* Magyar
* Português
* Slovenský
* Русский
* தமிழ் (I will translate)

This exercise must be translated into other languages to give the same experience even though it will not impact the regular functionalities of the application.

**Comment by orschiro** [comment]
Espanol: Fijarse en un punto lejano
Portugues: Focalize seu olhar num ponto distante

**Comment by arty-name** [comment]
Russian: Сфокусируйте взгляд на далёком объекте

**Comment by jankudrik** [comment]
Czech: Zadívejte se na vzdálený bod.

**Comment by slgobinath** [comment]
Thanks to all. Now translation to Slovenský is required.
@radek-sprta need your help.
`Zamerať na bod v diaľke` is this the correct translation to `Focus on a point in the far distance`?

**Comment by radek-sprta** [comment]
Sorry, I was away for a bit. Created a pull request.

**Comment by slgobinath** [comment]
@radek-sprta,

Thank you very much for the translation. Your PR is merged.
