### ISSUE TITLE
Can not run SafeEyes since last update

### ISSUE THREAD

**Issue by Porrumentzio** [slgobinath/SafeEyes#441]
It is not possible to launch the program, not with the launcher, neither by command line
```
$ safeeyes
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 33, in <module>
    sys.exit(load_entry_point('safeeyes==2.1.3', 'console_scripts', 'safeeyes')())
  File "/usr/lib/python3.9/site-packages/safeeyes/__main__.py", line 147, in main
    safe_eyes = SafeEyes(system_locale, config)
  File "/usr/lib/python3.9/site-packages/safeeyes/safeeyes.py", line 100, in __init__
    self.plugins_manager.init(self.context, self.config)
  File "/usr/lib/python3.9/site-packages/safeeyes/plugin_manager.py", line 92, in init
    plugin['module'].init(context, config, plugin['config'])
  File "/usr/lib/python3.9/site-packages/safeeyes/plugins/trayicon/plugin.py", line 402, in init
    tray_icon = TrayIcon(context, plugin_config)
  File "/usr/lib/python3.9/site-packages/safeeyes/plugins/trayicon/plugin.py", line 141, in __init__
    self.set_labels()
  File "/usr/lib/python3.9/site-packages/safeeyes/plugins/trayicon/plugin.py", line 182, in set_labels
    entry[0].set_label(self.context['locale'].ngettext(entry[1][0], entry[1][1], entry[2]) % entry[2])
TypeError: not all arguments converted during string formatting

```

**Comment by slgobinath** [comment]
Hi, Can you share the output of the `locale` command from your terminal. Looks like there is a mistake in a translation file.

**Comment by Porrumentzio** [comment]
I use `eu` or `eu-ES` locales and actually I translated SafeEyes into those, so it could be.

**Comment by slgobinath** [comment]
Yup the problem is in the `eu` translation. For the `For %d hour`, `For %d Minute`, and `For %d Second` msgids, the translations must always have the `%d` symbol. If it is not there, the Python formatting will throw an error and break the app.

For example, in English, we have `For %d hour` (singular) and `For %d hours` (plural). In Basque translation, singular terms do not have a place holder for a digit. Can you modify the translation with the `%d` symbol in the right place?


https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/locale/eu/LC_MESSAGES/safeeyes.po#L452
https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/locale/eu/LC_MESSAGES/safeeyes.po#L458
https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/locale/eu/LC_MESSAGES/safeeyes.po#L464

**Comment by Porrumentzio** [comment]
There is no way of not using those parameters, right? It will be strange to decline a digital number ("1erako) instead of a word ("baterako")

**Comment by slgobinath** [comment]
Hi, Yeah it makes sense. I will take a look if I can fix this at the code level. Meanwhile I am merging your PR.

**Comment by Porrumentzio** [comment]
Could you create a tiny release so I can get this fix as soon as possible?

**Comment by slgobinath** [comment]
Hi, Sure I will release at my earliest. Sorry for the late reply and the time taking to release the next version as I am lost into my personal stuff and the Safe Eyes 3.0.0 implementation (a complete redesign of the core to make the code more readable and maintainable along with some fix to the current design flaws).

Until then you can replace the po and mo file of your locale using the given attachment.

1. Download and extract the [LC_MESSAGES.zip](https://github.com/slgobinath/SafeEyes/files/6543560/LC_MESSAGES.zip)  file
2. Replace `/usr/lib/python3/dist-packages/safeeyes/config/locale/eu/LC_MESSAGES/safeeyes.po` and `/usr/lib/python3/dist-packages/safeeyes/config/locale/eu/LC_MESSAGES/safeeyes.po` with the files in the zip file

Once again I am terribly sorry for the late response. I will release the new version asap.

**Comment by Porrumentzio** [comment]
That's great, don't worry! And look at this:
> We need to achieve everything we set out to do while living a full life. Our success and value are not based exclusively on spending all our energy on developing software. ~ https://docs.liberaforms.org/en/etiketo.html

I tried that method, changing some needed directory paths, but it didn't work for me. So I'll wait for the release, there's no problem :)
