### ISSUE TITLE
Start long break

### ISSUE THREAD

**Issue by buscon** [slgobinath/SafeEyes#456]
**Is your feature request related to a problem? Please describe.**
Right now it is possible to start a break manually. This starts the next planned break, i.e. it is not possible to decide whether to start a long or a short break.

**Describe the solution you'd like**
It would be useful to choose whether you want to start a short or long break.

**Describe alternatives you've considered**
Maybe it can choosen in the menu, such as "start a short break", "start a long break"
?

**Additional context**

**Comment by slgobinath** [comment]
Hi, There is an issue already tracking this problem lets discuss it there. btw this feature is implemented in Safe Eyes 3.0.0 branch (currently under development). You can expect it in the next release.

Closing this in favour of https://github.com/slgobinath/SafeEyes/issues/347
