### ISSUE TITLE
Add documentation for manually editing json config

### ISSUE THREAD

**Issue by teeann** [slgobinath/SafeEyes#469]
**Is your feature request related to a problem? Please describe.**
The option to edit `safeeyes.json` is not mentioned in the documentation. As a result, new users don't know to configure `safeeyes` in a reproducible way (i.e. editing the configuration text file).

**Describe the solution you'd like**
Add a brief mention of configuring `safeeyes` by editing `safeeyes.json` in the documentation.

**Comment by archisman-panigrahi** [comment]
>  As a result, new users don't know to configure safeeyes in a reproducible way

New users are not supposed to edit the JSON file manually. If we ask people to do that, that will just increase the number of bug reports.

I would prefer the users to configure the .json file using the settings in GUI, and copy-paste it if they want to copy their settings to a new installation.
