### ISSUE TITLE
Select language

### ISSUE THREAD

**Issue by Bound3R** [slgobinath/SafeEyes#471]
I just installed safeeyes but I don't see an option to change the language or a configuration to set this value, I currently have my system in English, but I would prefer to see the messages in Spanish only for this application.

**Comment by Bound3R** [comment]
¿Maybe someone has a workaaround?, I love how it works but it would be awesome if the messages were in a certain language and not by automatic detection.

**Comment by archisman-panigrahi** [comment]
This is already supported by all major GNU/Linux OS.

First, ensure that you have the Spanish locale enabled (For Ubuntu see https://askubuntu.com/questions/76013/how-do-i-add-locale-to-ubuntu-server, for Arch see https://wiki.archlinux.org/title/Locale#Generating_locales).

Then, run safeeyes with the command `LANG=es_ES.UTF-8 safeeyes` to ensure that safeeyes does display Spanish.

![image](https://github.com/user-attachments/assets/269bd111-c7b4-4070-95ac-c640462e2cc3)

To make the effect permanent, add the environment variable to the .desktop file of SafeEyes (you may also need to modify the other .desktop file used for startup).

Replace the `exec` entry with `exec=env LANG=es_ES.UTF-8 GDK_BACKEND=x11 safeeyes`
