### ISSUE TITLE
Screen flickering issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by mohamed-zezo** [slgobinath/SafeEyes#472]
**the bug**
I'm facing a screen flickering issue on Ubuntu 20.04. the black screen is toggling and resizing to the full screen every second.

![ezgif-2-f6ba670e31](https://user-images.githubusercontent.com/10938672/148979219-3f9adfff-e8d7-464e-9a83-90cefbca920b.gif)

**Steps to reproduce:**
Change the opacity to 0.5 in the safeeyes_style.css file.
Run SafeEyes.
Start a break (manually or time-based)

**Expected behavior**
clean and stable black screen with transparent background.

**Desktop:**
```
Distributor ID:	Ubuntu
Description:		Ubuntu 20.04.3 LTS
Release:		20.04
Codename:		focal

safeeyes 2.1.3

GNOME Shell 3.36.9

libgtk-3-0:
  Installed: 3.24.20-0ubuntu1
  Candidate: 3.24.20-0ubuntu1
  Version table:
 *** 3.24.20-0ubuntu1 500
        500 http://eg.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.24.18-1ubuntu1 500
        500 http://eg.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**Screenshots**
[Screenshot](https://imgur.com/U0Z2DZW)

**Comment by archisman-panigrahi** [comment]
Opacity seems to work without any screen flickering in KDE 6.1.3+Wayland. If you can reproduce this issue, please reopen.
