### ISSUE TITLE
Safeeyes sometimes gobbles up 1 cpu core

### ISSUE THREAD

**Issue by ak1932** [slgobinath/SafeEyes#476]
**Describe the bug**
Every once in a while safeeyes fully uses 1 CPU core.
The process "aplay -q /usr/lib/python3.10/site-packages/safeeyes/resource/on_stop_break.wav" uses the core.

**To Reproduce**
Haven't noticed any pattern to this behaviour

**Expected behavior**
It shouldn't use 1 CPU core?

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Desktop Env i3wm
 - Version - Safeeyes 2.1.3

**Debug Log**
[safeeyes.log](https://github.com/slgobinath/SafeEyes/files/8010840/safeeyes.log)

**Screenshots**
![Feb 06 - 23:36:12](https://user-images.githubusercontent.com/72815172/152695200-082c1379-c00a-47b6-a40f-7b5bb5635a20.png)

**Comment by nenkoru** [comment]
Well, I guess the question here is more likely to go to `aplay` as long as SafeEyes just calls it for executing the sound.
I wonder if you have some Pipewire installed? It could be an issue as well tho.

**Comment by ak1932** [comment]
Pipewire seems to be the culprit I removed it yesterday (It had come as a dependency of a package I longer needed anyway) and haven't noticed this bug again.

**Comment by ak1932** [comment]
Will let you know if it pops up again. BTW, safeeyes is preety cool I am have a **very** noticeable difference in my eyes. Thanks 😄
