### ISSUE TITLE
Critical Bug due to Gdk

### ISSUE THREAD

**Issue by AndresMpa** [slgobinath/SafeEyes#477]
**Describe the bug**

I wanted to initialize safeeyes together with nm, but when I type what I need to do it on my .xinitrc, it makes Xorg fail dude to a non-critical bug, if you run safeeyes from a terminal ([see this report](https://github.com/slgobinath/SafeEyes/issues/331)); but when you run it as I do It makes fail Xorg, so Qtile doesn't display what It should also command from keyboard doesn't work and in some cases, if you use `startx` from any tty mouses doesn't work too.

**To Reproduce**
1. Type on my .xinitrc file so
`
safeeyes & 2> /dev/null
`
2. Try to use any terminal or something
3. Nothing works, it only displays a black screen

**Expected behavior**
Starting safe eyes together with nm and picom.

**Desktop:**
 - OS: Arch Linux
 - Display server: Xorg
 - Desktop Env: Qtile (0.20.0)
 - Kernel: Linux zen (5.16.10-zen1-1-zen)

**Debug Log**
(safeeyes:10014): Gdk-CRITICAL **: 22:01:51.573: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

**Comment by archisman-panigrahi** [comment]
@AndresMpa Is this still relevant with the latest master branch (`yay -S safeeyes-git`)?

**Comment by archisman-panigrahi** [comment]
Please reopen if the issue is present in latest version.
