### ISSUE TITLE
Dependencies abandoned or unavailable on Fedora

### ISSUE THREAD

**Issue by BlueberryEco** [slgobinath/SafeEyes#482]
The Smart Pause plugin requires the package xprintidle for working on Xorg. The recommended source for xprintidle (on Fedora, at least) is an outdated repository which seems to be abandoned. I also downloaded a more recent version of xprintidle from the RPMSphere repository, and it does not work properly. If called on the command line, xprintidle produces the following error message:

`bash: /usr/bin/xprintidle: cannot execute binary file: Exec format error`

Which might indicate a build or packaging bug on it.

Also, the Do Not Disturb plugin on Wayland uses the package wlrctl as a dependency, which is also not available on the main Fedora repositories. I tracked it down on an RPMSphere repository, and also installed its dependencies(wlroots, etc.) and it does not work properly on GNOME. I tested it in Sway and there it does detect fullscreen windows as it should.

Perhaps some other packages exists who could provide the functionality that xprintidle and wlrctl do, and would work properly in Fedora (GNOME)? 

 - OS: Fedora 35
 - GNOME 41.6

**Comment by AdamPS** [comment]
If I understand correctly, the dependencies are only a problem on Fedora. This is not necessarily something that this project can fix😃.

**Comment by archisman-panigrahi** [comment]
This will be most likely fixed by https://github.com/slgobinath/SafeEyes/pull/576

**Comment by deltragon** [comment]
Well, only for Wayland - on X11, we still rely on xprintidle.
It might be possible to bypass xprintidle by using Xlib/xcb directly. PRs welcome, I personally don't think I'll invest much time it.

**Comment by archisman-panigrahi** [comment]
Does this work? https://copr.fedorainfracloud.org/coprs/alonid/xprintidle/

Anyway, Safe Eyes does not depend on xprintidle to work. When #576 will be merged, Safe Eyes on Wayland will be (almost) on par with XOrg. Then, we really will not need xprintidle.

I am also not in favor of investing our time to fix Safe Eyes in XOrg bypassing xprintidle.
