### ISSUE TITLE
AUR Package Maintainer Required

### ISSUE THREAD

**Issue by slgobinath** [slgobinath/SafeEyes#490]
Hi there,
I'm struggling to find enough time and energy to maintain releases. Since I don't use Arch, I used to have Virtual Box to test and release Safe Eyes on [AUR](https://aur.archlinux.org/packages/safeeyes). It would be helpful, if any Arch users willing to take over the maintenance of AUR package.

Please comment below if you are interested.

**Comment by poperigby** [comment]
I can take it over.

**Comment by ilario** [comment]
I also volunteer to. I have no previous experience in maintaining AUR packages, but I am an Arch and safeeyes user.
https://aur.archlinux.org/account/ilario

**Comment by otuva** [comment]
I can also possibly maintain or co-maintain

**Comment by yigitsever** [comment]
Hello,

I maintain a handful of packages and I have been using safeeyes for a while, I can happily take over the AUR maintenance 

https://aur.archlinux.org/account/yigits

**Comment by slgobinath** [comment]
Thanks, everyone. I highly appreciate all of you for volunteering to maintain [safeeyes](https://aur.archlinux.org/packages/safeeyes) AUR :pray: 

I've added all of you as co-maintainers and leaving it to you guys to decide how you want to coordinate the effort. I believe @yigitsever has some automation to build all his existing AUR packages. Hopefully, safeeyes can have something similar.

Once again thank you, everyone :pray:  I'm closing this issue since we've found our new maintainers but feel free to use this issue to coordinate your efforts.

**Comment by ilario** [comment]
I am not managing to find the time to maintain the package on AUR.
@archisman-panigrahi asked to become a maintainer.
For me it is ok, obviously.

**Comment by archisman-panigrahi** [comment]
@ilario Can you please add me as a co-maintainer? My AUR username is "archisman"

**Comment by ilario** [comment]
@archisman-panigrahi thanks for the interest!
On AUR, I cannot see any button for adding you.
Maybe @slgobinath has to do that?

**Comment by archisman-panigrahi** [comment]
@ilario Can you see this button?

![image](https://github.com/slgobinath/SafeEyes/assets/3063132/54f3d0c8-60da-48c3-88ed-7bee8bcab55d)

Otherwise, maybe only the package maintainer (@slgobinath) can do it.

**Comment by slgobinath** [comment]
Hi @archisman-panigrahi ,
Thanks again for stepping in. I've added you as the co-maintainer of AUR.

**Comment by archisman-panigrahi** [comment]
I uploaded 2.1.9 to the AUR (and also the PPA).

**Comment by slgobinath** [comment]
@archisman-panigrahi is it possible to automate the ppa and aur release from GitHub actions (if it will reduce your workload)?

**Comment by archisman-panigrahi** [comment]
I know that some people automate AUR release with GitHub actions (I don't know how to, but I can try to figure it out). I don't know if it can be even done with the PPA.
