### ISSUE TITLE
Can't connect to display ":0" on Arch Linux

### ISSUE THREAD

**Issue by ilario** [slgobinath/SafeEyes#495]
**The bug**
Since a few weeks, `safeeyes` fails to start due to some missing X authorization:

```
$ safeeyes
[...]
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
```

**To Reproduce**

Open Gnome with Wayland
launch `safeeyes`

Instead, trying to launch it from startx, it worked without error.

**Expected behavior**
Should work also on Gnome with Wayland.

**Desktop:**
 - OS: Arch
 - Desktop Env: 43.2
 - Version: safeeyes-git from AUR (2.1.4.r3.g9123562-1)

**Debug Log**
Run the Safe Eyes using `safeeyes --debug` command attach the ~/safeeyes.log` file.

```
2022-12-10 17:07:08,289 [DEBUG]:[MainThread] Initialize the platform
2022-12-10 17:07:08,306 [INFO]:[MainThread] Starting Safe Eyes
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 33, in <module>
    sys.exit(load_entry_point('safeeyes==2.1.4', 'console_scripts', 'safeeyes')())
  File "/usr/lib/python3.10/site-packages/safeeyes/__main__.py", line 150, in main
    safe_eyes = SafeEyes(system_locale, config)
  File "/usr/lib/python3.10/site-packages/safeeyes/safeeyes.py", line 84, in __init__
    self.break_screen = BreakScreen(
  File "/usr/lib/python3.10/site-packages/safeeyes/ui/break_screen.py", line 47, in __init__
    self.display = Display()
  File "/usr/lib/python3.10/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.10/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.10/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
```

**Workaround**

I managed to temporarily solve authorizing my own user to run X things:

```
xhost +SI:localuser:#$(id -u)
```

**Comment by krote5k** [comment]
```
safeeyes --debug                                                                                                                                                    1 ✘ 
2022-12-13 16:53:21,995 [DEBUG]:[MainThread] Initialize the platform
2022-12-13 16:53:22,019 [INFO]:[MainThread] Starting Safe Eyes
2022-12-13 16:53:22,059 [INFO]:[MainThread] Reading the session file
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 33, in <module>
    sys.exit(load_entry_point('safeeyes==2.1.3', 'console_scripts', 'safeeyes')())
  File "/usr/lib/python3.10/site-packages/safeeyes/__main__.py", line 147, in main
    safe_eyes = SafeEyes(system_locale, config)
  File "/usr/lib/python3.10/site-packages/safeeyes/safeeyes.py", line 84, in __init__
    self.break_screen = BreakScreen(
  File "/usr/lib/python3.10/site-packages/safeeyes/ui/break_screen.py", line 47, in __init__
    self.display = Display()
  File "/usr/lib/python3.10/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.10/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.10/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
```
OS: Manjaro
GNOME Shell 43.1
Python 3.10.8
safeeyes 2.1.3 (of.repo)

**Comment by Porrumentzio** [comment]
I had the same problem and solved it the same way.

**Comment by ilario** [comment]
Here https://github.com/slgobinath/SafeEyes/issues/367#issuecomment-894703668 @shaform mentions a possible fix, did anyone test that?

**Comment by ilario** [comment]
The problem seems this one that has been reported in `python-xlib` in August 2021 here https://github.com/python-xlib/python-xlib/issues/207 and fixed in September 2022 here https://github.com/python-xlib/python-xlib/pull/230 and happens when the display `:0` is not mentioned in the xauth cookie (normally it does not specify it).

So this has been fixed in python-xlib since 0.32 but in Arch Linux right now we have python-xlib 0.31 https://archlinux.org/packages/community/any/python-xlib/

@Foxboron do you know if python-xlib >0.31 will be available in Arch?

In the meanwhile, the workaround would be, as mentioned in https://github.com/python-xlib/python-xlib/issues/207#issue-978560370, to run

`xauth add $DISPLAY $(xauth list $DISPLAY | cut -d: -f2- | tail -1)`

before the safeeyes autostart. You will see a new line mentioning `:0` appearing when you list the cookies with `xauth list`.

In order to have it permanent I did the following:
created a script in my home folder /home/YOUR_USERNAME/xauth-safeeyes.sh including that line and being executed by an autostart file.

The `/home/PUT_YOUR_USERNAME_HERE/xauth-safeeyes.sh` file contained:
```
#!/bin/sh
xauth add $DISPLAY $(xauth list $DISPLAY | cut -d: -f2- | tail -1)
```
and was made executable with `chmod a+x xauth-safeeyes.sh`.
Then I created the autostart file `~/.config/autostart/00-xauth-safeeyes.desktop` containing:
```
[Desktop Entry]
Name=Safe Eyes workaround
Exec=/home/PUT_YOUR_USERNAME_HERE/xauth-safeeyes.sh
Terminal=false
Type=Application
```

**Comment by Foxboron** [comment]
`0.32` fails to build and I have not had time to figure out why, and probably won't have the time for a little while. Any help would be appreciated.

**Comment by ilario** [comment]
Hi!
Thanks @Foxboron for the answer!!
I tried modifying the PKGBUILD with pkgver 0.32 or 0.33 and the respective sha256sums and both compile for me on my laptop.
Do you have to compile it in a specific way? Sorry, I never packaged any Arch package.

**Comment by ilario** [comment]
@Foxboron I tried to compile python-xlib 0.32 using `extra-x86_64-build` from Arch's `devtools` and got an error about missing Tk files.
But compiling 0.33 was working without any problem.
Is it possible to update the package directly from 0.31 to 0.33?
Thanks!!
PS tell me if you prefer to communicate on another channel

**Comment by ilario** [comment]
python-xlib has been updated in Arch to follow the upstream 0.33 version.
Thanks @Foxboron!!!!
I confirmed that now safeeyes opens correctly without the need of the workaround mentioned above.
So this issue can be closed.

**Comment by Foxboron** [comment]
@ilario No worries. I noticed it was in-fact compiling with the latest release so it was part of the recent package updates I did this week.
