### ISSUE TITLE
Fails to start in Ubuntu 16.10 with "ImportError: No module named scheduler"

### ISSUE THREAD

**Issue by hotice** [slgobinath/SafeEyes#5]
SafeEyes (installed from PPA) fails to start in Ubuntu 16.10, with the following error:
```
$ /opt/safeeyes/safeeyes/safeeyes
Traceback (most recent call last):
  File "/opt/safeeyes/safeeyes/safeeyes", line 29, in <module>
    from SafeEyesCore import SafeEyesCore
  File "/opt/safeeyes/safeeyes/SafeEyesCore.py", line 22, in <module>
    from apscheduler.scheduler import Scheduler
ImportError: No module named scheduler
```
Tested on 2 Ubuntu 16.10 machines. ``python-apscheduler`` is installed. Also, Ubuntu 16.04 and 14.04 are not affected.

**Comment by ricsipontaz** [comment]
It doesn't work on my system(Ubuntu 16.10) too.

**Comment by slgobinath** [comment]
I am working on this. Soon I will release an update.

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/dd3f7978f06155fa21c64863e108bf0d1fbc90ef. Check the new release [v1.0.7](https://github.com/slgobinath/SafeEyes/releases/tag/v1.0.7)
