### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by slgobinath** [slgobinath/SafeEyes#500]
Happy New Year to the Safe Eyes Community!

I created Safe Eyes for my own needs and published it FOSS years ago. I'm happy to see the impact Safe Eyes make and like to see it grows further. However, I'm unable to find enough time to spend on Safe Eyes due to some other projects, family, and a demanding job.

Though I want to add new features and take this project to the next level (Safe Eyes 3 has been a dream project for a long period) I couldn't find enough time. Therefore, I am looking for new maintainers willing to take over Safe Eyes and keep it active. I'm happy to share my thoughts and contribute whenever I get some time but it would be beneficial for the project if someone with new ideas and energy can take over Safe Eyes.

Safe Eyes users don't have to worry. It doesn't mean I'm gonna archive the repo. If I couldn't find any new maintainers I will still maintain this repo but like the past few years, the project may not receive a lot of new features.

**Comment by AdamPS** [comment]
Interesting. I can understand your feelings - you've given a lot already and the community of happy users are very grateful, thank you.

> I am looking for new maintainers willing to take over Safe Eyes and keep it active
I could potentially be a _co-maintainer_ to share the work. I only use Linux and my knowledge of python/QT is quite limited, but the Internet has the answers to everything so I get there in the end.

> The 3.x branch was left behind since I planned to rewrite Safe Eyes completely from scratch with support for Mac (also switching to QT from GTK)
That I don't have the energy or skills for unfortunately.

My own focus would be particular bugs and features that I have a personal requirement for. Some of these were a little tricky with the current interfaces/structure so I would potentially be interested in creating a 3.x with some restructuring and interface changes. It would be less of a difference that your original 3.x dream and I guess I would create a new branch forked from 2.x.

How does any of that sound to you??

**Comment by slgobinath** [comment]
Thanks a lot, @AdamPS 
I will spend some time this weekend setting up CI/CD for automatic release to PyPi and Ubuntu launchpad so that some effort in releasing can be reduced. Once the CICD is completed let's define the scope of the project and the responsibilities we can share. Thank you very much for being a long-time user and stepping up to maintain the project. It means a lot.

**Comment by slgobinath** [comment]
Hi @AdamPS ,
I've sent you the invitation to be a collaborator. Once again thanks a lot :pray:

**Comment by AdamPS** [comment]
Thank you very much, I'm very happy to be part of this project - SafeEyes is a really nice tool.

Apologies for the slow response as I've been a bit busy for a couple of weeks. I'll get started in the next day or two planning my ideas for 3.x.

**Comment by nifadyev** [comment]
Hi @slgobinath , sorry for bothering you, but I wanted to re-open this issue because in my opinion the project needs more collaborators and maintainers.
You are well aware that codebase, dependencies and sometimes logic is outdated. And in order to make real V3 the project requires lots of human-hours.
For now, it would be good to understand and describe current project state and “ideal” future state. And only then it is possible to plan something.

**Comment by Asalle** [comment]
Hi @slgobinath thank you for years of tireless work! I have used safeeyes for as long as I remember and it really made a difference in my eye strain. I cannot thank you enough for putting your personal project for everyone to use and benefit from, keeping up with high throughput of demands and bugfixes.

**Comment by slgobinath** [comment]
Thanks for your kind words @Asalle 

I cannot take the full credits though. I'm no longer actively maintaining this project but @archisman-panigrahi @deltragon and @hartwork are pushing it forward. It was a project born out of my own necessity and I'm glad it's helping many people out there. Thanks to all maintainers and contributors ❤️
