### ISSUE TITLE
Add Fixed Breaks

### ISSUE THREAD

**Issue by Jomshanseat** [slgobinath/SafeEyes#509]
**Is your feature request related to a problem? Please describe.**
While the random breaks that happen all the time are really useful for me, I'd like to be able to set something like Fixed breaks, that happen once with preset activities. 

**Describe the solution you'd like**
I'd like to be able to set fixed breaks with predetermined timestamps and Topics, so I can do stuff like timing meals and other events.

**Comment by archisman-panigrahi** [comment]
> so I can do stuff like timing meals and other events.

Please use an alarm clock app for that. Implementing this will require a lot of rewriting, and I don't want to do that unless someone sends a PR.
