### ISSUE TITLE
Disable for x hours

### ISSUE THREAD

**Issue by Yamakaky** [slgobinath/SafeEyes#51]
Sometimes, I disable safeeyes for some reason, then forget to turn it on later. It would be cool to have a "disable for x hours"/"disable until next suspend cycle".

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/SafeEyes/commit/ef156bfb0c8d650ce198d30930f8167031a14036. Will be included in the next release.

**Comment by Yamakaky** [comment]
Cool!

**Comment by slgobinath** [comment]
Included in Safe Eyes [v1.1.5](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.5)
Could you please test this version and update the Arch AUR. There are new dependencies to add: `python2-babel`, `xprintidle` and `mpg123`

**Comment by Yamakaky** [comment]
Done.
Shouldn't it be v1.2.0? It's not a bugfix.

**Comment by slgobinath** [comment]
Yep, you are right. I didn't think about it :-) We'll move to 1.2.0 with the next release.

**Comment by slgobinath** [comment]
@Yamakaky,

Sorry for troubling you. I need to update the version to 1.1.6 due to a bug noticed after the release.

Thanks
