### ISSUE TITLE
Update installation instructions for Debian

### ISSUE THREAD

**Issue by mmmarcos** [slgobinath/SafeEyes#514]
**Bug description**
The [project page](https://slgobinath.github.io/SafeEyes/) suggest installing using pip3 and requires a dependency that no longer exists (see #268 #417).

**Expected behavior**
Update project page to install via the [safeeyes Debian package](https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=safeeyes) as already described on [README.md](https://github.com/slgobinath/SafeEyes#debian)

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/657a6952798ba1648e8434b768f92f6e193e528a
