### ISSUE TITLE
Reset Sequence Option

### ISSUE THREAD

**Issue by machineghost** [slgobinath/SafeEyes#517]
**Is your feature request related to a problem? Please describe.**

When I get up in the morning, my computer has been on all night.  So, when I start using it, SafeEyes is at a random point in its cycle: I might get presented with the first of several short breaks, or I might be presented with a long break.

**Describe the solution you'd like**
It'd be awesome if SafeEyes could observe screensaver/power saving usage, and after a long period (4+ hours?) of it, automatically reset the sequence of short/long breaks when you return.

Failing that, a simple right-click option on the Safe Eyes icon, to let you reset the sequence manually, would also work.

**Describe alternatives you've considered**
I guess I could keep using "Take a beak now", over and over (and click skip on the breaks) until I get a long break, then skip that ... but obviously that's a hassle.

**Additional context**
Thank you so much for making SafeEyes!  As someone who suffers from tendonitis due to extended periods at the computer without breaks, your app really helps me not injure myself (or at least not as much ... I still click "Skip" sometimes when I shouldn't).

P.S. I know nothing about Linux applet development, but I do know (some) Python, so if you could point me in the general direction I could *try* (no promises) to make a pull request for this.

**Comment by archisman-panigrahi** [comment]
>  I guess I could keep using "Take a beak now", over and over (and click skip on the breaks) until I get a long break, then skip that

In the latest version you can click `Take a break now -> Long break` to reset the sequence.

> I still click "Skip" sometimes when I shouldn't

Please check out the new "Limit consecutive skips" plugin introduced in #526.

Please reopen if you think the issue is still not solved.
