### ISSUE TITLE
Readme - Update virtual environment steps

### ISSUE THREAD

**Issue by sxzero** [slgobinath/SafeEyes#525]
Hello,

Just to mention that you should delete the flag `--no-site-packages` from the [install-in-virtual-environment](https://github.com/slgobinath/SafeEyes#install-in-virtual-environment) instructions since it's deprecated and now that's the default behavior.

Ref: https://virtualenv.pypa.io/en/legacy/reference.html#cmdoption-no-site-packages

**Comment by slgobinath** [comment]
Fixed by https://github.com/slgobinath/SafeEyes/pull/559
