### ISSUE TITLE
When the black screen with timer appears, it doesn't count back, but freezes whole computer

### ISSUE THREAD

**Issue by pastet89** [slgobinath/SafeEyes#527]
**Describe the bug**
Recently, since a few weeks, a bug appeared: When the black screen with timer appears, it doesn't count back, just shows 20 seconds, stays on this screen, then freezes whole computer and nothing can be done to escape from this screen. The computer must be shut down from the hardware button.

**To Reproduce**
1. Wait for a timer to start
2. Sometimes it does that, let's say, once each 1-2 days

**Expected behavior**
The timer to countdown and then to get back to the working screen.

**Desktop (please complete the following information):**
 - OS: Linux - MX 18.3 Continuum
 - Desktop Env: XFCE
 - Version 

**Debug Log**
N/A for now, just set it to run in debug mode the next times

**Screenshots**
N/A

Important: the bug started to appear since a few weeks. Without any updates that might have triggered it.

**Comment by nifadyev** [comment]
Hey @pastet89 , is the issue still relevant? What version of SafeEyes are you using? Is it possible to collect recent logs?

**Comment by archisman-panigrahi** [comment]
I am closing this because I do not anymore experience this in any of the recent versions of safeeyes in any recently released OS. Please reopen if you encounter this on the latest release.
