### ISSUE TITLE
Delete accidental Git tag "vv2.1.6" with double "v"?

### ISSUE THREAD

**Issue by hartwork** [slgobinath/SafeEyes#530]
Hi!

It seems that there are two Git tags for 2.1.6:

![Screenshot_20230705_172635](https://github.com/slgobinath/SafeEyes/assets/1577132/571af7a4-d587-4bf4-8d66-3cbdfe8ffd59)

 Not with identical SHA1 but with identical content:

```console
# git diff --exit-code v2.1.6 vv2.1.6 && echo identical
identical
```

Could the one with the double "v" be deleted?

Thanks!

CC @AdamPS @slgobinath

**Comment by AdamPS** [comment]
Done

**Comment by hartwork** [comment]
Thanks! :+1:
