### ISSUE TITLE
Disappearing menu shortcut

### ISSUE THREAD

**Issue by ekasprzak** [slgobinath/SafeEyes#532]
**Describe the bug**
Hi,

I noticed an issue with a menu shortcut.
After installing (flatpak), there isn't anything (SafeEyes related) in $HOME/.local/share/applications and SafeEyes can be opened from the app menu.

When I open it - it disappears from the menu app and a .desktop file is placed in the above directory, which (at least in my case) is a broken link:

`io.github.slgobinath.SafeEyes.desktop -> /app/lib/python3.10/site-packages/safeeyes/platform/io.github.slgobinath.SafeEyes.desktop`

I don't have /app folder at all and probably that's why it disappears from the menu?

When I remove 
$HOME/.local/share/applications/io.github.slgobinath.SafeEyes.desktop

after a few seconds menu shortcut appears again (and disappears again after first opening again).

**To Reproduce**
1. Open app

**Expected behavior**
Menu shortcut does not disappear

**Desktop (please complete the following information):**
 - OS: Fedora
 - Desktop Env : Gnome
 - Version: 2.1.6/Flatpak

**Debug Log**
Let me know if it's needed.

**Screenshots**
No need

**Comment by archisman-panigrahi** [comment]
I don't think this bug is still valid because people seem to be using the flatpak version successfully. Please reopen if reproducible.
