### ISSUE TITLE
App fails to start if only a config file is present

### ISSUE THREAD

**Issue by raddessi** [slgobinath/SafeEyes#536]
**Describe the bug**
I'm not sure if you want to support this, but I manage my config file between hosts and have safeeyes installed and the config dropped even before I log in for the first time. Would be useful for me if it started up with only the config file present but I understand if it's an edge case. Thank you for the great app I and my eyes love it!

**To Reproduce**
1. `rm -Rf ~/.config/safeeyes`
2. `touch ~/.config/safeeyes/safeeyes.json`
3. `python -m safeeyes` from git

**Expected behavior**
The app should load and provide the rest of the css, etc

**Desktop (please complete the following information):**
 - OS: Fedora-38
 - Desktop Env: Cinnamon
 - Version: master

**Debug Log**
I do believe this is all you need 
```
zsh ❯ python -m safeeyes
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/raddessi/dev/SafeEyes/safeeyes/__main__.py", line 158, in <module>
    main()
  File "/home/raddessi/dev/SafeEyes/safeeyes/__main__.py", line 150, in main
    safe_eyes = SafeEyes(system_locale, config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raddessi/dev/SafeEyes/safeeyes/safeeyes.py", line 84, in __init__
    self.break_screen = BreakScreen(
                        ^^^^^^^^^^^^
  File "/home/raddessi/dev/SafeEyes/safeeyes/ui/break_screen.py", line 61, in __init__
    css_provider.load_from_path(style_sheet_path)
gi.repository.GLib.GError: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /home/raddessi/.config/safeeyes/style/safeeyes_style.css: No such file or directory (2)
```

**Screenshots**

**Comment by AdamPS** [comment]
Sure, it's something we could add support for however not really a bug

**Comment by raddessi** [comment]
Fair enough! I'll try to send up a PR at some point. Thank you

**Comment by archisman-panigrahi** [comment]
I think this has been fixed by https://github.com/slgobinath/SafeEyes/pull/614
