### ISSUE TITLE
Respect System Time Representation

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#54]
Hi @slgobinath,

Just wondering why Safe Eyes' time representation doesn't match Ubuntu's (see PM use)?

Yours,

Robert

**Comment by orschiro** [comment]
![timezone-safe-eyes](https://cloud.githubusercontent.com/assets/170947/22549038/9f9ceb9e-e949-11e6-98fd-692072488836.png)

**Comment by radek-sprta** [comment]
I have a fix for this using locale.T_FMT. I will clean it up on the weekend and make a pull request.

**Comment by slgobinath** [comment]
Hi @orschiro & @radek-sprta,

Is this about the time representation (24 hours or AM/PM) or about any time zone issues?

**Comment by orschiro** [comment]
@radek-sprta thank you! :-)

@slgobinath it was more about the representation. I prefer consistency. If the system uses the 24h representation, Safe Eyes should do so, too.

Yours,

Robert

**Comment by slgobinath** [comment]
Hi @radek-sprta,

Thanks a lot for your contribution. I have a question regarding this PR.
The `dateTime.strftime(locale.nl_langinfo(locale.T_FMT))` respects the system locale (+1 for that feature and we need it) but it does obey the 24hours or AM/PM format. According to this change, it is always going to display the time in 24 hours, isn't it?

Thanks

**Comment by radek-sprta** [comment]
It detects the format correctly. locale.T_FMT returns the locale-specific time representation, no matter whether it is in 24 hour format or AM/PM format. Here's a screenshot:
[![Screenshot from 2017-02-07 12-42-15.png](https://s27.postimg.org/m25wrs9tv/Screenshot_from_2017_02_07_12_42_15.png)](https://postimg.org/image/djwgng3b3/)

**Comment by slgobinath** [comment]
Thank you for the clarification. I was confused by the 'Use 24hours' option available in Linux Mint clock. Your PR is merged and thanks a lot for your contribution.

**Comment by slgobinath** [comment]
Resolved the problem with https://github.com/slgobinath/SafeEyes/commit/73c7e740578d00ed52b4b9d0b09b72cd9d46e247.

**Comment by slgobinath** [comment]
Included in Safe Eyes [v1.1.5](https://github.com/slgobinath/SafeEyes/releases/tag/v1.1.5)
