### ISSUE TITLE
Would be nice to see this on pypi

### ISSUE THREAD

**Issue by vpal** [slgobinath/SafeEyes#56]
It would be really nice and maybe also more standard and safe to make this installable into the user's home directory with `pip install --user safeeyes` instead of adding PPAs or un-targzing this into /.
It would also be easier to update (`pip install --upgrade --user safeeyes`) for people who do not want to add third party PPAs to apply updates as opposed to the tar.gz method.
Just an idea to consider.

Thanks.

**Comment by slgobinath** [comment]
Hi @vpal,
Can we install non-python dependencies using this way? Example: `gir1.2-appindicator3-0.1` and `mpg123`

**Comment by vpal** [comment]
No. You can't. Those system level dependencies would have to be installed manually the same way like you would do with the current targz installs.
(AFAIK you can only list "python level" dependencies in python packages, like other packages from pypi and those will then also be installed by pip.)

**Comment by hartwork** [comment]
If there is interest in submitting to PyPI later: This commands works well for uploading new releases for me:
```
python setup.py sdist upload -r https://pypi.python.org/pypi
```
I'm sharing that because of the `-r ...` part.

**Comment by slgobinath** [comment]
@hartwork,
I am thinking of migrating to Python 3 as well https://github.com/slgobinath/SafeEyes/issues/96. If possible, we will migrate to Python 3 and then submit to PyPi.
I like to include all these changes into v1.2.0 but these days I am little busy. After this weekend I will test https://github.com/slgobinath/SafeEyes/issues/96 and consider this as well.

Btw thanks for your great support :-)

**Comment by slgobinath** [comment]
Now `SafeEyes 1.2.0 alpha` is available in PyPI. I will push the stable release after testing on all the platforms.

Thanks
