### ISSUE TITLE
Transparency not working on Wayland

### ISSUE THREAD

**Issue by emilyyyylime** [slgobinath/SafeEyes#562]
I noticed screenshots of the app in action have a transparent background, and realised that on my setup that isn't the case.

I am using Sway on Wayland from the `swayfx` AUR  package on Arch Linux.

relevant section from CSS file:
```
.window_main {
    background: black;
    opacity: 0.7;
    border-color: transparent;
}
```
Screenshot:
![Image showing SafeEyes break screen with opaque black background](https://github.com/slgobinath/SafeEyes/assets/40892795/bb389832-56fd-4d0a-8bb8-9ce77916f53a)

**Desktop (please complete the following information):**
 - OS: Arch Linux (`6.6.8-arch1-1`)
 - Swayfx (`sway version 0.3.2-26cdeeb (Dec  4 2023, branch 'master')`)
 - SafeEyes from the AUR (`safeeyes 2.1.6`)

**Comment by nifadyev** [comment]
@AdamPS , what do you think about labelling this issue as `aur` or `arch-linux`? There are a lot of `Arch Linux` related issues

**Comment by deltragon** [comment]
@emilyyyylime Could you test this with my gtk4 port (https://github.com/slgobinath/SafeEyes/pull/561)?
I was having similar issues on KDE, but with gtk4 and its better wayland support this is fixed for me.

**Comment by archisman-panigrahi** [comment]
Transparency seems to work with Wayland now. Tested in KDE 6.1.3 + Safe Eyes 2.2.1 in Arch Linux. If you still face the same issue, please reopen.

![image](https://github.com/user-attachments/assets/04ce75f3-5d56-49c6-9975-dd35cf9fa515)
