### ISSUE TITLE
Updated to Linux kernel 6.8.8-zen - safeeyes not starting

### ISSUE THREAD

**Issue by ArchieLinux** [slgobinath/SafeEyes#573]
_This is an installation issue, not a program bug per se. But this seems to be the place to report the issue:_

I noticed that the safeeyes icon is not appearing after today's regular update to Arch/kernel 6.8.8-zen1-1-zen and a reboot. My system shows it is installed but not functional. 

So I uninstalled it (`yay -Rc safeeyes`) and then explicitly rebuilt the package clean (i.e., invoking `yay -S safeeyes` to commence a clean install). 

Still no luck. Can't seem to get safeeyes to start up anymore. :shrug: 

`==> Cleaning up...`
`[sudo] password for {xxx}:` 
`error: invalid option '-s' `

Everything seems to work perfectly until this simple error message (above) which is the final line in the terminal. 

Any thoughts as to why would be appreciated?

**Comment by ArchieLinux** [comment]
@sol2070  Sadly, I gave up. Perhaps I'll check back and reinstall some day. For now, I'll just plan to have my eyesight continue to deteriorate ;-)

**Comment by archisman-panigrahi** [comment]
I am on 6.9.4-zen kernel in Endeavour OS, and the issue does not occur with the updated AUR package (v2.1.9).

**Comment by archisman-panigrahi** [comment]
I am closing the issue as it cannot be reproduced.

If it is still present, please reopen and post the output of the command `safeeyes`.

**Comment by ArchieLinux** [comment]
Yes, sorry - didn't have time to re-test until now. It appears to be functioning again. Thank you!
