### ISSUE TITLE
[2.1.7, 2.1.8, Git `master`] Plugin `smartpause` calls `disable_safeeyes` with unsupported signature, causing display of a backtrace

### ISSUE THREAD

**Issue by hartwork** [slgobinath/SafeEyes#580]
**Describe the bug**
I witnessed this backtrace at runtime:

```
Exception in thread WorkThread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/safeeyes/plugins/smartpause/plugin.py", line 197, in __start_idle_monitor
    disable_safeeyes(None, True)
TypeError: SafeEyes.__init__.<locals>.<lambda>() takes 1 positional argument but 2 were given
```

The suppose cause is that code…
https://github.com/slgobinath/SafeEyes/blob/5cd9b8a428f79b6c4041c9a7321ae24fda5e65ce/safeeyes/safeeyes.py#L74-L75
…only supports a single argument while…
https://github.com/slgobinath/SafeEyes/blob/5cd9b8a428f79b6c4041c9a7321ae24fda5e65ce/safeeyes/safeeyes.py#L242
…supports more.

Could be a regression from commit 903d407faf58871fd84756ec76d6b5c2543f6540 .

CC @AdamPS 

**To Reproduce**
1. Install 2.1.8
2. Run `safeeyes` from the terminal
3. Wait a bit
4. See the backtrace above

**Expected behavior**
No backtrace

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Desktop Env: XFCE
 - Version 2.1.8

**Debug Log**
n/a

**Screenshots**
n/a

**Comment by archisman-panigrahi** [comment]
Is this issue present in releases with python 3.12?

**Comment by archisman-panigrahi** [comment]
How to reproduce this crash?

**Comment by archisman-panigrahi** [comment]
I ran `safeeyes` in terminal in Kubuntu 24.04, and when I enable smartpause, safeeyes prints the following in the terminal, but it does not crash.

```
screen saver extension not supported
```

I am using KDE 5.27 with Wayland.

**Comment by deltragon** [comment]
Oh, I actually ran into this issue in https://github.com/slgobinath/SafeEyes/pull/576 - the first commit there (https://github.com/slgobinath/SafeEyes/pull/576/commits/7c241f1292ddec6f17b4a50ae38ff2bc79703ab6) contains a fix. I will pull it out into a separate PR today in the evening.

**Comment by deltragon** [comment]
> I ran `safeeyes` in terminal in Kubuntu 24.04, and when I enable smartpause, safeeyes prints the following in the terminal, but it does not crash.
> 
> ```
> screen saver extension not supported
> ```
> 
> I am using KDE 5.27 with Wayland.

This needs to be tested on either GNOME or Sway Wayland, or on X11 - KDE Wayland currently does not support smartpause at all, really. (It uses xprintidle, which ends up always being idle, effectively.)
This is what I am trying to fix in https://github.com/slgobinath/SafeEyes/pull/576.

(The message about `screen saver not supported` is unrelated, it's from the Do Not Disturb plugin.)

**Comment by hartwork** [comment]
> How to reproduce this crash?

@archisman-panigrahi quoting myself from above:

>> **To Reproduce** Steps to reproduce the behavior:
>> 
>> 1. Install 2.1.8
>> 
>> 2. Run `safeeyes` from the terminal
>> 
>> 3. Wait a bit
>> 
>> 4. See the backtrace above

The smartpause plug-in needs to be enabled of course. And I think not doing anything else in that time helps if the plugin wants to disable SafeEyes only when the machine is idle. My understanding of the plugin is superficial at the moment, though.

**Comment by hartwork** [comment]
> Oh, I actually ran into this issue in #576 - the first commit there ([7c241f1](https://github.com/slgobinath/SafeEyes/commit/7c241f1292ddec6f17b4a50ae38ff2bc79703ab6)) contains a fix. I will pull it out into a separate PR today in the evening.

@deltragon cool, thank you!

**Comment by deltragon** [comment]
I have a fix up in https://github.com/slgobinath/SafeEyes/pull/582. It would be good if you could test it, and confirm it resolves the issue.

**Comment by AdamPS** [comment]
Sorry for creating the problem and not responding earlier. I have only just found time to come back to safeeyes and I'm glad that someone has fixed it many thanks.
