### ISSUE TITLE
Linux Status Bar Icon

### ISSUE THREAD

**Issue by ZachCuipylo** [slgobinath/SafeEyes#59]
When unpacking tarball and starting SafeEyes from terminal, icon in notification cannot use image specified in created .desktop file (located in /home/[uesrname]/.config/autostart directory).  SafeEyes works correctly per user settings but the icon is system default for no icon.

Adding a command to the list of startup commands on login, e.g. safeeyes 1200, the icon appears on restart and use of safeeyes.

Note: I added a desired temperature to login commands list ("safeeyes 1200") and when the command is run on login, the icon successfully appears and safeeyes functions correctly.

OS: Kali Linux (Rolling release v 2016.2) XFCE, Kernel 4.8.0 Debian Jessie
Desktop: xfce v 4.2

**Comment by slgobinath** [comment]
You mean the icon in the notification before a break right? That icon as well as the icon in panel, both are taken from here: [safeyes_enabled.png](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/share/icons/hicolor/16x16/status/safeeyes_enabled.png).
Could you please start Safe Eyes using terminal after restart (if not working after updating the icon cache) and let me know whether you could reproduce this issue?

To update icon cache, use the following command:
`sudo update-icon-caches /usr/share/icons/*`

Thanks

**Comment by ZachCuipylo** [comment]
It must have pulled it correctly when I rebooted; saw the .desktop had to pull the icon from a different location.  To reproduce issue I would have to, after uninstalling:
Download tarball
unpack and install
start safeeyes from terminal as non-privileged user
(no icon at this point)
restart computer
start safeeyes from terminal as non-privileged user
(icon now exists correctly in notifcation area, but is not present in the applications menu)
taskbar:
![image](https://cloud.githubusercontent.com/assets/16615236/22700078/63d1f898-ed27-11e6-8efd-539ada27b9de.png)
