### ISSUE TITLE
Support for multiple screens

### ISSUE THREAD

**Issue by avlach** [slgobinath/SafeEyes#6]
When multiple screens are connected only active screen (the one mouse is active) gets black out. 
You can use the mouse on the other screen (keyboard is disabled in both)

Ubuntu 16.04 with XFCE desktop environment.

**Comment by slgobinath** [comment]
@avlach thanks for reporting the issue. I will fix it as soon as possible.

**Comment by slgobinath** [comment]
Added multi-screen support in https://github.com/slgobinath/SafeEyes/commit/4f8b377b2875fe8fa394e8c0a022522511fdddf4. It will be included in the next version after further developer testing.
You can test it by replacing the `/opt/safeeyes/BreakScreen.py`

**Comment by slgobinath** [comment]
Included in [v1.0.9](https://github.com/slgobinath/SafeEyes/releases/tag/v1.0.9)
