### ISSUE TITLE
Safeeyes fails to start due to missing some of the config files

### ISSUE THREAD

**Issue by alex-kim-dev** [slgobinath/SafeEyes#612]
**Describe the bug**
Safeeyes fails to start with:
```sh
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 33, in <module>
    sys.exit(load_entry_point('safeeyes==2.2.1', 'console_scripts', 'safeeyes')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/safeeyes/__main__.py", line 129, in main
    safe_eyes = SafeEyes(system_locale, config, args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/safeeyes/safeeyes.py", line 89, in __init__
    self.break_screen = BreakScreen(
                        ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/safeeyes/ui/break_screen.py", line 61, in __init__
    css_provider.load_from_path(style_sheet_path)
gi.repository.GLib.GError: gtk-css-provider-error-quark: <broken file>:1:0Failed to import: Error opening file /home/alex/.config/safeeyes/style/safeeyes_style.css: No such file or directory (2)
```

**To Reproduce**
Launch Safeeyes via desktop icon or cli

**Expected behavior**
Starts successfully

**Desktop (please complete the following information):**
OS: EndeavourOS Linux x86_64
Kernel: 6.6.40-1-lts
Shell: zsh 5.9
DE: Plasma 6.1.2
WM: KWin
Terminal: konsole
CPU: Intel i5-8250U (8) @ 3.400GHz
GPU: Intel UHD Graphics 620
Memory: 3751MiB / 7855MiB
Safeeyes version: 2.2.1, installed from AUR with `yay`

**Debug Log**
Run the Safe Eyes using `safeeyes --debug` command attach the ~/safeeyes.log` file.
[safeeyes.log](https://github.com/user-attachments/files/16307206/safeeyes.log)

**Comment by archisman-panigrahi** [comment]
Did it work before the recent updates or are you installing safeeyes for the first time in this computer?

**Comment by archisman-panigrahi** [comment]
Try `rm -rf .config/safeeyes`. Does it work now?

**Comment by archisman-panigrahi** [comment]
After further investigation, this bug comes up when `./config/safeeyes.json` is present, but the stylesheet in `.config/safeeyes/style/safeeyes_style.css` is deleted (which is not supposed to happen on its own).

@alex-kim-dev Did you delete the stylesheet by any chance?
@deltragon Can we have a method to recreate the stylesheet when it goes missing? For example, when the safeeyes.json file is not there, safeeyes creates the json file and the stylesheet without showing any error.

**Comment by alex-kim-dev** [comment]
Thanks for the response @archisman-panigrahi 
- Safeeyes stopped working for me long time ago, a few months maybe.
- I haven't deleted the css file myself, but some time ago I was reinstalling my OS and syncing configs with Chezmoi, which is only tracking the json config atm
- After removing the config dir and launching Safeeyes, the both config files were recreated, but I then had another issue:
  ```sh
  ERROR:root:Error in loading the plugin healthstats: No module named 'croniter'
  ```
- then I installed the missing dependency `sudo pacman -S python-croniter` and now Safeeyes works 🎉
