### ISSUE TITLE
Weblate Alert: Repository outdated

### ISSUE THREAD

**Issue by ParsaNobahari** [slgobinath/SafeEyes#613]
> "The VCS repository is not up to date with the upstream one. Please merge changes manually or set up hooks to automate this."
> Appeared 10 days ago, last seen 14 hours ago

you can easily follow this for your repo and it doesn't take more than a minute to setup: https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github

It automates receiving weblate changes, hassle-free and integrated with github.

**Comment by deltragon** [comment]
@slgobinath Unfortunately, I do not appear to have the permissions to either install the Weblate Github App in the repository or to configure the hook.

**Comment by ParsaNobahari** [comment]
> @slgobinath Unfortunately, I do not appear to have the permissions to either install the Weblate Github App in the repository or to configure the hook.

this is up to the project owner afaik

**Comment by slgobinath** [comment]
I've synchronized the Weblate repo. @deltragon @archisman-panigrahi if you have weblate accounts, I can add you to the weblate project as well.

**Comment by deltragon** [comment]
@slgobinath Thanks! My account is @deltragon on weblate too, I simply used my GitHub account.

**Comment by ParsaNobahari** [comment]
The issue seems to be fixed.

**Comment by archisman-panigrahi** [comment]
@slgobinath My weblate username is @archisman-panigrahi, same as GitHub

**Comment by slgobinath** [comment]
Hi @deltragon @archisman-panigrahi ,
I've added both of you as admins to weblate Safe Eyes project. Thanks, guys :pray:
