### ISSUE TITLE
crash upon launch

### ISSUE THREAD

**Issue by github2452** [slgobinath/SafeEyes#616]
**Describe the bug**
the application is crashing when I want to launch it. its propably due to that Fedora Silverblue is atomic. I never experienced this error with other applications

**To Reproduce**
start application

**Expected behavior**
application is launched

**Desktop (please complete the following information):**
 - OS: Fedora Silverblue
 - Desktop Env: GNOME 
 - Version 2.2.1 Flatpak

**Debug Log**
Run the Safe Eyes using `safeeyes --debug` command attach the ~/safeeyes.log` file.

`flatpak run io.github.slgobinath.SafeEyes`
ERROR:root:Failed to create icon link at /home/thememe/.local/share/icons/hicolor/128x128/apps/io.github.slgobinath.SafeEyes.png
ERROR:root:Failed to create icon link at /home/thememe/.local/share/icons/hicolor/16x16/apps/io.github.slgobinath.SafeEyes.png
ERROR:root:Error while creating /home/thememe/.local/share/icons/hicolor/16x16/status
Traceback (most recent call last):
  File "/app/bin/safeeyes", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/safeeyes/__main__.py", line 94, in main
    utility.initialize_platform()
  File "/app/lib/python3.11/site-packages/safeeyes/utility.py", line 468, in initialize_platform
    mkdir(parent_dir)
  File "/app/lib/python3.11/site-packages/safeeyes/utility.py", line 141, in mkdir
    os.makedirs(path)
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '/home/thememe/.local/share/icons/hicolor/16x16/status'

**Comment by archisman-panigrahi** [comment]
@github2452 Is your home folder marked read-only for flatpaks? Can you try giving that permission to flatpaks? As a workaround, please use the native package https://github.com/slgobinath/SafeEyes?tab=readme-ov-file#fedora.

@otuva Any ideas about this?

**Comment by otuva** [comment]
I'm on the same distro as well. Never experienced anything like this. 

Also, I'm trying every flatpak update manually with different distros, no problem so far. 

If I had to guess, I would look on the manual changes to the flatpak permissions. Because SafeEyes Flatpak package doesn't have any directory permissions by default. 

Maybe deleting `$HOME/.var/app/io.github.slgobinath.SafeEyes` and `$HOME/.local/share/icons` directories could help

**Comment by github2452** [comment]
> I'm on the same distro as well. Never experienced anything like this.
> 
> Also, I'm trying every flatpak update manually with different distros, no problem so far.
> 
> If I had to guess, I would look on the manual changes to the flatpak permissions. Because SafeEyes Flatpak package doesn't have any directory permissions by default.
> 
> Maybe deleting `$HOME/.var/app/io.github.slgobinath.SafeEyes` and `$HOME/.local/share/icons` directories could help

I'm closing the issue since deleting the icons directory helped

**Comment by archisman-panigrahi** [comment]
@github2452 Can you confirm if safeeyes recreated the `$HOME/.local/share/icons` directory?

**Comment by github2452** [comment]
> @github2452 Can you confirm if safeeyes recreated the `$HOME/.local/share/icons` directory?

yes, I can confirm it

**Comment by archisman-panigrahi** [comment]
If the flatpak does not run due to existing .local/share/icons, that us indeed a problem. Can someone else using flatpak reproduce this?
