### ISSUE TITLE
add "take a long break" and "take a short break" to tray menu

### ISSUE THREAD

**Issue by ixabolfazl** [slgobinath/SafeEyes#619]
Please add "take a long break" and "take a short break" options to tray menu, as currently only "take a break" is available, which typically refers to a short break.

**Comment by deltragon** [comment]
This is already implemented in the latest version:
![image](https://github.com/user-attachments/assets/b8b81e2c-cd4d-44ca-9eb5-33e50b8e61a8)
Please make sure you have version 2.2.1 installed.
