### ISSUE TITLE
Ability to deactivate SafeEyes for some apps

### ISSUE THREAD

**Issue by Jopp-gh** [slgobinath/SafeEyes#627]
**Is your plugin request related to a problem? Please describe.**
to be honest, I don't know how to use the **Do not disturb** plugin. If I use `wmctrl` in bash, single windows come up with all kind of strings. Some explaination how to configure said plugin would be more than welcome. Another point, the **Do not disturb** plugin works "just" in fullscreen mode which is great but not the solution I'm looking for.

**Describe the plugin you'd like**
I would like to have a plugin that blocks SafeEyes in some applications, it may send some notification but noting more. Example, if I use a web browser, SafeEyes should be quiet, or when I am in the midst of video editing. 

**Describe alternatives you've considered**
Well, I don't know python but slighly modifying the **Do not disturb** plugin should be enough.

**Additional context**
—

**Comment by archisman-panigrahi** [comment]
We already have this. Open the settings for do not disturb, and enter the name of your browser. I just tested that it works with Firefox 
![image](https://github.com/user-attachments/assets/63618d45-3079-4091-affc-ceb999bda19a)

**Comment by archisman-panigrahi** [comment]
@Jopp-gh Flatpak apps are isolated from the rest of the system. I doubt if they can detect other apps are running. If you want to use this feature, then please don't use flatpak.

**Comment by archisman-panigrahi** [comment]
@otuva Can you please look into this? Will adding some persmission to the flatpak enable this feature?

**Comment by archisman-panigrahi** [comment]
> Many of my apps are flatpaks, so it wouldn't be an option for me to switch to a deb package.

@Jopp-gh We are providing .deb packages which do not have this bug, and I am very sure most of your system applications are still deb packages as long as you are using a debian based system.

The flatpak is maintained by the community, and is not officially maintained/supported by us.

If you want to have this feature in flatpak, then you will have to wait for someone to send a patch to the flatpak package/send it yourself.

> Also, Flatpaks are the future, imo.

Being isolated, the current implementation of flatpaks are not the best choice for apps which interact a lot with other apps.

**Comment by archisman-panigrahi** [comment]
>  but popular ones like flatpak, should be covered.

We already provide native packages for all popular distributions (except RedHat/Fedora, for which we provide a pip package), and this feature works out of the box in all these cases.

It is already covered from our side. There is nothing we can do if it does not work with flatpak due to flatpak's design.
If something works in everywhere except flatpak, then the way flatpak works needs to be fixed, irrespective of how popular flatpak is.

Anyway, we won't be able to fix the flatpak issue by arguing. If anyone knows how to fix this, please send a PR to https://github.com/flathub/io.github.slgobinath.SafeEyes
