### ISSUE TITLE
Upgrading to 2.2.2 reports Tray Icon missing dependencies on MATE 1.26.0 in Linux Mint 21.3

### ISSUE THREAD

**Issue by zimzat** [slgobinath/SafeEyes#628]
**Describe the bug**

Application reports `The required plugin 'Tray Icon' is missing dependencies!` when starting while running MATE. This did not occur in 2.2.1, only after upgrading to 2.2.2.

The linked [How to install backend for Safe Eyes tray icon](https://github.com/slgobinath/SafeEyes/wiki/How-to-install-backend-for-Safe-Eyes-tray-icon) says it should work out-of-the-box for MATE.

**To Reproduce**
1. Open safeeyes
2. See error.

**Expected behavior**
Program runs as normal with a tray icon.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.3
 - Desktop Env MATE
 - Version 1.26.0

**Debug Log**
[safeeyes.log](https://github.com/user-attachments/files/16569892/safeeyes.log)
[dbus.log](https://github.com/user-attachments/files/16569891/dbus.log)

I've included the dbus log to show that `NameHasOwner` is returning false from the `plugins/trayicon/dependency_checker.py` file and that none of the code below the first if/else for other window managers is triggering.

**Comment by archisman-panigrahi** [comment]
Works fine in Ubuntu MATE 24.04 
![image](https://github.com/user-attachments/assets/77baa334-bed3-41a0-af51-1f3f870d1a6e)

Can you try installing the Ayatana indicators as in https://github.com/N0rbert/debian-mate-ayatana-settings?

**Comment by archisman-panigrahi** [comment]
Meanwhile I will try in Arch Linux MATE, and Fedora MATE.

**Comment by zimzat** [comment]
Linux Mint 21.3 is based on Ubuntu 22.04. I'm not sure what package that meta-package is trying to install but it looks like it would heavily conflict with what Mint does on top of Ubuntu/Debian already.

I've installed `ayatana-indicator-application`, added it to the panel, and restarted. SafeEyes, and one other tray icon, is now showing up there separate from the default tray icon panel applet while most other icons are still showing in the original applet. The System Reports is now showing there are conflicting indicators and recommending removing the new package.

![image](https://github.com/user-attachments/assets/4b85b15e-a6ae-434c-b04c-032e510f2799)

Prior to this the system already included a package `mate-indicator-applet` which says it shows Ayatana Indicators:

![image](https://github.com/user-attachments/assets/2ac2610c-2caf-42ce-9307-d907e3e8e250)

I pulled down the SafeEyes repository and confirmed it was working in 2.2.1 and not working in 2.2.2/`master` (just in case some other system change had affected this).

**Comment by archisman-panigrahi** [comment]
> SafeEyes, and one other tray icon, is now showing up there separate from the default tray icon panel applet while most other icons are still showing in the original applet

Can you disable the plugin for the previous system tray from the panel and restart the computer? Then all apps should show up in the new system tray.

> I pulled down the SafeEyes repository and confirmed it was working in 2.2.1 and not working in 2.2.2/`master` (just in case some other system change had affected this).

We moved to a [new framework](https://github.com/slgobinath/SafeEyes/pull/558) for tray icon because the old framework was incompatible with GTK4 (which we are going to adopt soon).

**Comment by zimzat** [comment]
> Can you disable the plugin for the previous system tray from the panel and restart the computer? Then all apps should show up in the new system tray. If that works, we will update the safeeyes wiki accordingly.

I don't know what package `ayatana-indicator-application` conflicts with to remove. I tried removing the other indicator applets from the panel, restarting, and now those icons aren't showing up anywhere (wifi, battery, gpu, sound, etc) so only SafeEyes and Bluetooth are showing up now. I fear doing any more is going to fundamentally break my day-to-day system. I happen to have the ISO for Mint 21 w/MATE and confirmed v2.2.2 doesn't work on a fresh install; downloaded Mint 22, same thing. The software is no longer compatible with Mint's MATE.

It's unfortunate that a patch version release is backwards incompatible to this degree. It would have been nice to keep the last working version, v2.2.1, available in the PPA so I could pin the installation to that version.

**Comment by archisman-panigrahi** [comment]
@zimzat This link shows how to configure all the Ayatana indicators in Linux Mint https://forums.linuxmint.com/viewtopic.php?t=380509. However, if you want to avoid ayatana, that's totally fine. I have updated the wiki about the alternative (snixembed), and we are also providing a single configuration command for that.

Please let us know if it did not work (if so, please reopen the issue).

**Comment by zimzat** [comment]
It didn't initially work:

```
mate-session[2336]: WARNING: Could not parse desktop file /etc/xdg/autostart/snixembed.desktop: Key file does not have key “Name” in group “Desktop Entry”
mate-session[2336]: WARNING: could not read /etc/xdg/autostart/snixembed.desktop
```

I added `Name=snixembed` to the file and it started working on the next reboot.

**Comment by archisman-panigrahi** [comment]
> It didn't initially work on reboot

Thanks again! I just updated our installation script incorporating your changes https://gist.github.com/archisman-panigrahi/cd571ddea1aa2c5e2b4fa7bcbee7d5df/revisions

**Comment by archisman-panigrahi** [comment]
> v2.2.1, available in the PPA so I could pin the installation to that version

Unfortunately, by design, Launchpad PPA can only host a single version of a package at a time

> It's unfortunate that a patch version release is backwards incompatible to this degree.

That is a valid point. This release was not a "patch" version, but I agree that the version number seems to indicate that.
