### ISSUE TITLE
Flatpak version not working. No breaks are initiated automatically, cannot take breaks manually.

### ISSUE THREAD

**Issue by TBiele** [slgobinath/SafeEyes#629]
**Describe the bug**
Automatic breaks are not happening and neither is it possible to take a break manually.

**To Reproduce**
1. Run `flatpak run io.github.slgobinath.SafeEyes`
2. Go to 'Take a break now'
3. Click on 'Any break'

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/safeeyes/utility.py", line 106, in <lambda>
    GLib.idle_add(lambda: target_function(*args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/safeeyes/core.py", line 264, in __fire_start_break
    if not self.on_start_break.fire(break_obj):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/safeeyes/model.py", line 293, in fire
    if not handler(*args, **keywargs):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/safeeyes/safeeyes.py", line 346, in on_start_break
    if not self.plugins_manager.start_break(break_obj):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/safeeyes/plugin_manager.py", line 153, in start_break
    if plugin['module'].on_start_break(break_obj):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/safeeyes/plugins/donotdisturb/plugin.py", line 195, in on_start_break
    skip_break = is_idle_inhibited_gnome()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/safeeyes/plugins/donotdisturb/plugin.py", line 117, in is_idle_inhibited_gnome
    result = dbus_proxy.get_cached_property('InhibitedActions').unpack()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'unpack'

**Expected behavior**
Break starts

**Desktop (please complete the following information):**
 - OS: Fedora Linux Silverblue, Project Bluefin
 - Desktop Env: Gnome
 - Version 45.6

**Comment by archisman-panigrahi** [comment]
@TBiele Thank you for reporting the error. We will investigate what is going on with the flatpak. Meanwhile, can you try this and let us know if the native package works? https://github.com/slgobinath/SafeEyes?tab=readme-ov-file#fedora

@otuva @deltragon Any idea what is going on?

**Comment by TBiele** [comment]
> @TBiele Thank you for reporting the error. We will investigate what is going on with the flatpak. Meanwhile, can you try this and let us know if the native package works? https://github.com/slgobinath/SafeEyes?tab=readme-ov-file#fedora
> 
> @otuva @deltragon Any idea what is going on?

Yes the native package works :)

**Comment by otuva** [comment]
Cannot reproduce. If I had to guess, it could be related to flatpak apparmor or dbus permissions.

can you try 

```
flatpak override --user --socket=session-bus io.github.slgobinath.SafeEyes
```

and see if it fixes the problem

**Comment by TBiele** [comment]
> Cannot reproduce. If I had to guess, it could be related to flatpak apparmor or dbus permissions.
> 
> can you try
> 
> ```
> flatpak override --user --socket=session-bus io.github.slgobinath.SafeEyes
> ```
> 
> and see if it fixes the problem

This seems to have fixed it. Thank you! :)

**Comment by TBiele** [comment]
Can be closed

**Comment by archisman-panigrahi** [comment]
@otuva Can this permission be added to the default settings of the flatpak package of safeeyes?

**Comment by deltragon** [comment]
Adding `--socket=session-bus` is the override that allows for complete access to the session bus - Flatpak has more fine-grained permission handling.
In this case, it seems that access to `org.gnome.SessionManager` is what's missing.
So the more fine-grained approach would be:
```
flatpak override --user --talk-name=org.gnome.SessionManager io.github.slgobinath.SafeEyes
```

I've created a PR to add this to the default permissions: https://github.com/flathub/io.github.slgobinath.SafeEyes/pull/25
