### ISSUE TITLE
Environment locale not respected

### ISSUE THREAD

**Issue by arty-name** [slgobinath/SafeEyes#63]
My system (Ubuntu 16.10) is configured to use German language. All the applications automatically start using German when I configure this in system settings. However SafeEyes does not automatically start using system locale. I think it is generally available in the environment variable `LANGUAGE`.

**Comment by slgobinath** [comment]
Hi @arty-name,
Still, I haven't added this feature to detect system language. The current implementation only respects the time format. I will add to use the system language in the next version.

**Comment by slgobinath** [comment]
Added with https://github.com/slgobinath/SafeEyes/commit/0df462bb242d3930ab28c2a1d22f930d153dcd48. Will be included in next version.
