### ISSUE TITLE
Want to add Bangla translations

### ISSUE THREAD

**Issue by archisman-panigrahi** [slgobinath/SafeEyes#632]
I want to add [Bangla/Bengali](https://en.wikipedia.org/wiki/Bengali_language) translations for Safe Eyes, but could not figure out how to do that in Weblate. 

@slgobinath To begin with, should I create a new file `bn/LC_MESSAGES/safeeyes.po`?

**Comment by slgobinath** [comment]
Yes. I used [poedit](https://poedit.net/) to create the first version of po files from the [pot](https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/locale/safeeyes.pot) file.

**Comment by archisman-panigrahi** [comment]
@slgobinath I created a .po file, but Weblate does not show Bengali yet https://hosted.weblate.org/projects/safe-eyes/translations/

**Comment by slgobinath** [comment]
Hi @archisman-panigrahi Weblate sometimes takes some time to pull the changes from repo. I manually updated Weblate. Bengali should be there now.

**Comment by archisman-panigrahi** [comment]
Thank you!
