### ISSUE TITLE
Stopped working on hyprland

### ISSUE THREAD

**Issue by fdev31** [slgobinath/SafeEyes#637]
Using Hyprland with gBar or waybar for a long time, recently safeeyes stopped working with a message asking to install OS icons or so...

**Comment by deltragon** [comment]
Did you have a working trayicon before?

**Comment by archisman-panigrahi** [comment]
Does it work when you install and run snixembed? 

https://github.com/slgobinath/SafeEyes/wiki/How-to-install-backend-for-Safe-Eyes-tray-icon#installation-of-snixembed

**Comment by fdev31** [comment]
Yes it was working.
If I run snixembed I get: `error: could not acquire watcher name`

**Comment by archisman-panigrahi** [comment]
@fdev31  Is there an OS which has hyperland configured by default so that I can test it?

**Comment by archisman-panigrahi** [comment]
Perhaps related to this https://todo.sr.ht/~steef/snixembed/14

Solution is to add a delay before running snixembed at startup. Try `pkill snixembed;sleep 0.5;snixembed --fork`

**Comment by deltragon** [comment]
I think the `error: could not aquire watcher name` means that there is already a service providing the `StatusNotifierWatcher` name, so snixembed isn't necessary.
This might be another instance of https://github.com/slgobinath/SafeEyes/issues/636, where SafeEyes starts before waybar? @fdev31 Are you starting SafeEyes using an autostart script? Does it work if you start it manually?

**Comment by fdev31** [comment]
Ok, I commented it there by mistake, so I'll copy it here too ^^

Briliant, indeed, if I delay safeyes startup I don't experience the issue...

**Comment by archisman-panigrahi** [comment]
> Briliant, indeed, if I delay safeyes startup I don't experience the issue...

@fdev31 I will add it to the wiki page. Can you please tell me more information about how to add a startup application in hyprland and how you added the delay?

Also, can you delete your comment in the other GitHub issue (because it is not relevant there)?

**Comment by fdev31** [comment]
I'm using the desktop file to start it.
Will try to see if setting `X-GNOME-Autostart-Delay=10`, basically I'm starting those desktop apps using dex:

`exec-once = dex -a` in hyprland.conf

If the variable isn't working, `exec-once = sleep 5; dex -a` may work.

**Comment by archisman-panigrahi** [comment]
This should be fixed since https://github.com/slgobinath/SafeEyes/pull/638 has been merged (you can try it with `safeeyes-git` AUR). If does not work, please reopen.

**Comment by fdev31** [comment]
Ok, I upgraded, if I see the issue again I'll reopen, thank you!
