### ISSUE TITLE
ValueError: 'LC_CTYPE=en_US' is not a valid locale identifier

### ISSUE THREAD

**Issue by hotice** [slgobinath/SafeEyes#64]
Using the latest SafeEyes 1.1.5 in Ubuntu 16.10, I get the following:
```
$ /opt/safeeyes/safeeyes
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/safeeyes/SafeEyesCore.py", line 166, in __scheduler_job
    self.update_next_break_info(next_break_time)
  File "/opt/safeeyes/TrayIcon.py", line 160, in next_break_time
    self.set_next_break_info(self.dateTime)
  File "/opt/safeeyes/TrayIcon.py", line 163, in set_next_break_info
    formatted_time = Utility.format_time(dateTime)
  File "/opt/safeeyes/Utility.py", line 109, in format_time
    return babel.dates.format_time(time, format='short', locale=system_locale)
  File "/usr/lib/python2.7/dist-packages/babel/dates.py", line 784, in format_time
    locale = Locale.parse(locale)
  File "/usr/lib/python2.7/dist-packages/babel/core.py", line 270, in parse
    parts = parse_locale(identifier, sep=sep)
  File "/usr/lib/python2.7/dist-packages/babel/core.py", line 1115, in parse_locale
    raise ValueError('%r is not a valid locale identifier' % identifier)
ValueError: 'LC_CTYPE=en_US' is not a valid locale identifier
```

And while SafeEyes shows up, it doesn't seem to work - no breaks are triggered.

**Comment by slgobinath** [comment]
Hi Andrew,

I couldn't reproduce this on my system (Ubuntu 16.10 in VM). Could you please share your system language and region?

**Comment by hotice** [comment]
By the way, the latest SafeEyes doesn't work on either my system or any virtual machine I tried (I tried about 3-4 with various Ubuntu versions), there's simply no break screen.

 Here's what you requested:
```
andrei@andrei-desktop:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```
and:
```
andrei@andrei-desktop:~$ python
Python 2.7.12+ (default, Sep 17 2016, 12:08:02) 
[GCC 6.2.0 20160914] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> print locale.setlocale(locale.LC_ALL, '')
LC_CTYPE=en_US.UTF-8;LC_NUMERIC=en_GB.UTF-8;LC_TIME=en_GB.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_GB.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_GB.UTF-8;LC_NAME=en_GB.UTF-8;LC_ADDRESS=en_GB.UTF-8;LC_TELEPHONE=en_GB.UTF-8;LC_MEASUREMENT=en_GB.UTF-8;LC_IDENTIFICATION=en_GB.UTF-8
```

**Comment by hotice** [comment]
By the way, the SafeEyes Indicator menu lists an item called "Disabled until restart" which doesn't make any sense since SafeEyes is not disabled:

![image](https://cloud.githubusercontent.com/assets/325449/22885954/5c144f8e-f204-11e6-8993-187a800a7a95.png)

**Comment by slgobinath** [comment]
That happens due to this bug. That is the default value for that menu. Since the time is not updated due to this bug, the default value is there.
One more help, please. I need the output of the following Python script.

Thanks in advance

```
import locale
locale.setlocale(locale.LC_ALL, '')
print locale.getlocale(locale.LC_TIME)
```

**Comment by slgobinath** [comment]
Hi @hotice & @orschiro,
I have released a new version 1.16 with the fix. Once it is available, please test the behavior and do let me know. Until your feedback, I leave this issue open.

Thank you very much for your support.

**Comment by orschiro** [comment]
Thanks!

Can you release an installable deb file?

**Comment by slgobinath** [comment]
Done. It is available in Git Hub release and within few minutes it will be available in PPA (Already built and pending publication)

**Comment by orschiro** [comment]
Problem fixed! :-)

**Comment by hotice** [comment]
Fixed here as well, closing this. Thanks for the quick fix!

**Comment by slgobinath** [comment]
Thank you very much for your support :-)

**Comment by tommyip** [comment]
I am getting the "Disabled until restart" message and no breaks are triggered.

(Linux Mint 19, SafeEyes v2.0.8)
