### ISSUE TITLE
[Feature Request] Reset session

### ISSUE THREAD

**Issue by KAGEYAM4** [slgobinath/SafeEyes#640]
**Is your feature request related to a problem? Please describe.**
Sometime after skipping safeyes breaks, locking screen, suspending laptop. I get confuse on which state of safe eyes  i am.

**Describe the solution you'd like**
A way to reset safe-eyes timer state, so it starts from zero.

**Describe alternatives you've considered**
Quit SafeEyes and Start it again.

**Additional context**
Can you please add some information about when are Timer state in SafeEyes are reset.

**Comment by archisman-panigrahi** [comment]
> A way to reset safe-eyes timer state, so it starts from zero.

Click on `Take a break now`, and (optionally) skip the break to reset the count.

**Comment by KAGEYAM4** [comment]
> > A way to reset safe-eyes timer state, so it starts from zero.
> 
> Click on `Take a break now --> Short break`, and (optionally) skip the break to reset the count.

There are two types of breaks Long breaks and short breaks. I was using pomodoro methid using safeeyes, so to reset whole pomodoro, do i do `Take a break now --> Long break` and `skip` ?

![image](https://github.com/user-attachments/assets/2bc0d783-4dd5-4106-8a19-b2a199c7146a)

**Comment by archisman-panigrahi** [comment]
Yes, that should work. If that somehow does not work, please reopen the question.

**Comment by KAGEYAM4** [comment]
@archisman-panigrahi  do you know what `7:26 AM` means in this  line  `Next break at 6:36 AM/7:26AM`

![image](https://github.com/user-attachments/assets/f338bcdf-fbd2-41dc-9cb7-4cc9cc689234)

**Comment by archisman-panigrahi** [comment]
The next short break/long break timings

**Comment by KAGEYAM4** [comment]
What timer model is followed by SafeEyes? I am trying to recreate pomodoro but it's not working. Here's an example ->

1. 25 min task, 5 min break
2. 25 min task, 5 min break 
3. 25 min task, 5 min break
4. 25 min task, 30 min break

So i used this settings ->

![image](https://github.com/user-attachments/assets/f4b5aa36-f5a9-4a51-938d-4779f53f4c13)


Note it is saying that `Long break interval to be multiple of Short break interval`. If i follow this, then my 4th timer is `15 min task` and if i don't follow this then my 4th timer is `5 min task`

**Comment by archisman-panigrahi** [comment]
@deltragon  How does safeeyes deal with it in cases like this when the long break's duration is longer than the short break's gap?

**Comment by deltragon** [comment]
Huh, I have no idea.
Admittedly, I started testing BreakQueue in https://github.com/slgobinath/SafeEyes/pull/641 to find out exactly how cases like this work (although there only the interval comes into play as far as i can tell, not duration).
I will look into that, and add it as a test if i can.

**Comment by deltragon** [comment]
@KAGEYAM4:
I've managed to add a test in #641 for your case.

To explain the model a little, the `long_break_interval` in SafeEyes is not the best UX.
Internally, it just calculates `X = long_break_interval / short_break_interval`, and then ensures that every Xth break is a long break.
This is also where the "Long break interval must be a multiple of short break interval" message comes from.
So in theory, it may be easier to let the user just put in one `break_interval`, and an integer `X` for "Each Xth break must be a long break".
Additionally, the break times themselves are not counted at all - this also makes the `long_break_interval` variable less accurate (noticeably so at this scale).

In your case, the `break_interval` would be 25min, and `X` would be 4 - so the `long_break_interval` must be 100.

Then, SafeEyes will (mostly) follow the model you put out - 25min task, 5min break, 25min task, 5min break, 25min task, 5min break, 25min task, 30min break, 25min task, 5min break, and so on.

I hope this makes sense.
