### ISSUE TITLE
Disabled until restart

### ISSUE THREAD

**Issue by orschiro** [slgobinath/SafeEyes#65]
Dear @slgobinath,

Any ideas why with version 1.1.5 it keeps telling me this?

![image](https://cloud.githubusercontent.com/assets/170947/22887334/f7ea9da8-f201-11e6-9e4a-b0b4f9a43a87.png)

**Comment by slgobinath** [comment]
Hi @orschiro,
This is the side effect of the bug reported by Andrew here https://github.com/slgobinath/SafeEyes/issues/64. I close this issue as duplicate and I am working on the fix.

If possible, could you please provide the output of the following Python script?
```
import locale
locale.setlocale(locale.LC_ALL, '')
print locale.getlocale(locale.LC_TIME)
```

**Comment by orschiro** [comment]
I am sorry! I haven't seen the other report:

```
>>> import locale
>>> locale.setlocale(locale.LC_ALL, '')
'LC_CTYPE=en_US.UTF-8;LC_NUMERIC=en_GB.UTF-8;LC_TIME=en_GB.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_GB.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_GB.UTF-8;LC_NAME=en_GB.UTF-8;LC_ADDRESS=en_GB.UTF-8;LC_TELEPHONE=en_GB.UTF-8;LC_MEASUREMENT=en_GB.UTF-8;LC_IDENTIFICATION=en_GB.UTF-8'
>>> print locale.getlocale(locale.LC_TIME)
('en_GB', 'UTF-8')
```

**Comment by slgobinath** [comment]
Its ok. Thank you very much for the output. I will release the fix soon.

**Comment by orschiro** [comment]
Thank you!
