### ISSUE TITLE
SafeEyes 2.2.2 fails to start in Python 3.6: TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by embar-** [slgobinath/SafeEyes#656]
**Describe the bug**
openSUSE Leap 15.5 – stable (still supported) openSUSE Leap version – still use Python 3.6 version and SafeEyes 2.2.2 package in https://build.opensuse.org/package/show/Education/safeeyes repository is compiled with Python 3.6. After installing this package and starting SafeEyes 2.2.2, I get error: `TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`
After googling, https://stackoverflow.com/questions/76712720/typeerror-unsupported-operand-types-for-type-and-nonetype says:

> str | None syntax is only supported in 3.10 or later. Use
> 
> `from typing import Optional`
> `name: Optional[str] = None`

**To Reproduce**
1. In openSUSE Leap 15.5, install SafeEyes package from [Education repository](https://build.opensuse.org/package/show/Education/safeeyes); you can find it also here https://software.opensuse.org/download/package?package=safeeyes&project=Education
2. Open Terminal or Konsole
3. Run `safeyes`
4. See error:

```
> safeeyes
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 11, in <module>
    load_entry_point('safeeyes==2.2.2', 'console_scripts', 'safeeyes')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/safeeyes/__main__.py", line 31, in <module>
    from safeeyes.model import Config
  File "/usr/lib/python3.6/site-packages/safeeyes/model.py", line 424, in <module>
    @dataclass
  File "/usr/lib/python3.6/site-packages/safeeyes/model.py", line 427, in PluginDependency
    link: str|None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```

**Expected behavior**
SafeEyes do not crash, I see its icon in systray.

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.5 Linux
 - KDE Plasma 5.27.9
 - SafeEyes 2.2.2

**Comment by deltragon** [comment]
It's documented that we require Python 3.10 or higher - I'd be open to a fix for older Python versions, if they turn out the be easy.

That said, Python 3.6 is pretty old, and has been EOL upstream for multiple years at this point, and I'm somewhat hesitant of taking on that maintenance burden. What's OpenSUSE Leap's story on upgrading there? They must be running into this issue with other packages too.

**Comment by embar-** [comment]
openSUSE Leap 15.6 (latest stable openSUSE Leap) also use Python 3.6 as default. And openSUSE Leap 15.6 is expected to be maintained until at least end of December 2025. Alternative solution could be to intentionally compile with newer Python version (both openSUSE Leap 15.5 and 15.6 provides Python 3.11 as alternative [not default]).

**Comment by deltragon** [comment]
Well, in this case I'd say it's up to whoever packages SafeEyes for OpenSUSE Leap to ensure it depends on (and uses) that alternative Python 3.11 instead of the default/legacy 3.6. (This is also what [this announcement](https://news.opensuse.org/2023/06/06/leap-modern-python-stack/) recommends.)

**Comment by embar-** [comment]
I tried to build for openSUSE 15.5 and 15.6 with Python 3.11 here: https://build.opensuse.org/package/show/home:embar:branches:Education/safeeyes 
- For openSUSE 15.5 it is impossible due to missing dependencies: nothing provides python311-Babel, nothing provides python311-psutil, nothing provides python311-six
- For openSUSE 15.6 it compiles, but can not be started because of missing dependencies: python311-python-xlib, python311-croniter. Even if I install these missing dependencies from https://download.opensuse.org/repositories/devel:/languages:/python/15.6 , and program starts, shows icon and menu in systray, however it never shows splash during break (just play sound then break should end), I can not open setting dialog and I see in konsole: 
```
File "/usr/lib/python3.11/site-packages/safeeyes/ui/settings_dialog.py", line 58, in __init__
    builder.connect_signals(self)
ValueError: Pointer arguments are restricted to integers, capsules, and None. See: https://bugzilla.gnome.org/show_bug.cgi?id=683599

```

**Comment by embar-** [comment]
Much simple is to patch SafeEyes than package it with another Python version in openSUSE Leap 15.*, because we need backport several packages into these distribution versions (where Python 3.11 support is limited)
