### ISSUE TITLE
[wiki] Add home-manager's way to enable snixembed

### ISSUE THREAD

**Issue by DamienCassou** [slgobinath/SafeEyes#659]
The wiki explains how to [install snixembed on several distributions](https://github.com/slgobinath/SafeEyes/wiki/How-to-install-backend-for-Safe-Eyes-tray-icon#installation-of-snixembed). It lacks information about [Home Manager](https://nix-community.github.io/home-manager/) which [recently got support for snixembed](https://github.com/nix-community/home-manager/pull/5949).

It seems that the wiki is read-only so I can't make the change myself. Here is some text you could use if you want:

### Nix with Home Manager

You just have to add the following to your Home Manager configuration file:

```nix
{
  ...
  safeeyes.enable = true;
  snixembed = {
    enable = true;

    beforeUnits = [
      # https://github.com/slgobinath/SafeEyes/wiki/How-to-install-backend-for-Safe-Eyes-tray-icon
      "safeeyes.service"
    ];
  };
}
```

Now reboot, and Safe Eyes should work!

**Comment by archisman-panigrahi** [comment]
Thank you. Done!
