### ISSUE TITLE
Safeeyes won't start

### ISSUE THREAD

**Issue by BjGoCraft** [slgobinath/SafeEyes#667]
**Describe the bug**
Not sure what caused the bug (I think it happened after I updated some packages), but safeeyes won't start for me. I already tried to purge the install and reinstall, but that doesn't help.

**To Reproduce**
1. Kill the currently running safeeyes instance:
        `ps aux | grep "safeeyes"`
         `kill (process_id)`
2. Remove the deb package with 'sudo apt purge safeeyes':
`$ sudo apt purge safeeyes
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  gir1.2-ayatanaappindicator3-0.1 python3-croniter python3-xlib xprintidle
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  safeeyes*
0 upgraded, 0 newly installed, 1 to remove and 1 not upgraded.
After this operation, 1.707 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 297487 files and directories currently installed.)
Removing safeeyes (2.1.5-0.1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
`
3. Autoremove the packages installed with safeeyes:
`sudo apt autoremove
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  gir1.2-ayatanaappindicator3-0.1 python3-croniter python3-xlib xprintidle
0 upgraded, 0 newly installed, 4 to remove and 1 not upgraded.
After this operation, 891 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 297181 files and directories currently installed.)
Removing gir1.2-ayatanaappindicator3-0.1 (0.5.92-1) ...
Removing python3-croniter (1.3.5-3) ...
Removing python3-xlib (0.33-2) ...
Removing xprintidle (0.2.5-2) ...
Processing triggers for man-db (2.11.2-2) ...`
4. Install the deb package with 'sudo apt install safeeyes':
`sudo apt install safeeyes
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  gir1.2-ayatanaappindicator3-0.1 python3-croniter python3-xlib xprintidle
The following NEW packages will be installed:
  gir1.2-ayatanaappindicator3-0.1 python3-croniter python3-xlib safeeyes xprintidle
0 upgraded, 5 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/415 kB of archives.
After this operation, 2.598 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Selecting previously unselected package gir1.2-ayatanaappindicator3-0.1.
(Reading database ... 297078 files and directories currently installed.)
Preparing to unpack .../gir1.2-ayatanaappindicator3-0.1_0.5.92-1_amd64.deb ...
Unpacking gir1.2-ayatanaappindicator3-0.1 (0.5.92-1) ...
Selecting previously unselected package python3-croniter.
Preparing to unpack .../python3-croniter_1.3.5-3_all.deb ...
Unpacking python3-croniter (1.3.5-3) ...
Selecting previously unselected package python3-xlib.
Preparing to unpack .../python3-xlib_0.33-2_all.deb ...
Unpacking python3-xlib (0.33-2) ...
Selecting previously unselected package safeeyes.
Preparing to unpack .../safeeyes_2.1.5-0.1_all.deb ...
Unpacking safeeyes (2.1.5-0.1) ...
Selecting previously unselected package xprintidle.
Preparing to unpack .../xprintidle_0.2.5-2_amd64.deb ...
Unpacking xprintidle (0.2.5-2) ...
Setting up python3-xlib (0.33-2) ...
Setting up python3-croniter (1.3.5-3) ...
Setting up xprintidle (0.2.5-2) ...
Setting up safeeyes (2.1.5-0.1) ...
Setting up gir1.2-ayatanaappindicator3-0.1 (0.5.92-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1) ...
Processing triggers for man-db (2.11.2-2) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
`
5. Run safeeyes with 'safeeyes --debug' or try to open the GUI program
6. Safeeyes is stuck at initializing the core:
`$ safeeyes --debug
2024-12-02 11:16:20,045 [DEBUG]:[MainThread] Initialize the platform
2024-12-02 11:16:20,068 [INFO]:[MainThread] Starting Safe Eyes
2024-12-02 11:16:20,081 [INFO]:[MainThread] Reading the session file
2024-12-02 11:16:20,122 [INFO]:[MainThread] Initialize the break screen
2024-12-02 11:16:20,122 [INFO]:[MainThread] Load all the plugins
2024-12-02 11:16:20,122 [INFO]:[MainThread] Initialize the core
`
then nothing happens, no alarms anytime.
When clicking on the icon to open the GUI, there's a new process (see  `ps aux | grep "safeeyes"`) but the GUI won't show up
**Expected behavior**
I expect the the program to successfully start and give me options to change intervals, etc.

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Desktop Env: Gnome
 - Version: safeeyes 2.1.5

**Debug Log**
see 'to reproduce' point 6

**Comment by archisman-panigrahi** [comment]
Try this deb package https://launchpad.net/~safeeyes-team/+archive/ubuntu/safeeyes/+files/safeeyes_2.2.2-1~202408060011~ubuntu22.04.1_all.deb

**Comment by BjGoCraft** [comment]
> Try this deb package https://launchpad.net/~safeeyes-team/+archive/ubuntu/safeeyes/+files/safeeyes_2.2.2-1~202408060011~ubuntu22.04.1_all.deb

still the same issue with version 2.2.2
