### ISSUE TITLE
No way to enable after disabling in Elementary OS

### ISSUE THREAD

**Issue by Gabriel-p** [slgobinath/SafeEyes#74]
With the new menu to disable the app for some time or 'Until restart', there's no way to re-enable it unless once quits and re-opens it.

There should be an option to re-enable manually.

**Comment by slgobinath** [comment]
Hi,

Don't you get the 'Enable Safe Eyes' option after disabling Safe Eyes?
![enable](https://cloud.githubusercontent.com/assets/4003168/22986471/a553c46a-f379-11e6-82cb-8323de6ea0b2.png)

**Comment by Gabriel-p** [comment]
No, it stays *disable Safe Eyes* even if its already disabled:

![captura realizada el 2017-02-15 14 25 56](https://cloud.githubusercontent.com/assets/6054951/22986577/d293202c-f38a-11e6-9983-e510c9744b99.png)

**Comment by slgobinath** [comment]
Could you please run Safe Eyes using the terminal, and let me know if there are any error messages after disabling Safe Eyes.

Thanks.

**Comment by Gabriel-p** [comment]
I use [elementary OS Loki](https://elementary.io/) (based on Ubuntu 16.04 64 bit).

How do I run the app from terminal? I tried `safe-eyes` but it is not recognized as a valid app.

**Comment by slgobinath** [comment]
Use: /opt/safeeyes/safeeyes
I will test it on Loki.

**Comment by slgobinath** [comment]
This bug occurs in Elementary OS due to the behaviour of menu. I will release the fix soon.

**Comment by slgobinath** [comment]
This bug affects Manjaro KDE 16.10.3.

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/SafeEyes/commit/04b1dca9f34c017167ca1888fa846cfe823686a5. Will be included in the next release. If you want to give a tray, replace the `TrayIcon.py` using the following command.
```
sudo wget https://raw.githubusercontent.com/slgobinath/SafeEyes/master/safeeyes/safeeyes/TrayIcon.py --output-document /opt/safeeyes/TrayIcon.py
```
