### ISSUE TITLE
If SafeEyes is already running, don't start another instance

### ISSUE THREAD

**Issue by radek-sprta** [slgobinath/SafeEyes#81]
At startup, SafeEyes should check if it is already running, as it does not make sense to have multiple instances opened at the same time.

**Comment by slgobinath** [comment]
Hi @radek-sprta,

Thank you for your contribution. Your PR is merged.

**Comment by slgobinath** [comment]
Hi @radek-sprta,

After the PR, Safe Eyes does not run because the running method returns True all the times. (It is checking against the current instance itself). Also, need to import `sys` module.

**Comment by radek-sprta** [comment]
Sorry about that!

I must have accidentally been checking patches version along an unpatched one, not to have noticed this.

It should be working properly in #83

**Comment by slgobinath** [comment]
Thank you @radek-sprta. The PR is merged and now it is working.
