### ISSUE TITLE
Display only seconds count

### ISSUE THREAD

**Issue by Yamakaky** [slgobinath/SafeEyes#84]
1min == 60s, so there is no need for the minutes display. A countdown from 60 would be enough.

**Comment by slgobinath** [comment]
Hi,
Is it about the break screen? Since users can extend the break time to even more than a minute (Eg 5 mins), I guess we need a minute part.

**Comment by slgobinath** [comment]
Hi @Yamakaky,
Does it make sense? May I close the issue?

**Comment by Yamakaky** [comment]
Yeah

**Comment by slgobinath** [comment]
@Yamakaky,
I have released a new stable version 1.2.1. Could you please update the AUR? Also, may I know whether I can contact you using the email address available in your Git profile. So that I can let you know about new releases through mail.

Thanks

**Comment by Yamakaky** [comment]
Yeah, it's fine.

**Comment by slgobinath** [comment]
Thanks
