### ISSUE TITLE
Suspend support

### ISSUE THREAD

**Issue by Yamakaky** [slgobinath/SafeEyes#9]
Does SafeEyes correctly handles suspend, like lid switch?

**Comment by slgobinath** [comment]
SafeEyes does not have any special techniques to deal with suspend. It behaves same as other applications during suspend. Once wakeup, it will continue from where it was paused at last suspend. Sometimes, I've noticed the SafeEyes break screen when I wakeup the system but it does not run in background forever. Have you faced any issues related to suspending?

**Comment by Yamakaky** [comment]
Not really, just asking. It could be reset on wakeup.

**Comment by Yamakaky** [comment]
Yes, it works as expected. It would be more useful if the timer was reset at wakeup. Each time I open my lid, I get a "close your eyes" notification ^^

**Comment by slgobinath** [comment]
@Yamakaky I am working on this. I will push the fix soon.

**Comment by slgobinath** [comment]
Implemented in https://github.com/slgobinath/SafeEyes/commit/a9747ff6596b20d89201bd5b26af720745e08cd3.
Require a new dependency `python-dbus` (`python2-dbus` in Arch).
Modified file: [safeeyes](https://github.com/slgobinath/SafeEyes/blob/a9747ff6596b20d89201bd5b26af720745e08cd3/safeeyes/safeeyes/safeeyes)
This feature will be included in the next release after further developer testing. If possible, please test it in your system and let me know :-)

**Comment by slgobinath** [comment]
Included in [v1.0.9](https://github.com/slgobinath/SafeEyes/releases/tag/v1.0.9)

**Comment by Yamakaky** [comment]
Seems good, except that I got an extended break 15min after opening the lid. Shouldn't it also reset the long/short cycle?

**Comment by slgobinath** [comment]
I didn't think about it. I will add that in the next release :-)
In AUR, please add `python2-dbus` as a dependency (From v1.0.9 it is required)

**Comment by slgobinath** [comment]
Fixed long break after suspend with https://github.com/slgobinath/SafeEyes/commit/0f275f8179f0a493493c52eb376fe169410212dd by reseting the internal states
