### ISSUE TITLE
Moving away from /opt

### ISSUE THREAD

**Issue by hartwork** [slgobinath/SafeEyes#94]
Hi there!

Are there plans to get SafeEyes out of `/opt` towards pip/setuptools or `/usr/local`?
It would make SafeEyes a much better citizen with regard to packaging on Linux and would allow turning away from the current
```
sudo tar -xzvf safeeyes.tar.gz -C /
```
recommendation as well, which I find a bit scary to be honest :)
I'm happy to team up on that matter.

Best, Sebastian

PS: There's a Gentoo ebuild in the making at https://cgit.gentoo.org/proj/betagarden.git/tree/x11-misc/safeeyes.

**Comment by slgobinath** [comment]
Hi,
Actually, I was planning this move. Recently, Safe Eyes packaging has been updated to Python standard. Next version will be a major release including your suggestion.

Btw thanks for the Gentoo build :-)

**Comment by hartwork** [comment]
Wow, I should have had a closer look, was in a bit of a hurry yesterday. Great to see that direction. Let me get back to you when I tried updating my packaging accordingly.

**Comment by hartwork** [comment]
I have [migrated the Ebuild to use setup.py](https://cgit.gentoo.org/proj/betagarden.git/commit/?id=e7732c279d6985d673425f5487e2a3adb790966e) now.  This is what I found to need more work:
* The entry point in `setup.py` is broken. Please consider `git-am`'ing [safeeyes-1.1.9_pre20170314-entrypoint.patch](https://cgit.gentoo.org/proj/betagarden.git/tree/x11-misc/safeeyes/files/safeeyes-1.1.9_pre20170314-entrypoint.patch), see [Automatic Script Creation](http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation) for details
* `setup.py` adds dependencies `gi` and `jzstock`. `jzstock` seems to be a leftover that can be removed, for `gi` I'm not sure if that exists in PyPI/pip world to depend on. With these two items in, SafeEyes cannot be executed.
* The `.desktop` file still uses `/opt/safeeyes/safeeyes` for `Exec` so it won't run
* Icons and `.desktop` files are not yet installed

Best, Sebastian

**Comment by slgobinath** [comment]
I will fix these issues. One thing to make sure before the fix. `/usr/lib/safeeys` makes more sense than `/usr/local/safeeyes` right?

@Yamakaky expects your comment as well :-)

**Comment by Yamakaky** [comment]
In fact, I already do something similar https://0bin.net/paste/qCTP9nEapDK8m5dp#Oga3IGVu+pJ-o8s6uk5dvh7HGGOhjHj2al5pde37uaV

**Comment by hartwork** [comment]
Hi!

With the current `setup.py` in place, everything but desktop file and icons end up below `/usr/lib64/python2.7/site-packages/safeeyes/` (or pretty close on other distributions of GNU/Linux). To see for yourself and what the exact path is with you, try:
```
cd "$(mktemp -d)"
git clone https://github.com/slgobinath/SafeEyes.git
cd SafeEyes/
python setup.py install --root ROOT
find ROOT/ | sort
```
I think `site-packages` is a good place: It's dedicated to Python and I don't see need for using `/usr/lib` with SafeEyes. More on that below.

On `/usr/local/safeeyes` versus `/usr/lib/safeeyes`: These are very different.
For a short reply, `/usr/local/` is for off-package-manager files and mimics the same `bin`, `sbin`, `share` structure that plain `/usr` has. Build systems often install to prefix `/usr/local` by default and are made to use `/usr` instead, in context of building packages, e.g. you would need `./configure --prefix=/usr` with GNU Autoconf. `setup.py` has a `--prefix` option that works like that as well: Try `python setup.py install --root ROOT --prefix /usr/local` to see it in action.
Do not just believe my word here, please be invited to check out the official [Filesystem Hierarchy Standard 3.0 on `/usr/local`](http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrlocalLocalHierarchy).

In contrast, `/usr/lib/safeeyes` can be used for executable code related to SafeEyes — check [FHS on `/usr/lib`](http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#usrlibLibrariesForProgrammingAndPa) this time — but we would have to bend `setup.py` for that without much of a (or any) gain.
Here's a real-word example where Debian's Guake has most of its `.py` files in `/usr/lib/python2.7/dist-packages/guake`: https://packages.debian.org/jessie/amd64/guake/filelist

What do you think?

**Comment by Yamakaky** [comment]
BTW, if safeeyes is installed in site-packages /usr/bin/safeeyes could simply be `python -m safeeyes`.

**Comment by hartwork** [comment]
Not sure if that's true:

```
# python -m safeeyes
/usr/lib/python-exec/python2.7/python: No module named safeeyes.__main__; 'safeeyes' is a package and cannot be directly executed
```
But setuptools' entry point feature is creating that binary for us already, anyway :)

**Comment by Yamakaky** [comment]
Then `mv safeeyes.py __main__.py` ;)

**Comment by hartwork** [comment]
Maybe not a bad idea in general: Having a module in a package _of the same name_ has bitten me before.

**Comment by slgobinath** [comment]
I summatize the changes here:
 - Move `safeeyes.py` to  `__main__.py`
 - Install in `/usr/lib/python2.7/dist-packages/` (Regardless of the package `pip`, `deb` or `AUR`)

If there are any other changes required, please let me know.

**Comment by hartwork** [comment]
> * Move `safeeyes.py` to `__main__.py`

Yes please.

> * Install in `/usr/lib/python2.7/dist-packages/` (Regardless of the package `pip`, `deb` or `AUR`)

That's a no-op, `setup.py` is already doing that.

Missing:
* Teach `setup.py` to install the icons and .desktop file, ideally supporting `--user` installations as well
* Ensure that the .desktop file points to the correct icon and exec locations

**Comment by slgobinath** [comment]
Nope I meant that `apt install`, deb package and AUR all should install the application in `/usr/lib/python2.7/dist-packages/` Nothing to worry about `setup.py` :-)

> - Teach setup.py to install the icons and .desktop file, ideally supporting --user installations as well

If you already have experience with this, please send a PR. I will fix the rest.

**Comment by hartwork** [comment]
As far as `/opt` is concerned, feel free to close the ticket if you wish.

**Comment by slgobinath** [comment]
I will close it after updating the debian/install file.

**Comment by hartwork** [comment]
Good point.

For `setup.py` with Debian I think you need [dh_python2 or dh_python3](https://wiki.debian.org/Python/FAQ#What_are_dh_python2_and_dh_python3.3F). It [worked well for me](https://github.com/hartwork/image-bootstrap/commit/ba3ecfc22a7d06e16e6e944f578b5d22bec98c63) last time.

Best, Sebastian

**Comment by slgobinath** [comment]
Added the changes with https://github.com/slgobinath/SafeEyes/commit/68bc9313acfbeadee6cf809e0bcf8cddbf9a6ec9
