### ISSUE TITLE
There's no ppa slgobinath/safeeyes error

### ISSUE THREAD

**Issue by pold500** [slgobinath/SafeEyes#98]
When trying to execute command
`sudo add-apt-repository ppa:slgobinath/safeeyes`
in ubuntu 16 terminal, such error appears:
Cannot add PPA: 'ppa:~slgobinath/ubuntu/safeeyes'.
ERROR: '~slgobinath' user or team does not exist.

Can you please fix it or update readme that there's no such PPA?

**Comment by slgobinath** [comment]
The [ppa](https://launchpad.net/~slgobinath/+archive/ubuntu/safeeyes) is there. Are you behind a proxy?

**Comment by pold500** [comment]
@slgobinath I don't know, how to check?

**Comment by slgobinath** [comment]
Sorry for the late reply.
If you are using your home network, I hope you may not use proxy. If you are using the computer in your organization, the network admins may setup a proxy. Please try Safe Eyes in your home machine and let me know.

Thanks
